package com.caskbycask.domain.spirit.dto;

import com.caskbycask.domain.spirit.entity.SpiritRegisterRequest;
import com.caskbycask.domain.spirit.entity.enums.RequestStatus;
import com.caskbycask.domain.spirit.entity.enums.SpiritCategory;
import com.caskbycask.domain.spirit.entity.enums.WhiskyCaskType;
import com.caskbycask.domain.spirit.entity.enums.WhiskyStyle;
import com.caskbycask.domain.spirit.entity.enums.WineType;
import com.caskbycask.domain.spirit.entity.enums.CognacGrade;
import com.caskbycask.domain.spirit.entity.enums.OtherSpiritType;
import com.caskbycask.domain.spirit.entity.enums.VariantType;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

public record SpiritRegisterRequestDetailResponse(
        Long id,
        Long requesterId,
        String requesterNickname,
        String nameKo,
        String nameEn,
        SpiritCategory category,
        Long producerId,
        String producerNameKo,
        String bottler,
        Integer bottledYear,
        Integer vintageYear,
        BigDecimal abv,
        Integer volumeMl,
        BigDecimal abvMin,
        BigDecimal abvMax,
        Integer volumeMlMin,
        Integer volumeMlMax,
        String country,
        String region,
        Integer ageStatement,
        Integer ageStatementMonths,
        Integer ageStatementMin,
        Integer ageStatementMinMonths,
        Integer ageStatementMax,
        Integer ageStatementMaxMonths,
        Boolean isNas,
        String distilledDate,
        String bottledDate,
        LocalDate releaseDate,
        String bottleNo,
        String batchNo,
        Integer totalBottles,
        WhiskyStyle whiskyStyle,
        String whiskyStyleOther,
        String brandName,
        String bottlingType,
        String caskNo,
        String whiskyNotes,
        List<WhiskyCaskType> caskTypes,
        List<WhiskyCaskType> caskFinishes,
        String caskTypeOther,
        Map<WhiskyCaskType, List<String>> caskDetails,
        Boolean isNonChillFiltered,
        Boolean isNaturalColour,
        Boolean isSingleCask,
        Boolean isCaskStrength,
        Boolean isPeated,
        Integer phenolPpm,
        Integer phenolPpmMin,
        Integer phenolPpmMax,
        WineType wineType,
        CognacGrade cognacGrade,
        OtherSpiritType otherType,
        WineDetailRequest wineDetail,
        CognacDetailRequest cognacDetail,
        OtherDetailRequest otherDetail,
        List<String> imageUrls,
        String note,
        VariantType variantType,
        String variantValue,
        String variantValueEn,
        RequestStatus status,
        String rejectReason,
        LocalDateTime createdAt,
        LocalDateTime reviewedAt
) {
    public static SpiritRegisterRequestDetailResponse of(
            SpiritRegisterRequest req,
            SpiritRegisterRequestBody body,
            String producerNameKo) {
        return new SpiritRegisterRequestDetailResponse(
                req.getId(),
                req.getUser().getId(),
                req.getUser().getNickname(),
                body.nameKo(),
                body.nameEn(),
                body.category(),
                body.producerId(),
                producerNameKo,
                body.bottler(),
                body.bottledYear(),
                body.vintageYear(),
                body.abv(),
                body.volumeMl(),
                body.abvMin(),
                body.abvMax(),
                body.volumeMlMin(),
                body.volumeMlMax(),
                body.country(),
                body.region(),
                body.ageStatement(),
                body.ageStatementMonths(),
                body.ageStatementMin(),
                body.ageStatementMinMonths(),
                body.ageStatementMax(),
                body.ageStatementMaxMonths(),
                body.isNas(),
                body.distilledDate(),
                body.bottledDate(),
                body.releaseDate(),
                body.bottleNo(),
                body.batchNo(),
                body.totalBottles(),
                body.whiskyStyle(),
                body.whiskyStyleOther(),
                body.brandName(),
                body.bottlingType(),
                body.caskNo(),
                body.whiskyNotes(),
                body.caskTypes() != null ? body.caskTypes() : List.of(),
                body.caskFinishes() != null ? body.caskFinishes() : List.of(),
                body.caskTypeOther(),
                body.caskDetails() != null ? body.caskDetails() : Map.of(),
                body.isNonChillFiltered(),
                body.isNaturalColour(),
                body.isSingleCask(),
                body.isCaskStrength(),
                body.isPeated(),
                body.phenolPpm(),
                body.phenolPpmMin(),
                body.phenolPpmMax(),
                body.wineType(),
                body.cognacGrade(),
                body.otherType(),
                body.wineDetail(),
                body.cognacDetail(),
                body.otherDetail(),
                body.imageUrls() != null ? body.imageUrls() : List.of(),
                body.note(),
                body.variantType(),
                body.variantValue(),
                body.variantValueEn(),
                req.getStatus(),
                req.getRejectReason(),
                req.getCreatedAt(),
                req.getReviewedAt()
        );
    }
}
