-- 대한민국 소주 제조사 생산자 시드 (2026-09-01 조사 기준)
-- 엑셀의 '등록용_확정' 65개사만 적재한다. 검토 필요 후보와 제외 대상은 포함하지 않는다.
-- 소개문에는 조사 날짜·출처 확인 문구를 넣지 않고 제조사의 연혁·제품·원료·생산 특징만 담았다.
-- 이미 같은 한국어명 또는 영문명으로 등록된 생산자는 관리자 수정 내용을 보존하기 위해 건너뛴다.

CREATE TEMPORARY TABLE tmp_korean_soju_producer_seed (
    name_ko VARCHAR(200) NOT NULL,
    name_en VARCHAR(200) NOT NULL,
    country VARCHAR(100) NOT NULL,
    region VARCHAR(100),
    region_code VARCHAR(40),
    website VARCHAR(500),
    founded_year INTEGER,
    description_ko TEXT,
    description_en TEXT,
    search_keywords VARCHAR(300)
);

INSERT INTO tmp_korean_soju_producer_seed
    (name_ko, name_en, country, region, region_code, website, founded_year,
     description_ko, description_en, search_keywords)
VALUES
    ('하이트진로㈜', 'HiteJinro Co., Ltd.', '대한민국', NULL, NULL, 'https://www.hitejinro.com/', 1924, '하이트진로㈜(HiteJinro Co., Ltd.)는 1924년 진천양조상회에서 출발한 대한민국의 종합 주류 기업입니다. 참이슬과 진로를 중심으로 대중적인 희석식 소주를 전개하고, 일품진로를 통해 증류식 소주 제품군도 운영합니다. 소주와 맥주를 함께 다루는 폭넓은 포트폴리오와 전국 단위 생산·유통 기반이 특징입니다.', 'HiteJinro Co., Ltd. is a Korean drinks company whose history begins with Jincheon Brewery in 1924. Its soju portfolio combines mainstream diluted brands such as Chamisul and Jinro with distilled expressions led by Ilpoom Jinro. A nationwide production and distribution base, together with a broad portfolio spanning both soju and beer, defines the company’s scale and identity.', '하이트진로, 진로, 참이슬, 일품진로, 하이트진로㈜, HiteJinro Co., Ltd.'),
    ('롯데칠성음료㈜', 'LOTTE Chilsung Beverage Co., Ltd.', '대한민국', NULL, NULL, 'https://company.lottechilsung.co.kr/', 1950, '롯데칠성음료㈜(LOTTE Chilsung Beverage Co., Ltd.)는 1950년 설립된 음료·주류 기업입니다. 처음처럼과 새로를 중심으로 희석식 소주를 전개하며, 대장부 등 증류식 소주 제품도 함께 다룹니다. 음료 사업에서 축적한 전국 유통망과 다양한 주류 카테고리를 결합한 종합 포트폴리오가 특징입니다.', 'LOTTE Chilsung Beverage Co., Ltd. is a Korean beverage and alcoholic-drinks company founded in 1950. Its soju range is led by diluted brands such as Chum Churum and Saero, alongside distilled products including Daejangbu. The company is distinguished by a nationwide distribution network and a broad portfolio that combines soft drinks with several alcoholic-drinks categories.', '롯데주류, 처음처럼, 새로, 대장부, 여울, 롯데칠성음료㈜, LOTTE Chilsung Beverage Co., Ltd.'),
    ('㈜무학', 'Muhak Co., Ltd.', '대한민국', '경상남도', 'KR_GYEONGNAM', 'https://www.muhak.co.kr/', 1929, '㈜무학(Muhak Co., Ltd.)은 1929년부터 이어진 경상남도 기반의 주류 기업입니다. 좋은데이와 화이트를 중심으로 희석식 소주를 생산하며, 부산·울산·경남을 비롯한 영남권에서 오랫동안 지역 브랜드 정체성을 쌓아 왔습니다. 부드러운 음용성을 지향하는 저도 소주 제품군을 지속적으로 발전시킨 점이 특징입니다.', 'Muhak Co., Ltd. is a Gyeongsangnam-do-based drinks company with a history dating to 1929. It produces diluted soju led by Good Day and White and has built a long-standing regional identity across southeastern Korea. Its portfolio is particularly associated with lower-strength soju designed for a softer drinking style.', '무학, 좋은데이, 화이트, ㈜무학, Muhak Co., Ltd.'),
    ('대선주조㈜', 'Daesun Distilling Co., Ltd.', '대한민국', '부산', 'KR_BUSAN', 'https://www.c1.co.kr/', 1930, '대선주조㈜(Daesun Distilling Co., Ltd.)은 1930년 설립된 부산 기반의 소주 제조사입니다. 대선과 C1을 중심으로 희석식 소주를 생산하고, 부산 지역의 식문화와 유통망에 밀착한 브랜드 운영을 이어 왔습니다. 지역 대표 소주와 계절·향미형 파생 제품을 함께 전개하는 구성이 특징입니다.', 'Daesun Distilling Co., Ltd. is a Busan-based soju producer founded in 1930. Its diluted-soju portfolio is led by Daesun and C1, supported by a brand and distribution presence closely tied to Busan’s local drinking culture. The range combines its core regional labels with seasonal and flavour-led extensions.', '대선주조, 대선159, 대선소주, C1, 시원소주, 대선주조㈜, Daesun Distilling Co., Ltd., 대선, 대선 샤인머스캣'),
    ('보해양조㈜', 'Bohae Brewery Co., Ltd.', '대한민국', '전라남도', 'KR_JEONNAM', 'https://www.bohae.co.kr/', 1950, '보해양조㈜(Bohae Brewery Co., Ltd.)은 1950년 설립된 전라남도 기반의 주류 기업입니다. 잎새주와 보해골드를 중심으로 희석식 소주를 생산하며, 광주·전남을 중심으로 형성된 지역 브랜드 기반을 갖고 있습니다. 소주뿐 아니라 과실주와 전통주까지 폭넓게 다루는 종합 양조 역량이 특징입니다.', 'Bohae Brewery Co., Ltd. is a Jeollanam-do-based drinks producer founded in 1950. Its diluted-soju range is led by Ipseju and Bohae Gold, supported by a strong regional base in Gwangju and Jeollanam-do. The company’s production capability extends beyond soju to fruit wines and traditional Korean alcoholic drinks.', '보해양조, 잎새주, 보해골드, 보해양조㈜, Bohae Brewery Co., Ltd.'),
    ('㈜금복주', 'Kumbokju Co., Ltd.', '대한민국', '대구', 'KR_DAEGU', 'https://www.kumbokju.co.kr/', 1957, '㈜금복주(Kumbokju Co., Ltd.)는 1957년 설립된 대구 기반의 주류 기업입니다. 참소주와 제로투 같은 희석식 소주를 중심으로 대구·경북 지역의 대표 브랜드를 운영하며, 제왕 안동소주를 통해 증류식 소주도 함께 전개합니다. 지역 대중주와 전통 증류주를 한 포트폴리오에서 다루는 점이 특징입니다.', 'Kumbokju Co., Ltd. is a Daegu-based drinks company founded in 1957. It operates major diluted-soju brands in Daegu and Gyeongsangbuk-do, including Cham Soju and Zero2, while also producing distilled soju through the Jewang Andong Soju range. Its portfolio links a strong regional mainstream business with traditional distilled expressions.', '금복주, 참소주, 맛있는참, 제로투, 제왕, ㈜금복주, Kumbokju Co., Ltd., 제왕 안동소주'),
    ('㈜선양소주', 'Sunyang Soju Co., Ltd.', '대한민국', '대전', 'KR_DAEJEON', 'https://www.mackisscompany.co.kr/', 1973, '㈜선양소주(Sunyang Soju Co., Ltd.)는 1973년 선양주조에서 출발한 대전·충청권 기반의 소주 제조사입니다. 선양과 선양린을 중심으로 희석식 소주를 생산하고, 사락 GOLD 같은 증류식 소주도 함께 선보입니다. 지역 밀착형 대중 소주와 프리미엄 증류 제품을 병행하는 구성이 특징입니다.', 'Sunyang Soju Co., Ltd. traces its history to Sunyang Brewery, established in 1973, and is rooted in Daejeon and the Chungcheong region. Its range combines diluted soju led by Sunyang and Sunyang Linn with distilled expressions such as S-arak GOLD. The company’s identity joins a locally focused mainstream business with a smaller premium distilled portfolio.', '맥키스컴퍼니, 선양소주, 선양, 선양린, O2린, 사락, ㈜선양소주, Sunyang Soju Co., Ltd., 사락 GOLD'),
    ('㈜충북소주', 'Chungbuk Soju Co., Ltd.', '대한민국', '충청북도', 'KR_CHUNGBUK', 'http://www.cbsoju.com/', 1957, '㈜충북소주(Chungbuk Soju Co., Ltd.)는 충청북도를 기반으로 시원한 청풍과 맑은바람을 생산하는 희석식 소주 제조사입니다. 1957년부터 이어진 지역 소주의 계보를 바탕으로 충북 지역의 유통과 소비 문화에 밀착한 제품을 운영해 왔습니다. 지역명과 청정 이미지를 전면에 둔 브랜드 정체성이 특징입니다.', 'Chungbuk Soju Co., Ltd. is a diluted-soju producer based in Chungcheongbuk-do, with Cool Cheongpung and Malgeun Baram as its core brands. Drawing on a regional soju lineage that dates to 1957, it has developed products closely tied to local distribution and drinking culture. Its brand identity places strong emphasis on Chungcheongbuk-do and a clean, fresh image.', '충북소주, 시원한청풍, 시원한 청풍, 맑은바람, ㈜충북소주, Chungbuk Soju Co., Ltd.'),
    ('㈜한라산', 'Hallasan Co., Ltd.', '대한민국', '제주도', 'KR_JEJU', 'https://www.hallasan.co.kr/', 1950, '㈜한라산(Hallasan Co., Ltd.)은 1950년 호남양조장에서 출발한 제주도의 소주 제조사입니다. 한라산과 한라산 순한을 중심으로 희석식 소주를 생산하며, 제주 화산암반수와 제주 현지 생산을 브랜드 정체성의 핵심으로 삼고 있습니다. 섬 지역의 독립적인 생산 기반과 지역 대표성이 특징입니다.', 'Hallasan Co., Ltd. is a Jeju-do soju producer whose history begins with Honam Brewery in 1950. Its diluted-soju portfolio is led by Hallasan and Hallasan Mild, with Jeju volcanic bedrock water and local production forming central parts of the brand identity. An independent island production base and strong regional representation distinguish the company.', '한라산소주, 한라산21, 한라산17, 한라산순한, ㈜한라산, Hallasan Co., Ltd., 한라산, 한라산 순한'),
    ('㈜배혜정농업회사법인', 'Bae Hye Jeong Agricultural Corporation', '대한민국', '경기도', 'KR_GYEONGGI', 'http://www.baedoga.co.kr/', NULL, '㈜배혜정농업회사법인(Bae Hye Jeong Agricultural Corporation)은 대한민국 경기도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 로아 포르토·우곡소주·로아19화이트·로아19옐로우·로아19레드·로아40화이트·로아40퍼플 등이 포함됩니다. 제품 원료에는 쌀 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '㈜배혜정농업회사법인 (Bae Hye Jeong Agricultural Corporation) is a distilled soju producer based in Gyeonggi-do, South Korea. Its core range includes 로아 포르토, 우곡소주, 로아19화이트, 로아19옐로우, 로아19레드, 로아40화이트, 로아40퍼플. The range uses ingredients such as rice. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '배혜정도가, (주)배혜정농업회사법인, ㈜배혜정농업회사법인, Bae Hye Jeong Agricultural Corporation, 로아 포르토, 우곡소주, 로아19화이트, 로아19옐로우, 로아19레드, 로아40화이트, 로아40퍼플'),
    ('㈜백제명가주조', 'Baekjemyeonggajujo Brewery', '대한민국', '충청남도', 'KR_CHUNGNAM', 'https://smartstore.naver.com/baekje2012', NULL, '㈜백제명가주조(Baekjemyeonggajujo Brewery)은 대한민국 충청남도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 백제한산군주 등이 포함됩니다. 제품 원료에는 쌀 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '㈜백제명가주조 (Baekjemyeonggajujo Brewery) is a distilled soju producer based in Chungcheongnam-do, South Korea. Its core range includes 백제한산군주. The range uses ingredients such as rice. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '㈜백제명가주조, Baekjemyeonggajujo Brewery, 백제한산군주'),
    ('㈜우보주책', 'Ubojuchaek Brewery', '대한민국', '경기도', 'KR_GYEONGGI', 'https://woobojoocheck.com/', NULL, '㈜우보주책(Ubojuchaek Brewery)은 대한민국 경기도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 양평 밀 소주 등이 포함됩니다. 제품 원료에는 밀 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '㈜우보주책 (Ubojuchaek Brewery) is a distilled soju producer based in Gyeonggi-do, South Korea. Its core range includes 양평 밀 소주. The range uses ingredients such as wheat. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '㈜우보주책, Ubojuchaek Brewery, 양평 밀 소주'),
    ('㈜좋은술', 'Joeunsul Co., Ltd.', '대한민국', '경기도', 'KR_GYEONGGI', 'http://jsul.modoo.at/', NULL, '㈜좋은술(Joeunsul Co., Ltd.)은 대한민국 경기도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 천비향 화주 등이 포함됩니다. 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '㈜좋은술 (Joeunsul Co., Ltd.) is a distilled soju producer based in Gyeonggi-do, South Korea. Its core range includes 천비향 화주. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '좋은술, 천비향 화주, 천비향, ㈜좋은술, Joeunsul Co., Ltd.'),
    ('㈜화요', 'Hwayo Co., Ltd.', '대한민국', '경기도', 'KR_GYEONGGI', 'https://www.hwayo.com/', NULL, '㈜화요(Hwayo Co., Ltd.)은 대한민국 경기도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 화요 41%, 25%, 17%·화요53·화요41·화요25·화요 X.Premium·화요17 등이 포함됩니다. 제품 원료에는 쌀 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '㈜화요 (Hwayo Co., Ltd.) is a distilled soju producer based in Gyeonggi-do, South Korea. Its core range includes 화요 41%, 25%, 17%, 화요53, 화요41, 화요25, 화요 X.Premium, 화요17. The range uses ingredients such as rice. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '㈜화요, (주)화요, Hwayo Co., Ltd., 화요 41%, 25%, 17%, 화요53, 화요41, 화요25, 화요 X.Premium, 화요17'),
    ('국가유산·명인 조옥화 안동소주', 'Cho Ok-hwa Andong Soju', '대한민국', '경상북도', 'KR_GYEONGBUK', 'https://www.andongsoju.com/', NULL, '국가유산·명인 조옥화 안동소주(Cho Ok-hwa Andong Soju)은 대한민국 경상북도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 국가유산·명인 조옥화 안동소주 45도 등이 포함됩니다. 제품 원료에는 쌀·누룩·국 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '국가유산·명인 조옥화 안동소주 (Cho Ok-hwa Andong Soju) is a distilled soju producer based in Gyeongsangbuk-do, South Korea. Its core range includes 국가유산·명인 조옥화 안동소주 45도. The range uses ingredients such as rice, nuruk or koji. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '국가유산·명인 조옥화 안동소주, Cho Ok-hwa Andong Soju, 국가유산·명인 조옥화 안동소주 45도'),
    ('국순당 횡성양조장', 'Kooksoondang Hoengseong Brewery', '대한민국', '강원도', 'KR_GANGWON', 'http://drink.ksdb.co.kr/', NULL, '국순당 횡성양조장(Kooksoondang Hoengseong Brewery)은 대한민국 강원도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 려·려 2013 본 등이 포함됩니다. 제품 원료에는 쌀·고구마 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '국순당 횡성양조장 (Kooksoondang Hoengseong Brewery) is a distilled soju producer based in Gangwon-do, South Korea. Its core range includes 려, 려 2013 본. The range uses ingredients such as rice, sweet potato. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '국순당 횡성양조장, Kooksoondang Hoengseong Brewery, 려, 려 2013 본'),
    ('국순당여주명주㈜', 'Kooksoondang Yeoju Myungju Co., Ltd.', '대한민국', '경기도', 'KR_GYEONGGI', 'http://www.ksdyeoju.com/', NULL, '국순당여주명주㈜(Kooksoondang Yeoju Myungju Co., Ltd.)은 대한민국 경기도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 려 고구마 소주·려40 등이 포함됩니다. 제품 원료에는 쌀·고구마 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '국순당여주명주㈜ (Kooksoondang Yeoju Myungju Co., Ltd.) is a distilled soju producer based in Gyeonggi-do, South Korea. Its core range includes 려 고구마 소주, 려40. The range uses ingredients such as rice, sweet potato. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '국순당여주명주, 국순당여주명주(주), 국순당여주명주㈜, Kooksoondang Yeoju Myungju Co., Ltd., 려 고구마 소주, 려40'),
    ('남한산성소주', 'Namhansanseongsoju Brewery', '대한민국', '경기도', 'KR_GYEONGGI', 'http://www.sansungsoju.com/', NULL, '남한산성소주(Namhansanseongsoju Brewery)은 대한민국 경기도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 남한산성소주·남한산성소주 21 등이 포함됩니다. 제품 원료에는 쌀·보리·누룩·국 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '남한산성소주 (Namhansanseongsoju Brewery) is a distilled soju producer based in Gyeonggi-do, South Korea. Its core range includes 남한산성소주, 남한산성소주 21. The range uses ingredients such as rice, barley, nuruk or koji. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '남한산성소주, Namhansanseongsoju Brewery, 남한산성소주 21'),
    ('내변산', 'Naebyeonsan Brewery', '대한민국', '전라북도', 'KR_JEONBUK', 'https://smartstore.naver.com/odwine/products/6140247908', NULL, '내변산(Naebyeonsan Brewery)은 대한민국 전라북도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 백제소주 등이 포함됩니다. 제품 원료에는 쌀 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '내변산 (Naebyeonsan Brewery) is a distilled soju producer based in Jeollabuk-do, South Korea. Its core range includes 백제소주. The range uses ingredients such as rice. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '내변산, Naebyeonsan Brewery, 백제소주'),
    ('내외 디스틸러리', 'Naeoe Distillery', '대한민국', NULL, NULL, NULL, NULL, '내외 디스틸러리(Naeoe Distillery)은 대한민국에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 내외39 등이 포함됩니다. 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '내외 디스틸러리 (Naeoe Distillery) is a distilled soju producer operating in South Korea. Its core range includes 내외39. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '내외39, 내외 디스틸러리, Naeoe Distillery'),
    ('농업회사법인 (유) 양촌양조', 'Yangchonyangjo Brewery', '대한민국', '충청남도', 'KR_CHUNGNAM', 'http://www.yangchon.co.kr/', NULL, '농업회사법인 (유) 양촌양조(Yangchonyangjo Brewery)은 대한민국 충청남도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 여유40 등이 포함됩니다. 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '농업회사법인 (유) 양촌양조 (Yangchonyangjo Brewery) is a distilled soju producer based in Chungcheongnam-do, South Korea. Its core range includes 여유40. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '농업회사법인 (유)양촌양조, 농업회사법인 (유) 양촌양조, Yangchonyangjo Brewery, 여유40'),
    ('농업회사법인 (유) 화양', 'Hwayang Agricultural Corporation', '대한민국', '충청북도', 'KR_CHUNGBUK', NULL, NULL, '농업회사법인 (유) 화양(Hwayang Agricultural Corporation)은 대한민국 충청북도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 풍정사계 동 등이 포함됩니다. 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '농업회사법인 (유) 화양 (Hwayang Agricultural Corporation) is a distilled soju producer based in Chungcheongbuk-do, South Korea. Its core range includes 풍정사계 동. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '화양, 풍정사계 동, 풍정사계, 농업회사법인 (유) 화양, Hwayang Agricultural Corporation'),
    ('농업회사법인 ㈜달홀주조', 'Dalholjujo Brewery', '대한민국', '강원도', 'KR_GANGWON', 'http://dalholju.com/', NULL, '농업회사법인 ㈜달홀주조(Dalholjujo Brewery)은 대한민국 강원도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 달홀진주25·달홀진주 등이 포함됩니다. 제품 원료에는 쌀 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '농업회사법인 ㈜달홀주조 (Dalholjujo Brewery) is a distilled soju producer based in Gangwon-do, South Korea. Its core range includes 달홀진주25, 달홀진주. The range uses ingredients such as rice. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '농업회사법인 달홀주조, 농업회사법인(주)달홀주조, 농업회사법인 ㈜달홀주조, Dalholjujo Brewery, 달홀진주25, 달홀진주'),
    ('농업회사법인 ㈜온증류소', 'Distillery On Co., Ltd.', '대한민국', '경기도', 'KR_GYEONGGI', 'https://smartstore.naver.com/distilleryon', NULL, '농업회사법인 ㈜온증류소(Distillery On Co., Ltd.)은 대한민국 경기도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 형형 25·연연 25·형형40 등이 포함됩니다. 제품 원료에는 쌀 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '농업회사법인 ㈜온증류소 (Distillery On Co., Ltd.) is a distilled soju producer based in Gyeonggi-do, South Korea. Its core range includes 형형 25, 연연 25, 형형40. The range uses ingredients such as rice. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '온 증류소, 농업회사법인 (주)온증류소, 농업회사법인 ㈜온증류소, Distillery On Co., Ltd., 형형 25, 연연 25, 형형40'),
    ('농업회사법인 담을', 'Dameul Brewery', '대한민국', '충청북도', 'KR_CHUNGBUK', 'https://smartstore.naver.com/dameul_service', NULL, '농업회사법인 담을(Dameul Brewery)은 대한민국 충청북도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 주향소주 25·주향담을·주향이오·주향아라·주향아라 스페셜·이음주 등이 포함됩니다. 제품 원료에는 쌀 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '농업회사법인 담을 (Dameul Brewery) is a distilled soju producer based in Chungcheongbuk-do, South Korea. Its core range includes 주향소주 25, 주향담을, 주향이오, 주향아라, 주향아라 스페셜, 이음주. The range uses ingredients such as rice. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '담을, 농업회사법인 담을, 농업회사법인담을, Dameul Brewery, 주향소주 25, 주향담을, 주향이오, 주향아라, 주향아라 스페셜, 이음주'),
    ('농업회사법인 아리랑주조㈜', 'Arirangjujo Brewery', '대한민국', '충청남도', 'KR_CHUNGNAM', 'https://smartstore.naver.com/arirangjujo/products/4985769134', NULL, '농업회사법인 아리랑주조㈜(Arirangjujo Brewery)은 대한민국 충청남도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 겨울소주 25·겨울소주45 등이 포함됩니다. 제품 원료에는 쌀 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '농업회사법인 아리랑주조㈜ (Arirangjujo Brewery) is a distilled soju producer based in Chungcheongnam-do, South Korea. Its core range includes 겨울소주 25, 겨울소주45. The range uses ingredients such as rice. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '두이술공방, 농업회사법인 아리랑주조㈜, Arirangjujo Brewery, 겨울소주 25, 겨울소주45'),
    ('농업회사법인 연천양조㈜', 'Yeoncheonyangjo Brewery', '대한민국', '경기도', 'KR_GYEONGGI', 'https://ksool88.modoo.at/', NULL, '농업회사법인 연천양조㈜(Yeoncheonyangjo Brewery)은 대한민국 경기도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 연천 우주·연천우주 38 등이 포함됩니다. 제품 원료에는 쌀·누룩·국 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '농업회사법인 연천양조㈜ (Yeoncheonyangjo Brewery) is a distilled soju producer based in Gyeonggi-do, South Korea. Its core range includes 연천 우주, 연천우주 38. The range uses ingredients such as rice, nuruk or koji. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '농업회사법인 연천양조(주), 연천양조, 농업회사법인 연천양조㈜, Yeoncheonyangjo Brewery, 연천 우주, 연천우주 38'),
    ('농업회사법인 이가수불㈜', 'Igasubul Brewery', '대한민국', '충청남도', 'KR_CHUNGNAM', 'https://smartstore.naver.com/leegasubul', NULL, '농업회사법인 이가수불㈜(Igasubul Brewery)은 대한민국 충청남도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 이상헌 소주 등이 포함됩니다. 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '농업회사법인 이가수불㈜ (Igasubul Brewery) is a distilled soju producer based in Chungcheongnam-do, South Korea. Its core range includes 이상헌 소주. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '농업회사법인 이가수불㈜, Igasubul Brewery, 이상헌 소주'),
    ('농업회사법인 주식회사 다농바이오', 'Danongbaio Brewery', '대한민국', '충청북도', 'KR_CHUNGBUK', 'https://danongbio.kr/', NULL, '농업회사법인 주식회사 다농바이오(Danongbaio Brewery)은 대한민국 충청북도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 가무치 25도 등이 포함됩니다. 제품 원료에는 쌀 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '농업회사법인 주식회사 다농바이오 (Danongbaio Brewery) is a distilled soju producer based in Chungcheongbuk-do, South Korea. Its core range includes 가무치 25도. The range uses ingredients such as rice. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '농업회사법인 주식회사 다농바이오, Danongbaio Brewery, 가무치 25도'),
    ('농업회사법인 주식회사 주연향', 'Juyeonhyang Brewery', '대한민국', '인천', 'KR_INCHEON', 'https://smartstore.naver.com/juyeonhyang', NULL, '농업회사법인 주식회사 주연향(Juyeonhyang Brewery)은 대한민국 인천에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 야수 S 53 등이 포함됩니다. 제품 원료에는 쌀·고구마 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '농업회사법인 주식회사 주연향 (Juyeonhyang Brewery) is a distilled soju producer based in Incheon, South Korea. Its core range includes 야수 S 53. The range uses ingredients such as rice, sweet potato. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '농업회사법인 주식회사 주연향, Juyeonhyang Brewery, 야수 S 53'),
    ('농업회사법인 토끼소주㈜', 'Tokki Soju Co., Ltd.', '대한민국', '충청북도', 'KR_CHUNGBUK', 'https://tokkisoju.com/', NULL, '농업회사법인 토끼소주㈜(Tokki Soju Co., Ltd.)은 대한민국 충청북도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 토끼소주 블랙·선비 보드카 등이 포함됩니다. 제품 원료에는 쌀·누룩·국 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '농업회사법인 토끼소주㈜ (Tokki Soju Co., Ltd.) is a distilled soju producer based in Chungcheongbuk-do, South Korea. Its core range includes 토끼소주 블랙, 선비 보드카. The range uses ingredients such as rice, nuruk or koji. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '농업회사법인 토끼소주 (주), 농업회사법인 토끼소주, 농업회사법인 토끼소주㈜, Tokki Soju Co., Ltd., 토끼소주 블랙, 선비 보드카'),
    ('대작영농조합법인', 'Daejak Brewery', '대한민국', '강원도', 'KR_GANGWON', 'https://blog.naver.com/daejak_ricewine', NULL, '대작영농조합법인(Daejak Brewery)은 대한민국 강원도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 모을동주 소주·모을동주소주 등이 포함됩니다. 제품 원료에는 쌀·밀 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '대작영농조합법인 (Daejak Brewery) is a distilled soju producer based in Gangwon-do, South Korea. Its core range includes 모을동주 소주, 모을동주소주. The range uses ingredients such as rice, wheat. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '대작영농조합법인, Daejak Brewery, 모을동주 소주, 모을동주소주'),
    ('맹개술도가', 'Maenggaesuldoga Brewery', '대한민국', '경상북도', 'KR_GYEONGBUK', 'https://3d.co.kr/mgsdg/', NULL, '맹개술도가(Maenggaesuldoga Brewery)은 대한민국 경상북도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 안동 진맥 소주 등이 포함됩니다. 제품 원료에는 밀 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '맹개술도가 (Maenggaesuldoga Brewery) is a distilled soju producer based in Gyeongsangbuk-do, South Korea. Its core range includes 안동 진맥 소주. The range uses ingredients such as wheat. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '맹개술도가, Maenggaesuldoga Brewery, 안동 진맥 소주'),
    ('명인안동소주', 'Master Andong Soju', '대한민국', '경상북도', 'KR_GYEONGBUK', 'http://www.adsoju.com/', NULL, '명인안동소주(Master Andong Soju)은 대한민국 경상북도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 명인 안동소주 양반탈·명인 안동소주 22%·명인안동소주 35%·명인안동소주/22도·명인안동소주/45도 등이 포함됩니다. 제품 원료에는 쌀·누룩·국 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '명인안동소주 (Master Andong Soju) is a distilled soju producer based in Gyeongsangbuk-do, South Korea. Its core range includes 명인 안동소주 양반탈, 명인 안동소주 22%, 명인안동소주 35%, 명인안동소주/22도, 명인안동소주/45도. The range uses ingredients such as rice, nuruk or koji. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '명인안동소주, Master Andong Soju, 명인 안동소주 양반탈, 명인 안동소주 22%, 명인안동소주 35%, 명인안동소주/22도, 명인안동소주/45도'),
    ('문배주양조원', 'Moonbaesool Brewery', '대한민국', '경기도', 'KR_GYEONGGI', 'https://www.moonbaesool.co.kr/', NULL, '문배주양조원(Moonbaesool Brewery)은 대한민국 경기도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 문배주 용상·문배술·문배술 헤리티지 40도·문배술 천향·문배술 명작·문배술 용상·문배술 호리병 등이 포함됩니다. 제품 원료에는 쌀 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '문배주양조원 (Moonbaesool Brewery) is a distilled soju producer based in Gyeonggi-do, South Korea. Its core range includes 문배주 용상, 문배술, 문배술 헤리티지 40도, 문배술 천향, 문배술 명작, 문배술 용상, 문배술 호리병. The range uses ingredients such as rice. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '문배주양조원, Moonbaesool Brewery, 문배주 용상, 문배술, 문배술 헤리티지 40도, 문배술 천향, 문배술 명작, 문배술 용상, 문배술 호리병'),
    ('미음넷증류소', 'Fourmieum Distillery', '대한민국', '경기도', 'KR_GYEONGGI', 'https://smartstore.naver.com/fourmieum', NULL, '미음넷증류소(Fourmieum Distillery)은 대한민국 경기도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 소주다움 45·소주다움27 등이 포함됩니다. 제품 원료에는 쌀 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '미음넷증류소 (Fourmieum Distillery) is a distilled soju producer based in Gyeonggi-do, South Korea. Its core range includes 소주다움 45, 소주다움27. The range uses ingredients such as rice. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '미음넷증류소, Fourmieum Distillery, 소주다움 45, 소주다움27'),
    ('밀과노닐다', 'Milgwanonilda Brewery', '대한민국', '경상북도', 'KR_GYEONGBUK', 'https://www.jinmaek.co/', NULL, '밀과노닐다(Milgwanonilda Brewery)은 대한민국 경상북도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 진맥소주 오크40%·시인의 바위·진맥소주 시인의바위·진맥소주 등이 포함됩니다. 제품 원료에는 밀 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '밀과노닐다 (Milgwanonilda Brewery) is a distilled soju producer based in Gyeongsangbuk-do, South Korea. Its core range includes 진맥소주 오크40%, 시인의 바위, 진맥소주 시인의바위, 진맥소주. The range uses ingredients such as wheat. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '밀과노닐다, Milgwanonilda Brewery, 진맥소주 오크40%, 시인의 바위, 진맥소주 시인의바위, 진맥소주'),
    ('밝은세상영농조합', 'Balkeunsesangyeongnongjohap Brewery', '대한민국', '경기도', 'KR_GYEONGGI', 'https://www.instagram.com/tigercalyx/?hl=ko', NULL, '밝은세상영농조합(Balkeunsesangyeongnongjohap Brewery)은 대한민국 경기도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 소호 등이 포함됩니다. 제품 원료에는 쌀·누룩·국 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '밝은세상영농조합 (Balkeunsesangyeongnongjohap Brewery) is a distilled soju producer based in Gyeonggi-do, South Korea. Its core range includes 소호. The range uses ingredients such as rice, nuruk or koji. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '밝은세상영농조합, Balkeunsesangyeongnongjohap Brewery, 소호'),
    ('배상면주가', 'Baesangmyeonjuga Brewery', '대한민국', '경기도', 'KR_GYEONGGI', 'https://www.soolsool.co.kr/', NULL, '배상면주가(Baesangmyeonjuga Brewery)은 대한민국 경기도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 느린마을소주21·감아락 25 등이 포함됩니다. 제품 원료에는 쌀 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '배상면주가 (Baesangmyeonjuga Brewery) is a distilled soju producer based in Gyeonggi-do, South Korea. Its core range includes 느린마을소주21, 감아락 25. The range uses ingredients such as rice. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '배상면주가, Baesangmyeonjuga Brewery, 느린마을소주21, 감아락 25'),
    ('병영양조장', 'Byeongyeongyangjojang Brewery', '대한민국', '전라남도', 'KR_JEONNAM', 'http://www.byjujo.co.kr/', NULL, '병영양조장(Byeongyeongyangjojang Brewery)은 대한민국 전라남도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 병영소주 등이 포함됩니다. 제품 원료에는 보리 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '병영양조장 (Byeongyeongyangjojang Brewery) is a distilled soju producer based in Jeollanam-do, South Korea. Its core range includes 병영소주. The range uses ingredients such as barley. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '병영양조장, Byeongyeongyangjojang Brewery, 병영소주'),
    ('술도가제주바당', 'Suldogajejubadang Brewery', '대한민국', '제주도', 'KR_JEJU', 'https://jejudoga.modoo.at/', NULL, '술도가제주바당(Suldogajejubadang Brewery)은 대한민국 제주도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 제주낭만 등이 포함됩니다. 제품 원료에는 쌀 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '술도가제주바당 (Suldogajejubadang Brewery) is a distilled soju producer based in Jeju-do, South Korea. Its core range includes 제주낭만. The range uses ingredients such as rice. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '술도가제주바당, Suldogajejubadang Brewery, 제주낭만'),
    ('술샘', 'Soolseam', '대한민국', '경기도', 'KR_GYEONGGI', 'http://www.sulseam.com/', 2012, '술샘(Soolseam)은 대한민국 경기도에 기반을 둔 증류식 소주 제조사입니다. 2012년부터 이어진 연혁을 바탕으로 대표 제품군에는 미르·미르25·미르54 등이 포함됩니다. 제품 원료에는 쌀·밀·누룩·국 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '술샘 (Soolseam) is a distilled soju producer based in Gyeonggi-do, South Korea. Its history dates to 2012. Its core range includes 미르, 미르25, 미르54. The range uses ingredients such as rice, wheat, nuruk or koji. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '술샘, (주)술샘, Soolseam, 미르, 미르25, 미르54'),
    ('안동소주일품', 'Ilpoom Andong Soju', '대한민국', '경상북도', 'KR_GYEONGBUK', 'http://www.ilpoomsoju.com/', NULL, '안동소주일품(Ilpoom Andong Soju)은 대한민국 경상북도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 안동소주 일품 17도·안동소주 일품 21도 등이 포함됩니다. 제품 원료에는 쌀 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '안동소주일품 (Ilpoom Andong Soju) is a distilled soju producer based in Gyeongsangbuk-do, South Korea. Its core range includes 안동소주 일품 17도, 안동소주 일품 21도. The range uses ingredients such as rice. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '안동소주일품, Ilpoom Andong Soju, 안동소주 일품 17도, 안동소주 일품 21도'),
    ('안동전통명주㈜', 'Andongjeontongmyeongju Brewery', '대한민국', '경상북도', 'KR_GYEONGBUK', 'https://smartstore.naver.com/andongmyongju/products/3458697714', NULL, '안동전통명주㈜(Andongjeontongmyeongju Brewery)은 대한민국 경상북도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 느낌 30·필·느낌 등이 포함됩니다. 제품 원료에는 쌀·누룩·국 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '안동전통명주㈜ (Andongjeontongmyeongju Brewery) is a distilled soju producer based in Gyeongsangbuk-do, South Korea. Its core range includes 느낌 30, 필, 느낌. The range uses ingredients such as rice, nuruk or koji. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '명품 안동소주, 안동전통명주(주), 안동전통명주㈜, Andongjeontongmyeongju Brewery, 느낌 30, 필, 느낌'),
    ('양반안동소주', 'Yangban Andong Soju', '대한민국', '경상북도', 'KR_GYEONGBUK', 'https://www.sojumall.com/htm/main.htm', NULL, '양반안동소주(Yangban Andong Soju)은 대한민국 경상북도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 양반안동소주 3년산 호리병 등이 포함됩니다. 제품 원료에는 쌀 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '양반안동소주 (Yangban Andong Soju) is a distilled soju producer based in Gyeongsangbuk-do, South Korea. Its core range includes 양반안동소주 3년산 호리병. The range uses ingredients such as rice. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '양반안동소주, Yangban Andong Soju, 양반안동소주 3년산 호리병'),
    ('오산양조', 'Osanyangjo Brewery', '대한민국', '경기도', 'KR_GYEONGGI', 'https://www.osansool.com/', NULL, '오산양조(Osanyangjo Brewery)은 대한민국 경기도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 독산 53·독산 30 등이 포함됩니다. 제품 원료에는 쌀·누룩·국 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '오산양조 (Osanyangjo Brewery) is a distilled soju producer based in Gyeonggi-do, South Korea. Its core range includes 독산 53, 독산 30. The range uses ingredients such as rice, nuruk or koji. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '오산양조, Osanyangjo Brewery, 독산 53, 독산 30'),
    ('옥순가 소곡주 마주', 'Oksunga Sogokju Maju Brewery', '대한민국', '충청남도', 'KR_CHUNGNAM', 'https://smartstore.naver.com/oksoonga/products/4780697995', NULL, '옥순가 소곡주 마주(Oksunga Sogokju Maju Brewery)은 대한민국 충청남도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 마주 소곡화주 등이 포함됩니다. 제품 원료에는 쌀·밀·누룩·국 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '옥순가 소곡주 마주 (Oksunga Sogokju Maju Brewery) is a distilled soju producer based in Chungcheongnam-do, South Korea. Its core range includes 마주 소곡화주. The range uses ingredients such as rice, wheat, nuruk or koji. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '옥순가 소곡주 마주, Oksunga Sogokju Maju Brewery, 마주 소곡화주'),
    ('우리도가', 'Uridoga Brewery', '대한민국', '경기도', 'KR_GYEONGGI', 'https://smartstore.naver.com/wooridoga/products/6611468981', NULL, '우리도가(Uridoga Brewery)은 대한민국 경기도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 가평소주 등이 포함됩니다. 제품 원료에는 쌀 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '우리도가 (Uridoga Brewery) is a distilled soju producer based in Gyeonggi-do, South Korea. Its core range includes 가평소주. The range uses ingredients such as rice. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '우리도가, Uridoga Brewery, 가평소주'),
    ('원스피리츠 농업법인 주식회사', 'Won Spirits Agricultural Corporation', '대한민국', '강원도', 'KR_GANGWON', 'https://wonsoju.com/', NULL, '원스피리츠 농업법인 주식회사(Won Spirits Agricultural Corporation)은 대한민국 강원도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 원소주 등이 포함됩니다. 제품 원료에는 쌀 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '원스피리츠 농업법인 주식회사 (Won Spirits Agricultural Corporation) is a distilled soju producer based in Gangwon-do, South Korea. Its core range includes 원소주. The range uses ingredients such as rice. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '원스피리츠 농업법인 주식회사, Won Spirits Agricultural Corporation, 원소주'),
    ('원조소곡주', 'Wonjosogokju Brewery', '대한민국', '충청남도', 'KR_CHUNGNAM', 'http://www.xn--399ay50bszdtxbcu.com/', NULL, '원조소곡주(Wonjosogokju Brewery)은 대한민국 충청남도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 한산 소곡화주 등이 포함됩니다. 제품 원료에는 쌀·누룩·국 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '원조소곡주 (Wonjosogokju Brewery) is a distilled soju producer based in Chungcheongnam-do, South Korea. Its core range includes 한산 소곡화주. The range uses ingredients such as rice, nuruk or koji. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '원조소곡주, Wonjosogokju Brewery, 한산 소곡화주'),
    ('월광주조', 'Wolgwangjujo Brewery', '대한민국', '광주', 'KR_GWANGJU', 'https://smartstore.naver.com/wgwgwg', NULL, '월광주조(Wolgwangjujo Brewery)은 대한민국 광주에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 월광주 42 등이 포함됩니다. 제품 원료에는 쌀·누룩·국 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '월광주조 (Wolgwangjujo Brewery) is a distilled soju producer based in Gwangju, South Korea. Its core range includes 월광주 42. The range uses ingredients such as rice, nuruk or koji. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '월광주조, Wolgwangjujo Brewery, 월광주 42'),
    ('유토피아㈜', 'Yutopia Brewery', '대한민국', '경상북도', 'KR_GYEONGBUK', 'http://www.sojumall.com/', NULL, '유토피아㈜(Yutopia Brewery)은 대한민국 경상북도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 로얄 안동소주·양반안동소주·양식주 등이 포함됩니다. 제품 원료에는 쌀 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '유토피아㈜ (Yutopia Brewery) is a distilled soju producer based in Gyeongsangbuk-do, South Korea. Its core range includes 로얄 안동소주, 양반안동소주, 양식주. The range uses ingredients such as rice. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '(농)유토피아㈜, 유토피아(주), 유토피아㈜, Yutopia Brewery, 로얄 안동소주, 양반안동소주, 양식주'),
    ('제이앤제이 브루어리㈜', 'J&J Brewery Ltd.', '대한민국', NULL, NULL, NULL, NULL, '제이앤제이 브루어리㈜(J&J Brewery Ltd.)은 대한민국에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 청혼 Red 25 등이 포함됩니다. 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '제이앤제이 브루어리㈜ (J&J Brewery Ltd.) is a distilled soju producer operating in South Korea. Its core range includes 청혼 Red 25. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', 'J&J Brewery, 청혼레드25, 청혼 Red, 제이앤제이 브루어리㈜, J&J Brewery Ltd., 청혼 Red 25'),
    ('제주고소리술익는집', 'Jeju Gosorisul Ikneunjip', '대한민국', '제주도', 'KR_JEJU', 'http://jejugosorisul.com/', NULL, '제주고소리술익는집(Jeju Gosorisul Ikneunjip)은 대한민국 제주도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 제주술익는집 고소리술·제주고소리술 등이 포함됩니다. 제품 원료에는 누룩·국 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '제주고소리술익는집 (Jeju Gosorisul Ikneunjip) is a distilled soju producer based in Jeju-do, South Korea. Its core range includes 제주술익는집 고소리술, 제주고소리술. The range uses ingredients such as nuruk or koji. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '제주고소리술익는집, Jeju Gosorisul Ikneunjip, 제주술익는집 고소리술, 제주고소리술'),
    ('제천한약영농조합법인', 'Jecheonhanyak Brewery', '대한민국', '충청북도', 'KR_CHUNGBUK', 'https://www.xn--o39aj06azycp7ebxxnfa.com/', NULL, '제천한약영농조합법인(Jecheonhanyak Brewery)은 대한민국 충청북도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 한비 쌀소주·한비 오가피술·한비의림소주·한비쌀소주·한비소주 등이 포함됩니다. 제품 원료에는 쌀·누룩·국 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '제천한약영농조합법인 (Jecheonhanyak Brewery) is a distilled soju producer based in Chungcheongbuk-do, South Korea. Its core range includes 한비 쌀소주, 한비 오가피술, 한비의림소주, 한비쌀소주, 한비소주. The range uses ingredients such as rice, nuruk or koji. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '제천한약영농조합법인, 제천한약 영농조합법인, 제천한약, Jecheonhanyak Brewery, 한비 쌀소주, 한비 오가피술, 한비의림소주, 한비쌀소주, 한비소주'),
    ('조은술세종㈜', 'Joeunsul Sejong Co., Ltd.', '대한민국', '충청북도', 'KR_CHUNGBUK', 'http://www.joeunsulsj.co.kr/', NULL, '조은술세종㈜(Joeunsul Sejong Co., Ltd.)은 대한민국 충청북도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 유기농 이도 32·유기농 이도 42·이도22·이도 등이 포함됩니다. 제품 원료에는 쌀 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '조은술세종㈜ (Joeunsul Sejong Co., Ltd.) is a distilled soju producer based in Chungcheongbuk-do, South Korea. Its core range includes 유기농 이도 32, 유기농 이도 42, 이도22, 이도. The range uses ingredients such as rice. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '조은술 세종, 조은술세종, 조은술세종(주), 조은술세종㈜, Joeunsul Sejong Co., Ltd., 유기농 이도 32, 유기농 이도 42, 이도22, 이도'),
    ('죽향도가', 'Jukhyangdoga Brewery', '대한민국', '전라남도', 'KR_JEONNAM', 'https://smartstore.naver.com/jhdg', NULL, '죽향도가(Jukhyangdoga Brewery)은 대한민국 전라남도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 대숲 맑은 담양향 Gold 등이 포함됩니다. 제품 원료에는 쌀 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '죽향도가 (Jukhyangdoga Brewery) is a distilled soju producer based in Jeollanam-do, South Korea. Its core range includes 대숲 맑은 담양향 Gold. The range uses ingredients such as rice. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '죽향도가, Jukhyangdoga Brewery, 대숲 맑은 담양향 Gold'),
    ('지비지 스피리츠㈜ 농업회사법인', 'GBG Spirits Agricultural Corporation', '대한민국', NULL, NULL, NULL, NULL, '지비지 스피리츠㈜ 농업회사법인(GBG Spirits Agricultural Corporation)은 대한민국에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 경복궁 소주40 등이 포함됩니다. 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '지비지 스피리츠㈜ 농업회사법인 (GBG Spirits Agricultural Corporation) is a distilled soju producer operating in South Korea. Its core range includes 경복궁 소주40. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', 'GBG Spirits, 경복궁 소주, 지비지 스피리츠㈜ 농업회사법인, GBG Spirits Agricultural Corporation, 경복궁 소주40'),
    ('추연당', 'Chuyeondang Brewery', '대한민국', '경기도', 'KR_GYEONGGI', 'https://smartstore.naver.com/chuyondang', NULL, '추연당(Chuyeondang Brewery)은 대한민국 경기도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 소여강 등이 포함됩니다. 제품 원료에는 쌀·누룩·국 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '추연당 (Chuyeondang Brewery) is a distilled soju producer based in Gyeonggi-do, South Korea. Its core range includes 소여강. The range uses ingredients such as rice, nuruk or koji. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '추연당, Chuyeondang Brewery, 소여강'),
    ('한산소곡주', 'Hansansogokju Brewery', '대한민국', '충청남도', 'KR_CHUNGNAM', 'http://www.sogokju.co.kr/', NULL, '한산소곡주(Hansansogokju Brewery)은 대한민국 충청남도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 불소주·화백 등이 포함됩니다. 제품 원료에는 쌀·밀·누룩·국 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '한산소곡주 (Hansansogokju Brewery) is a distilled soju producer based in Chungcheongnam-do, South Korea. Its core range includes 불소주, 화백. The range uses ingredients such as rice, wheat, nuruk or koji. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '한산소곡주, Hansansogokju Brewery, 불소주, 화백'),
    ('한산예담은소곡주', 'Hansanyedameunsogokju Brewery', '대한민국', '충청남도', 'KR_CHUNGNAM', 'http://xn--399a58ii8nflevubg8d.com/', NULL, '한산예담은소곡주(Hansanyedameunsogokju Brewery)은 대한민국 충청남도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 한산예담은 한산소곡화주 등이 포함됩니다. 제품 원료에는 쌀·누룩·국 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '한산예담은소곡주 (Hansanyedameunsogokju Brewery) is a distilled soju producer based in Chungcheongnam-do, South Korea. Its core range includes 한산예담은 한산소곡화주. The range uses ingredients such as rice, nuruk or koji. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '한산예담은소곡주, Hansanyedameunsogokju Brewery, 한산예담은 한산소곡화주'),
    ('한주양조', 'Hanjuyangjo Brewery', '대한민국', '경기도', 'KR_GYEONGGI', 'https://www.hanju.kr/hanju', NULL, '한주양조(Hanjuyangjo Brewery)은 대한민국 경기도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 한주매화·한주/25도·한주/20도·한주/35도 등이 포함됩니다. 제품 원료에는 쌀·밀·누룩·국 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '한주양조 (Hanjuyangjo Brewery) is a distilled soju producer based in Gyeonggi-do, South Korea. Its core range includes 한주매화, 한주/25도, 한주/20도, 한주/35도. The range uses ingredients such as rice, wheat, nuruk or koji. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '한주양조, Hanjuyangjo Brewery, 한주매화, 한주/25도, 한주/20도, 한주/35도'),
    ('협동조합 모월', 'MOWOL Cooperative', '대한민국', '강원도', 'KR_GANGWON', 'http://www.mowall.co.kr/', NULL, '협동조합 모월(MOWOL Cooperative)은 대한민국 강원도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 모월 로·모월 인·모월인 등이 포함됩니다. 제품 원료에는 쌀·누룩·국 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '협동조합 모월 (MOWOL Cooperative) is a distilled soju producer based in Gangwon-do, South Korea. Its core range includes 모월 로, 모월 인, 모월인. The range uses ingredients such as rice, nuruk or koji. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '모월, 모월 협동조합, 주담, 협동조합 모월, MOWOL Cooperative, 모월 로, 모월 인, 모월인'),
    ('화심주조', 'Hwasimjujo Brewery', '대한민국', '경기도', 'KR_GYEONGGI', 'https://hwasimjujo.co.kr/', NULL, '화심주조(Hwasimjujo Brewery)은 대한민국 경기도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 화심소주 군고구마 등이 포함됩니다. 제품 원료에는 고구마 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '화심주조 (Hwasimjujo Brewery) is a distilled soju producer based in Gyeonggi-do, South Korea. Its core range includes 화심소주 군고구마. The range uses ingredients such as sweet potato. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '화심주조, Hwasimjujo Brewery, 화심소주 군고구마'),
    ('황금보리(유)농업회사법인', 'Hwanggeumbori Brewery', '대한민국', '충청남도', 'KR_CHUNGNAM', 'http://www.xn--jj0bu4t8rc0w2b.com/', NULL, '황금보리(유)농업회사법인(Hwanggeumbori Brewery)은 대한민국 충청남도에 기반을 둔 증류식 소주 제조사입니다. 대표 제품군에는 황금보리 증류주 25·황금보리주/40도·황금보리주/25도·황금보리주/17도 등이 포함됩니다. 제품 원료에는 보리·누룩·국 등이 쓰이며, 원료 선택과 발효·증류 방식의 차이를 살려 제품별 개성을 구성하는 데 초점을 둡니다.', '황금보리(유)농업회사법인 (Hwanggeumbori Brewery) is a distilled soju producer based in Chungcheongnam-do, South Korea. Its core range includes 황금보리 증류주 25, 황금보리주/40도, 황금보리주/25도, 황금보리주/17도. The range uses ingredients such as barley, nuruk or koji. Its portfolio emphasizes ingredient choice and differences in fermentation and distillation to give each expression a distinct identity.', '황금보리(유)농업회사법인, 황금보리(유한), Hwanggeumbori Brewery, 황금보리 증류주 25, 황금보리주/40도, 황금보리주/25도, 황금보리주/17도');

INSERT INTO producer
    (type, name_ko, name_en, country, region, region_code, website, founded_year,
     description_ko, description_en, search_keywords, created_at, updated_at)
SELECT
    'OTHER', seed.name_ko, seed.name_en, seed.country, seed.region, seed.region_code,
    seed.website, seed.founded_year, seed.description_ko, seed.description_en,
    seed.search_keywords, NOW(6), NOW(6)
FROM tmp_korean_soju_producer_seed seed
WHERE NOT EXISTS (
    SELECT 1
    FROM producer existing
    WHERE existing.country = seed.country
      AND (
          existing.name_ko = seed.name_ko
          OR LOWER(existing.name_en) = LOWER(seed.name_en)
      )
);

DROP TABLE tmp_korean_soju_producer_seed;
