-- =============================================================================
-- CaskByCask 기초데이터 — 위스키 증류소 추가분 (Distillery seed, 보강)
-- =============================================================================
-- 작성 기준일: 2026-06-06
-- 범위: V2 누락 보강 — 대중성(클래식) + 올드 바틀(폐쇄·사일런트) + 신생(크래프트) 증류소.
--       whiskybase 의 브랜드 코드(GF, L 등 비공식 약어)는 제외하고, 실재하는 증류소만 수록.
--
-- [주의]
--   - Flyway 버전 마이그레이션입니다. 한 번 적용된 후에는 이 파일을 수정하지 마세요.
--   - producer.type 은 기본값이 없는 NOT NULL → INSERT 동안만 'DISTILLERY' 기본값을 지정.
--   - search_keywords(V9 추가)는 생략 → NULL.
--   - 중복 방지: V2 에 이미 있는 증류소는 제외했습니다.
--   - website 가 확실치 않거나 폐쇄 증류소는 NULL. 폐쇄·신생 여부는 description 에 명시.
-- =============================================================================
ALTER TABLE producer ALTER COLUMN type SET DEFAULT 'DISTILLERY';

INSERT INTO producer
    (name_ko, name_en, country, region, website, founded_year, description_ko, description_en, created_at, updated_at)
VALUES
-- ===================== 스코틀랜드 — Speyside (클래식/블렌드 핵심) =====================
('롱몬', 'Longmorn', '스코틀랜드', 'Speyside', NULL, 1893,
 '진한 과실·꿀 풍미로 애호가들에게 추앙받는 스페이사이드 몰트. 시바스 블렌드의 핵심 원액으로도 유명하다.',
 'A Speyside malt revered by enthusiasts for its rich fruit and honey, also a key component of Chivas blends.',
 NOW(6), NOW(6)),
('링크우드', 'Linkwood', '스코틀랜드', 'Speyside', NULL, 1821,
 '꽃향과 섬세함으로 정평이 난 스페이사이드 몰트. 디아지오 ''플로라 앤 파우나''로 잘 알려져 있다.',
 'A Speyside malt esteemed for its floral delicacy, well known through Diageo''s "Flora & Fauna" range.',
 NOW(6), NOW(6)),
('토모어', 'Tormore', '스코틀랜드', 'Speyside', NULL, 1958,
 '''스페이사이드의 진주''로 불리는 웅장한 건축물의 증류소. 깔끔하고 가벼운 스타일이 특징이다.',
 'A distillery in a grand building dubbed "the Pearl of Speyside," known for a clean, light style.',
 NOW(6), NOW(6)),
('스페이번', 'Speyburn', '스코틀랜드', 'Speyside', 'https://www.speyburn.com', 1897,
 '협곡에 자리한 그림 같은 증류소. 부드럽고 가성비 좋은 스페이사이드 몰트로 사랑받는다.',
 'A picturesque glen distillery beloved for its smooth, great-value Speyside malt.',
 NOW(6), NOW(6)),
('더프타운', 'Dufftown', '스코틀랜드', 'Speyside', NULL, 1895,
 '디아지오의 대형 증류소로 ''싱글톤 오브 더프타운''으로 출시된다. 풍부하고 부드러운 스타일이다.',
 'A large Diageo distillery bottled as "The Singleton of Dufftown," with a rich, smooth style.',
 NOW(6), NOW(6)),
('녹칸도', 'Knockando', '스코틀랜드', 'Speyside', NULL, 1898,
 '가볍고 우아한 스타일의 스페이사이드 몰트. J&B 블렌드의 핵심 원액으로 유명하다.',
 'A light, elegant Speyside malt famed as a core component of the J&B blend.',
 NOW(6), NOW(6)),
('글렌 엘긴', 'Glen Elgin', '스코틀랜드', 'Speyside', NULL, 1898,
 '꿀과 꽃향이 풍부한 클래식 스페이사이드 몰트. 화이트 호스 블렌드의 핵심이다.',
 'A classic Speyside malt rich in honey and floral notes, central to the White Horse blend.',
 NOW(6), NOW(6)),
('벤리네스', 'Benrinnes', '스코틀랜드', 'Speyside', NULL, 1826,
 '부분 삼중 증류의 흔적이 남은 묵직하고 미트한 스페이사이드 몰트.',
 'A weighty, meaty Speyside malt that retains traces of its old partial triple-distillation.',
 NOW(6), NOW(6)),
('글렌토커스', 'Glentauchers', '스코틀랜드', 'Speyside', NULL, 1897,
 '전통 공정을 잘 보존한 증류소. 발렌타인 블렌드의 핵심 몰트로 쓰인다.',
 'A distillery that preserves traditional methods, a key malt in the Ballantine''s blend.',
 NOW(6), NOW(6)),
('글렌버기', 'Glenburgie', '스코틀랜드', 'Speyside', NULL, 1810,
 '과실 향이 풍부한 몰트로 발렌타인 블렌드의 중심을 이룬다.',
 'A fruity malt that forms the heart of the Ballantine''s blend.',
 NOW(6), NOW(6)),
('밀튼더프', 'Miltonduff', '스코틀랜드', 'Speyside', NULL, 1824,
 '엘긴 인근의 대형 증류소. 부드럽고 꽃향 가득한 발렌타인 블렌드용 몰트로 유명하다.',
 'A large distillery near Elgin famed for its smooth, floral malt used in Ballantine''s.',
 NOW(6), NOW(6)),
('로즈아일', 'Roseisle', '스코틀랜드', 'Speyside', NULL, 2009,
 '디아지오가 2009년 가동한 초대형 신생 증류소. 가볍고 묵직한 두 스타일을 모두 생산한다.',
 'A vast modern distillery commissioned by Diageo in 2009, capable of producing both light and heavy styles.',
 NOW(6), NOW(6)),
('글렌 키스', 'Glen Keith', '스코틀랜드', 'Speyside', NULL, 1957,
 '한동안 가동을 멈췄다 2013년 재가동한 시바스 소속 증류소.',
 'A Chivas-owned distillery that resumed production in 2013 after a period of silence.',
 NOW(6), NOW(6)),
('오크로이스크', 'Auchroisk', '스코틀랜드', 'Speyside', NULL, 1974,
 '깔끔하고 가벼운 스타일의 디아지오 증류소. ''플로라 앤 파우나''로도 출시된다.',
 'A clean, light-styled Diageo distillery also released in the "Flora & Fauna" range.',
 NOW(6), NOW(6)),
('글렌로시', 'Glenlossie', '스코틀랜드', 'Speyside', NULL, 1876,
 '풀세이버리하고 부드러운 몰트로 헤이그 블렌드의 핵심을 이룬다.',
 'A grassy, supple malt that forms a backbone of the Haig blends.',
 NOW(6), NOW(6)),
('매녹모어', 'Mannochmore', '스코틀랜드', 'Speyside', NULL, 1971,
 '글렌로시와 부지를 공유하는 증류소. 한때 검은 위스키 ''로흐 듀''로 화제가 되었다.',
 'A distillery sharing a site with Glenlossie, once notorious for the jet-black whisky "Loch Dhu".',
 NOW(6), NOW(6)),
-- ===================== 스코틀랜드 — Highland (클래식) =====================
('글렌드로낙', 'GlenDronach', '스코틀랜드', 'Highland', 'https://www.glendronachdistillery.com', 1826,
 '진한 셰리 캐스크 숙성으로 ''셰리 폭탄''으로 불리는 이스턴 하이랜드의 명가.',
 'An Eastern Highland distillery dubbed a "sherry bomb" for its rich sherry-cask maturation.',
 NOW(6), NOW(6)),
('벤 네비스', 'Ben Nevis', '스코틀랜드', 'Highland', 'https://www.bennevisdistillery.com', 1825,
 '영국 최고봉 기슭의 역사적 증류소. 니카(일본) 소유로 묵직하고 개성 있는 스타일로 컬트적 인기를 누린다.',
 'A historic distillery at the foot of Britain''s highest mountain, owned by Nikka (Japan), with a cult following for its weighty, characterful style.',
 NOW(6), NOW(6)),
('블레어 아솔', 'Blair Athol', '스코틀랜드', 'Highland', NULL, 1798,
 '피틀로크리에 자리한 증류소. 진하고 견과적인 몰트로 벨즈 블렌드의 핵심이다.',
 'A Pitlochry distillery whose rich, nutty malt is the heart of the Bell''s blend.',
 NOW(6), NOW(6)),
('글렌 기리', 'Glen Garioch', '스코틀랜드', 'Highland', 'https://www.glengarioch.com', 1797,
 '스코틀랜드에서 가장 오래된 증류소 중 하나. 과거 피티드 스타일로도 유명했다.',
 'One of Scotland''s oldest distilleries, also known historically for its peated style.',
 NOW(6), NOW(6)),
('아드모어', 'Ardmore', '스코틀랜드', 'Highland', 'https://www.ardmorewhisky.com', 1898,
 '하이랜드에서 드물게 피트를 사용하는 증류소. 티처스 블렌드의 핵심 몰트다.',
 'A rare peated Highland distillery, the core malt of the Teacher''s blend.',
 NOW(6), NOW(6)),
('글렌글라사', 'Glenglassaugh', '스코틀랜드', 'Highland', 'https://www.glenglassaugh.com', 1875,
 '해안가의 증류소. 오랜 휴면 끝에 2008년 부활해 해풍 머금은 개성적 몰트를 만든다.',
 'A coastal distillery revived in 2008 after long dormancy, making a distinctive, sea-influenced malt.',
 NOW(6), NOW(6)),
('글렌카담', 'Glencadam', '스코틀랜드', 'Highland', 'https://www.glencadamwhisky.com', 1825,
 '브레친의 소규모 증류소. 깔끔하고 크리미한 ''이스턴 하이랜드'' 스타일로 알려져 있다.',
 'A small Brechin distillery known for a clean, creamy "Eastern Highland" style.',
 NOW(6), NOW(6)),
('로열 브라클라', 'Royal Brackla', '스코틀랜드', 'Highland', NULL, 1812,
 '''왕의 위스키''라는 칭호를 받은 역사적 증류소. 과실 향 풍부한 몰트로 듀어스 블렌드에 쓰인다.',
 'A historic distillery granted the title "The King''s Own Whisky," a fruity malt used in the Dewar''s blend.',
 NOW(6), NOW(6)),
('맥더프', 'Macduff', '스코틀랜드', 'Highland', NULL, 1960,
 '공식 병입은 ''글렌 데버론''으로 출시되는 해안가 증류소. 부드러운 과실 스타일이 특징이다.',
 'A coastal distillery whose official bottlings appear as "Glen Deveron," known for a soft, fruity style.',
 NOW(6), NOW(6)),
('티니닉', 'Teaninich', '스코틀랜드', 'Highland', NULL, 1817,
 '여과 매시로 만드는 깔끔하고 왁시한 몰트. 디아지오 블렌드의 핵심 원액이다.',
 'A clean, waxy malt made with a mash filter, a key fill for Diageo blends.',
 NOW(6), NOW(6)),
-- ===================== 스코틀랜드 — Island (섬) =====================
('스카파', 'Scapa', '스코틀랜드', 'Island', NULL, 1885,
 '오크니 섬에서 하이랜드 파크와 이웃한 증류소. 논피티드의 부드럽고 과실 가득한 스타일이 특징이다.',
 'An Orkney distillery neighbouring Highland Park, known for an unpeated, smooth and fruity style.',
 NOW(6), NOW(6)),
('아일 오브 해리스', 'Isle of Harris', '스코틀랜드', 'Island', 'https://www.harrisdistillery.com', 2015,
 '아우터 헤브리디스 해리스 섬의 신생 증류소. 진(The Hearach 진)으로 먼저 유명해진 뒤 싱글몰트 ''히어라크''를 출시했다.',
 'A new distillery on the Isle of Harris in the Outer Hebrides, first famed for its gin before releasing the "Hearach" single malt.',
 NOW(6), NOW(6)),
-- ===================== 스코틀랜드 — Lowland (신생) =====================
('에일사 베이', 'Ailsa Bay', '스코틀랜드', 'Lowland', NULL, 2007,
 '윌리엄 그랜트가 거번 부지에 세운 대형 증류소. 측정 기반(ppm·SPPM)으로 만든 피티드 몰트로 알려져 있다.',
 'A large William Grant distillery on the Girvan site, known for a measurement-driven (ppm/SPPM) peated malt.',
 NOW(6), NOW(6)),
('홀리루드', 'Holyrood', '스코틀랜드', 'Lowland', 'https://www.holyrooddistillery.co.uk', 2019,
 '에든버러 도심에 자리한 신생 증류소. 다양한 효모·맥아 실험으로 풍미 스펙트럼을 넓힌다.',
 'A new distillery in central Edinburgh, expanding flavour through extensive yeast and malt experimentation.',
 NOW(6), NOW(6)),
('인치데어니', 'InchDairnie', '스코틀랜드', 'Lowland', 'https://www.inchdairniedistillery.com', 2015,
 '파이프의 혁신적 신생 증류소. 라이 위스키 ''라이로'' 등 실험적 제품으로 주목받는다.',
 'An innovative new distillery in Fife, drawing attention with experimental releases such as its "RyeLaw" rye whisky.',
 NOW(6), NOW(6)),
-- ===================== 스코틀랜드 — 그레인 / 폐쇄(사일런트, 올드 바틀) =====================
('캐머런 브리지', 'Cameronbridge', '스코틀랜드', 'Lowland', NULL, 1824,
 '디아지오의 거대한 그레인 증류소. 헤이그 클럽·고든스 등 블렌드·주정의 핵심 생산지다.',
 'A vast Diageo grain distillery, the key source for blends and spirits such as Haig Club and Gordon''s.',
 NOW(6), NOW(6)),
('인버고든', 'Invergordon', '스코틀랜드', 'Highland', NULL, 1959,
 '하이랜드 유일의 대형 그레인 증류소. 화이트 앤 맥케이 등 블렌드용 그레인 위스키를 만든다.',
 'The only large grain distillery in the Highlands, producing grain whisky for blends such as Whyte & Mackay.',
 NOW(6), NOW(6)),
('노스 브리티시', 'North British', '스코틀랜드', 'Lowland', NULL, 1885,
 '에든버러의 대형 그레인 증류소. 100년 넘게 다수 블렌드의 그레인 원액을 공급해 왔다.',
 'A large Edinburgh grain distillery that has supplied grain spirit to many blends for over a century.',
 NOW(6), NOW(6)),
('포트 던다스', 'Port Dundas', '스코틀랜드', 'Lowland', NULL, 1811,
 '글래스고의 역사적 그레인 증류소. 2010년 폐쇄되었으나 올드 그레인 보틀로 애호가들의 사랑을 받는다.',
 'A historic Glasgow grain distillery; closed in 2010 but cherished by enthusiasts as old grain bottlings.',
 NOW(6), NOW(6)),
('캠버스', 'Cambus', '스코틀랜드', 'Lowland', NULL, 1806,
 '클락매넌셔의 그레인 증류소. 1993년 폐쇄되었으며 희소한 싱글 그레인으로 평가받는다.',
 'A Clackmannanshire grain distillery closed in 1993, prized as a scarce single grain.',
 NOW(6), NOW(6)),
('레이디번', 'Ladyburn', '스코틀랜드', 'Lowland', NULL, 1966,
 '거번 단지 안에서 가동됐던 몰트 증류소. 1975년 폐쇄돼 극히 희소한 올드 바틀로만 남아 있다.',
 'A malt distillery once operating within the Girvan complex; closed in 1975 and surviving only as extremely rare old bottles.',
 NOW(6), NOW(6)),
('킨클레이스', 'Kinclaith', '스코틀랜드', 'Lowland', NULL, 1957,
 '글래스고 스트라스클라이드 단지 안에 있던 로랜드 몰트. 1975년 철거돼 컬렉터용 올드 바틀로만 거래된다.',
 'A Lowland malt within Glasgow''s Strathclyde complex; dismantled in 1975 and now traded only as collector old bottles.',
 NOW(6), NOW(6)),
('벤 위비스', 'Ben Wyvis', '스코틀랜드', 'Highland', NULL, 1965,
 '인버고든 그레인 단지 안에 있던 몰트 증류소. 1977년 폐쇄돼 극소수 올드 바틀만 존재한다.',
 'A malt distillery inside the Invergordon grain complex; closed in 1977, with only a handful of old bottles in existence.',
 NOW(6), NOW(6)),
-- ===================== 아일랜드 =====================
('킬베간', 'Kilbeggan', '아일랜드', '웨스트미스 (킬베간)', 'https://www.kilbegganwhiskey.com', 1757,
 '1757년 라이선스를 받은, 세계에서 가장 오래된 라이선스 증류소 중 하나. 부활해 가동 중이다.',
 'Licensed in 1757, one of the oldest licensed distilleries in the world, now revived and operating.',
 NOW(6), NOW(6)),
('로 앤 코', 'Roe & Co', '아일랜드', '더블린', 'https://www.roeandcowhiskey.com', 2019,
 '디아지오가 옛 기네스 발전소 자리에 세운 더블린 도심의 신생 증류소.',
 'A new Dublin city distillery built by Diageo on the site of a former Guinness power station.',
 NOW(6), NOW(6)),
-- ===================== 미국 (버번/라이 — 대중성 + 신생 + 폐쇄) =====================
('엔젤스 엔비', 'Angel''s Envy', '미국', '켄터키', 'https://www.angelsenvy.com', 2010,
 '루이빌의 인기 증류소. 포트·럼 캐스크 피니시 버번으로 화제를 모았다.',
 'A popular Louisville distillery that made its name with port- and rum-finished bourbon.',
 NOW(6), NOW(6)),
('바즈타운 버번 컴퍼니', 'Bardstown Bourbon Company', '미국', '켄터키', 'https://www.bardstownbourbon.com', 2014,
 '''버번의 수도'' 바즈타운의 현대적 대형 신생 증류소. 협업·피니시 시리즈로 인기를 얻었다.',
 'A modern large distillery in Bardstown, the "Bourbon Capital," popular for its collaboration and finishing series.',
 NOW(6), NOW(6)),
('뉴 리프', 'New Riff', '미국', '켄터키', 'https://www.newriffdistilling.com', 2014,
 '신시내티 인근 뉴포트의 크래프트 증류소. ''보틀드 인 본드'' 버번·라이로 호평받는다.',
 'A craft distillery in Newport near Cincinnati, acclaimed for its "Bottled in Bond" bourbon and rye.',
 NOW(6), NOW(6)),
('엉클 니어리스트', 'Uncle Nearest', '미국', '테네시', 'https://www.unclenearest.com', 2017,
 '잭 다니엘에게 증류를 가르친 흑인 장인 니어리스트 그린을 기리는 인기 테네시 위스키.',
 'A popular Tennessee whiskey honouring Nearest Green, the Black master distiller who taught Jack Daniel.',
 NOW(6), NOW(6)),
('캐슬 앤 키', 'Castle & Key', '미국', '켄터키', 'https://www.castleandkey.com', 2018,
 '전설적 양조가 E.H. 테일러의 옛 ''올드 테일러'' 증류소를 복원해 부활시킨 명소.',
 'A landmark distillery that restored and revived the historic "Old Taylor" distillery of E.H. Taylor.',
 NOW(6), NOW(6)),
('로스 앤 스큅 (MGP)', 'Ross & Squibb (MGP)', '미국', '인디애나', 'https://www.mgpingredients.com', 1847,
 '로런스버그의 대형 증류소. 다수 유명 라이·버번 브랜드에 원액을 공급하는 핵심 생산지로 유명하다.',
 'A large Lawrenceburg distillery famed as the source of spirit for many well-known rye and bourbon brands.',
 NOW(6), NOW(6)),
('새거모어 스피릿', 'Sagamore Spirit', '미국', '메릴랜드', 'https://www.sagamorespirit.com', 2017,
 '볼티모어 부둣가의 인기 증류소. 메릴랜드 스타일 라이 위스키를 부흥시켰다.',
 'A popular distillery on the Baltimore waterfront that revived Maryland-style rye whiskey.',
 NOW(6), NOW(6)),
('킹스 카운티', 'Kings County Distillery', '미국', '뉴욕', 'https://www.kingscountydistillery.com', 2010,
 '브루클린 해군 부지에 자리한 뉴욕시 최초의 금주법 이후 위스키 증류소.',
 'New York City''s first post-Prohibition whiskey distillery, located in the Brooklyn Navy Yard.',
 NOW(6), NOW(6)),
('A. 스미스 보먼', 'A. Smith Bowman', '미국', '버지니아', 'https://www.asmithbowman.com', 1934,
 '버지니아의 역사적 증류소. 버팔로 트레이스 계열로 ''존 J. 보먼'' 버번으로 유명하다.',
 'A historic Virginia distillery in the Buffalo Trace family, famed for its "John J. Bowman" bourbon.',
 NOW(6), NOW(6)),
('스티첼-웰러', 'Stitzel-Weller', '미국', '켄터키', NULL, 1935,
 '''파피 반 윙클''의 뿌리가 된 전설적 증류소. 1992년 가동을 멈췄으나 올드 바틀은 컬렉터의 성배로 꼽힌다.',
 'The legendary distillery behind the roots of "Pappy Van Winkle"; production ceased in 1992, but its old bottles are a collector''s holy grail.',
 NOW(6), NOW(6)),
-- ===================== 캐나다 =====================
('크라운 로열 (김리)', 'Crown Royal (Gimli)', '캐나다', '매니토바', 'https://www.crownroyal.com', 1968,
 '매니토바 김리의 대형 증류소. 세계에서 가장 많이 팔리는 캐나다 위스키 ''크라운 로열''을 만든다.',
 'A large distillery in Gimli, Manitoba, producing "Crown Royal," the best-selling Canadian whisky in the world.',
 NOW(6), NOW(6)),
('앨버타 디스틸러스', 'Alberta Distillers', '캐나다', '앨버타', NULL, 1946,
 '캘거리의 라이 위스키 전문 증류소. 100% 호밀 위스키로 애호가들의 사랑을 받는다.',
 'A Calgary distillery specialising in rye, beloved by enthusiasts for its 100% rye whiskies.',
 NOW(6), NOW(6)),
('포티 크릭', 'Forty Creek', '캐나다', '온타리오', 'https://www.fortycreekwhisky.com', 1992,
 '온타리오 그림스비의 인기 크래프트 증류소. 와인메이커 출신 존 홀이 설립했다.',
 'A popular craft distillery in Grimsby, Ontario, founded by former winemaker John Hall.',
 NOW(6), NOW(6)),
-- ===================== 일본 (대중성 + 신생 + 폐쇄) =====================
('치타', 'Chita', '일본', '아이치', NULL, 1972,
 '산토리의 그레인 위스키 증류소. 하이볼·블렌드의 핵심이며 싱글 그레인 ''치타''로도 출시된다.',
 'Suntory''s grain whisky distillery, central to highballs and blends, also bottled as the single grain "Chita".',
 NOW(6), NOW(6)),
('사부로마루', 'Saburomaru', '일본', '도야마', 'https://www.wakatsuru.co.jp', 1952,
 '와카쓰루 주조의 증류소. 크라우드펀딩으로 부활해 피티드 몰트로 컬트적 인기를 얻은 신예다.',
 'The distillery of Wakatsuru Shuzo, revived via crowdfunding and a rising cult name for its peated malt.',
 NOW(6), NOW(6)),
('카이쿄 (하토자키)', 'Kaikyo (Hatozaki)', '일본', '효고', 'https://www.kaikyo-distillery.com', 2017,
 '아카시의 신생 증류소. 블렌디드·싱글몰트 ''하토자키''로 국제 시장에서 인기를 얻고 있다.',
 'A new distillery in Akashi gaining international popularity with its "Hatozaki" blended and single malt whiskies.',
 NOW(6), NOW(6)),
('아사카', 'Asaka', '일본', '후쿠시마', 'https://www.sasanokawa.co.jp', 2016,
 '사사노카와 주조가 고리야마에 세운 신생 증류소. 싱글몰트 ''야마자쿠라/아사카''로 알려져 있다.',
 'A new distillery built by Sasanokawa Shuzo in Koriyama, known for its "Yamazakura/Asaka" single malt.',
 NOW(6), NOW(6)),
('나가하마', 'Nagahama', '일본', '시가', 'https://www.nagahama-roman.jp', 2016,
 '일본에서 가장 작은 축에 드는 신생 증류소. 비와 호숫가의 크래프트 몰트로 주목받는다.',
 'One of Japan''s smallest new distilleries, drawing attention for its craft malt by Lake Biwa.',
 NOW(6), NOW(6)),
('시라카와', 'Shirakawa', '일본', '후쿠시마', NULL, 1939,
 '1969년 위스키 생산을 멈춘 환상의 증류소. 2020년 단 한 종의 올드 보틀이 공개돼 화제가 되었다.',
 'A "phantom" distillery that ceased whisky production in 1969; a single old bottling unveiled in 2020 caused a sensation.',
 NOW(6), NOW(6)),
-- ===================== 호주 =====================
('라임버너스', 'Limeburners', '호주', '서오스트레일리아 (앨버니)', 'https://www.distillery.com.au', 2004,
 '서호주 그레이트 서던 디스틸링의 증류소. 호주 싱글몰트의 대표 주자로 다수 수상했다.',
 'The distillery of Great Southern Distilling in Western Australia, a flagship of Australian single malt with many awards.',
 NOW(6), NOW(6)),
('헬리어스 로드', 'Hellyers Road', '호주', '태즈메이니아', 'https://www.hellyersroaddistillery.com.au', 1999,
 '태즈메이니아의 대형 증류소 중 하나. 부드럽고 접근성 좋은 싱글몰트로 사랑받는다.',
 'One of the larger Tasmanian distilleries, beloved for its smooth, approachable single malt.',
 NOW(6), NOW(6)),
('베이커리 힐', 'Bakery Hill', '호주', '멜버른', 'https://www.bakeryhill.com', 1999,
 '멜버른의 선구적 크래프트 증류소. 피티드·논피티드 싱글몰트로 호주 위스키 붐을 이끌었다.',
 'A pioneering Melbourne craft distillery that helped launch the Australian whisky boom with peated and unpeated single malts.',
 NOW(6), NOW(6)),
-- ===================== 잉글랜드 / 유럽 (신생) =====================
('스피릿 오브 요크셔 (파일리 베이)', 'Spirit of Yorkshire', '잉글랜드', '요크셔', 'https://www.spiritofyorkshire.com', 2016,
 '요크셔의 농장 기반 신생 증류소. 싱글몰트 ''파일리 베이''로 빠르게 명성을 얻었다.',
 'A farm-based new distillery in Yorkshire that quickly gained fame with its "Filey Bay" single malt.',
 NOW(6), NOW(6)),
('화이트 피크 (와이어 웍스)', 'White Peak', '잉글랜드', '더비셔', 'https://www.whitepeakdistillery.co.uk', 2018,
 '더비셔 피크 디스트릭트의 신생 증류소. 싱글몰트 ''와이어 웍스''로 주목받는다.',
 'A new distillery in the Derbyshire Peak District, drawing attention with its "Wire Works" single malt.',
 NOW(6), NOW(6)),
('세인트 킬리안', 'St. Kilian', '독일', '바이에른', 'https://www.stkiliandistillers.com', 2016,
 '독일 최대 규모의 위스키 증류소. 스코틀랜드식 설비로 폭넓은 싱글몰트를 만든다.',
 'Germany''s largest whisky distillery, producing a wide range of single malt with Scottish-style equipment.',
 NOW(6), NOW(6)),
('스토닝', 'Stauning', '덴마크', '윌란 (서부)', 'https://www.stauningwhisky.com', 2005,
 '덴마크의 신생 증류소. 플로어 몰팅과 토착 호밀을 사용한 라이·피티드 몰트로 국제적 호평을 받는다.',
 'A new Danish distillery acclaimed internationally for floor-malted, native-rye and peated whiskies.',
 NOW(6), NOW(6)),
('퀴뢰', 'Kyrö', '핀란드', '이소키로', 'https://www.kyrodistillery.com', 2012,
 '핀란드의 신생 증류소. 100% 호밀 몰트 라이 위스키로 유럽에서 인기를 얻고 있다.',
 'A new Finnish distillery gaining European popularity for its 100% malted-rye whisky.',
 NOW(6), NOW(6));


ALTER TABLE producer ALTER COLUMN type DROP DEFAULT;
