-- [클린 베이스라인 변환] 생산자 통합(producer.type) 반영.
--   원본 시드는 type 컬럼이 없어, INSERT 동안만 type 기본값을 'DISTILLERY' 으로 지정한 뒤
--   삽입 종료 후 기본값을 제거한다. (엔티티상 producer.type 은 기본값 없는 NOT NULL)
ALTER TABLE producer ALTER COLUMN type SET DEFAULT 'DISTILLERY';

-- =============================================================================
-- CaskByCask 기초데이터 — 위스키 증류소 (Distillery seed)
-- =============================================================================
-- 작성 기준일: 2026-05-30
-- 범위: 글로벌 종합 — 국가별/지역별로 그룹화하여 정렬 (가동 중 + 폐쇄·폐업 포함)
--
-- [주의]
--   - Flyway 버전 마이그레이션입니다. 한 번 적용된 후에는 이 파일을 수정하지 마세요.
--     (체크섬 검증 실패로 기동이 막힙니다. 보정이 필요하면 V3__*.sql 로 추가하세요.)
--   - country 는 "위스키 분류상 생산국/지역" 기준으로 세분화 표기합니다 (스코틀랜드/아일랜드/미국/일본/대한민국 등).
--     (예: 부시밀스는 지리상 북아일랜드(영국)이나 아이리시 위스키로 분류 → country='아일랜드', region 에 명시)
--   - website 가 확실치 않은 경우 추측 URL 대신 NULL 로 두었습니다. (폐쇄 증류소는 공식 사이트 없음 → NULL)
--   - founded_year 는 증류소(또는 라이선스) 설립 연도 기준이며, 부활/이전 사례는 description 에 보충했습니다.
--   - 운영상태 컬럼이 스키마에 없으므로, 폐쇄·폐업 여부와 폐쇄연도는 description 에 명시했습니다.
--     각 국가/지역 그룹 안에서 가동 중 → 폐쇄 순으로 배치했습니다. (추후 status 컬럼이 필요하면 V3 로 추가 권장)
-- =============================================================================

INSERT INTO producer
    (name_ko, name_en, country, region, website, founded_year, description_ko, description_en, created_at, updated_at)
VALUES
-- =========================== 스코틀랜드 — Speyside ===========================
('맥캘란', 'The Macallan', '스코틀랜드', 'Speyside', 'https://www.themacallan.com', 1824,
 '셰리 오크 숙성으로 유명한 스페이사이드의 프리미엄 싱글몰트. 풍부하고 진한 과실·스파이스 풍미로 세계적 명성을 얻고 있다.',
 'A premium Speyside single malt renowned for its sherry oak maturation, prized worldwide for its rich, fruity and spicy character.',
 NOW(6), NOW(6)),
('글렌피딕', 'Glenfiddich', '스코틀랜드', 'Speyside', 'https://www.glenfiddich.com', 1886,
 '윌리엄 그랜트가 설립한, 전 세계에서 가장 많이 팔리는 싱글몰트 중 하나. 신선한 배·사과 향이 특징이다.',
 'Founded by William Grant, one of the world''s best-selling single malts, characterised by fresh pear and apple notes.',
 NOW(6), NOW(6)),
('글렌리벳', 'The Glenlivet', '스코틀랜드', 'Speyside', 'https://www.theglenlivet.com', 1824,
 '정부 라이선스를 받은 최초의 합법 증류소 중 하나로, 부드럽고 꽃향 가득한 스페이사이드 스타일의 기준이 되는 몰트.',
 'One of the first legally licensed distilleries, setting the benchmark for the smooth, floral Speyside style.',
 NOW(6), NOW(6)),
('발베니', 'The Balvenie', '스코틀랜드', 'Speyside', 'https://www.thebalvenie.com', 1892,
 '글렌피딕 옆에 자리한 자매 증류소. 자체 보리 재배·플로어 몰팅 등 전통 공정을 유지하며 꿀·오크 풍미로 사랑받는다.',
 'A sister distillery beside Glenfiddich that maintains traditional crafts such as floor malting, beloved for its honeyed, oaky flavour.',
 NOW(6), NOW(6)),
('아벨라워', 'Aberlour', '스코틀랜드', 'Speyside', 'https://www.aberlour.com', 1879,
 '셰리·버번 캐스크 더블 숙성으로 유명한 스페이사이드 몰트. 진한 과실과 스파이스의 조화가 특징이다.',
 'A Speyside malt known for double cask maturation in sherry and bourbon wood, marked by rich fruit and spice.',
 NOW(6), NOW(6)),
('글렌파클라스', 'Glenfarclas', '스코틀랜드', 'Speyside', 'https://www.glenfarclas.com', 1836,
 '6대째 그랜트 가문이 운영하는 독립 가족 증류소. 직화 증류와 셰리 캐스크 숙성으로 묵직한 풍미를 낸다.',
 'An independent family distillery run by six generations of the Grant family, producing rich whisky via direct-fired stills and sherry cask maturation.',
 NOW(6), NOW(6)),
('모틀락', 'Mortlach', '스코틀랜드', 'Speyside', NULL, 1823,
 '더프타운 최초의 합법 증류소. 복잡한 2.81회 증류 공정으로 고기향이 도는 묵직한 ''더프타운의 야수''로 불린다.',
 'The first legal distillery in Dufftown, famed for its complex 2.81-times distillation and meaty, robust spirit known as "The Beast of Dufftown".',
 NOW(6), NOW(6)),
('크라간모어', 'Cragganmore', '스코틀랜드', 'Speyside', NULL, 1869,
 '디아지오 클래식 몰트 중 스페이사이드를 대표하는 증류소. 복합적이면서 섬세한 향미로 정평이 나 있다.',
 'The Speyside representative among Diageo''s Classic Malts, esteemed for its complex yet delicate aromatics.',
 NOW(6), NOW(6)),
('글렌 그란트', 'Glen Grant', '스코틀랜드', 'Speyside', 'https://www.glengrant.com', 1840,
 '로시스에 위치한 증류소로 키가 큰 증류기와 정화기를 사용해 가볍고 깨끗한 스타일을 만든다.',
 'A Rothes distillery using tall stills and purifiers to create a light, clean style of malt.',
 NOW(6), NOW(6)),
('벤리악', 'BenRiach', '스코틀랜드', 'Speyside', 'https://www.benriachdistillery.com', 1898,
 '비피티드·피티드 원액과 다양한 캐스크 실험으로 유명한 스페이사이드 증류소.',
 'A Speyside distillery known for both unpeated and peated spirit and adventurous cask experimentation.',
 NOW(6), NOW(6)),
('글렌로시스', 'The Glenrothes', '스코틀랜드', 'Speyside', 'https://www.theglenrothes.com', 1879,
 '셰리 캐스크 숙성에 집중하는 로시스의 증류소. 빈티지 릴리스로도 잘 알려져 있다.',
 'A Rothes distillery focused on sherry cask maturation, also well known for its vintage releases.',
 NOW(6), NOW(6)),
('크레이겔라키', 'Craigellachie', '스코틀랜드', 'Speyside', 'https://www.craigellachie.com', 1891,
 '벌레 응축기(웜텁)를 사용해 유황기 있는 묵직하고 오일리한 구식 스타일을 고수하는 증류소.',
 'A distillery that retains an old-style, sulphurous and oily character by using traditional worm-tub condensers.',
 NOW(6), NOW(6)),
('스트라스아일라', 'Strathisla', '스코틀랜드', 'Speyside', NULL, 1786,
 '하이랜드에서 가장 오래된 가동 증류소 중 하나로, 시바스 리갈 블렌드의 핵심 몰트다.',
 'One of the oldest operating distilleries in the Highlands and the heart malt of the Chivas Regal blend.',
 NOW(6), NOW(6)),
('글렌 모레이', 'Glen Moray', '스코틀랜드', 'Speyside', 'https://www.glenmoray.com', 1897,
 '엘긴에 위치한 가성비 좋은 증류소로 다양한 와인 캐스크 피니시 실험으로도 알려져 있다.',
 'An Elgin distillery offering great value and known for varied wine-cask finishing experiments.',
 NOW(6), NOW(6)),
('벤로막', 'Benromach', '스코틀랜드', 'Speyside', 'https://www.benromach.com', 1898,
 '독립 병입사 고든 앤 맥페일이 운영하는 소규모 증류소. 살짝 피트한 전통 스페이사이드 스타일을 지향한다.',
 'A small distillery run by independent bottler Gordon & MacPhail, aiming for a lightly peated, traditional Speyside style.',
 NOW(6), NOW(6)),
('글렌알라키', 'GlenAllachie', '스코틀랜드', 'Speyside', 'https://www.theglenallachie.com', 1967,
 '2017년 빌리 워커가 인수한 뒤 단숨에 인기 반열에 오른 스페이사이드 증류소. 다양한 캐스크와 고숙성 릴리스로 호평받는다.',
 'A Speyside distillery that surged in popularity after Billy Walker''s 2017 takeover, acclaimed for diverse casks and aged releases.',
 NOW(6), NOW(6)),
('토민토울', 'Tomintoul', '스코틀랜드', 'Speyside', 'https://www.tomintoulwhisky.com', 1964,
 '''부드러운 스페이사이드의 정수''를 표방하는 증류소. 가볍고 꿀 같은 풍미로 접근성이 좋다.',
 'A distillery styling itself "the gentle dram of Speyside," with a light, honeyed and approachable character.',
 NOW(6), NOW(6)),
('탐두', 'Tamdhu', '스코틀랜드', 'Speyside', 'https://www.tamdhu.com', 1897,
 '셰리 캐스크 숙성에만 집중하는 스페이사이드 증류소. 진하고 풍부한 셰리 풍미로 알려져 있다.',
 'A Speyside distillery focused exclusively on sherry cask maturation, known for its rich, full sherried character.',
 NOW(6), NOW(6)),
('카듀', 'Cardhu', '스코틀랜드', 'Speyside', NULL, 1824,
 '조니워커 블렌드의 핵심 몰트. 여성(헬렌 커밍)이 설립한 것으로도 유명하며 부드럽고 깔끔한 스타일을 낸다.',
 'A core malt of the Johnnie Walker blend, famously founded by a woman (Helen Cumming), producing a smooth, clean style.',
 NOW(6), NOW(6)),
('올트모어', 'Aultmore', '스코틀랜드', 'Speyside', 'https://www.aultmore.com', 1896,
 '오랫동안 블렌드용으로만 쓰이다 싱글몰트로 재조명된 증류소. 신선하고 풀향 도는 깔끔한 풍미가 특징이다.',
 'Long used only for blends and later rediscovered as a single malt, with a fresh, grassy and clean character.',
 NOW(6), NOW(6)),
-- Speyside (폐쇄)
('캐퍼도닉', 'Caperdonich', '스코틀랜드', 'Speyside', NULL, 1898,
 '글렌 그란트 제2증류소로 출발한 로시스의 증류소. 2002년 폐쇄되고 이후 철거되어 유령 위스키로 남았다.',
 'A Rothes distillery that began as Glen Grant''s second site; closed in 2002 and later demolished, remaining a ghost whisky.',
 NOW(6), NOW(6)),
('임페리얼', 'Imperial', '스코틀랜드', 'Speyside', NULL, 1897,
 '1998년 폐쇄 후 철거된 스페이사이드 증류소. 부지에는 2015년 달무낙(Dalmunach) 증류소가 새로 들어섰다.',
 'A Speyside distillery closed in 1998 and demolished; the Dalmunach distillery was built on its site in 2015.',
 NOW(6), NOW(6)),
('콘발모어', 'Convalmore', '스코틀랜드', 'Speyside', NULL, 1894,
 '1985년 폐쇄된 더프타운의 증류소. 건물은 윌리엄 그랜트사가 보관 용도로 보유하고 있다.',
 'A Dufftown distillery closed in 1985; its buildings are retained by William Grant & Sons for storage.',
 NOW(6), NOW(6)),
('피티베이크', 'Pittyvaich', '스코틀랜드', 'Speyside', NULL, 1974,
 '1974년 가동해 1993년 폐쇄, 2002년 철거된 단명한 더프타운 증류소.',
 'A short-lived Dufftown distillery commissioned in 1974, closed in 1993 and demolished in 2002.',
 NOW(6), NOW(6)),
('콜번', 'Coleburn', '스코틀랜드', 'Speyside', NULL, 1897,
 '1985년 폐쇄된 스페이사이드 증류소로, 주로 블렌드용 원액을 공급했다.',
 'A Speyside distillery closed in 1985 that mainly supplied malt for blends.',
 NOW(6), NOW(6)),
('댈러스 두', 'Dallas Dhu', '스코틀랜드', 'Speyside', NULL, 1898,
 '1983년 폐쇄된 포레스의 증류소. 현재는 보존되어 위스키 박물관으로 운영된다.',
 'A Forres distillery closed in 1983, now preserved and run as a whisky museum.',
 NOW(6), NOW(6)),
-- =========================== 스코틀랜드 — Highland ===========================
('글렌모렌지', 'Glenmorangie', '스코틀랜드', 'Highland', 'https://www.glenmorangie.com', 1843,
 '스코틀랜드에서 가장 키가 큰 증류기를 사용해 섬세하고 우아한 스타일을 만든다. 다양한 캐스크 피니시의 선구자.',
 'Using the tallest stills in Scotland to craft a delicate, elegant style; a pioneer of cask finishing.',
 NOW(6), NOW(6)),
('달모어', 'The Dalmore', '스코틀랜드', 'Highland', 'https://www.thedalmore.com', 1839,
 '수사슴 엠블럼으로 유명한 노던 하이랜드 증류소. 셰리 캐스크 숙성의 진하고 풍부한 풍미가 특징이다.',
 'A Northern Highland distillery famed for its stag emblem, known for rich, full-bodied sherry-cask-matured whisky.',
 NOW(6), NOW(6)),
('오반', 'Oban', '스코틀랜드', 'Highland', NULL, 1794,
 '서부 해안 도시 오반에 위치한 소형 증류소. 하이랜드와 섬 위스키 사이의 가벼운 스모키·해풍 풍미를 낸다.',
 'A small distillery in the West Coast town of Oban, producing a lightly smoky, maritime style between Highland and Island whisky.',
 NOW(6), NOW(6)),
('글렌고인', 'Glengoyne', '스코틀랜드', 'Highland', 'https://www.glengoyne.com', 1833,
 '피트를 전혀 쓰지 않고 천천히 증류하는 것으로 유명한 하이랜드 경계의 증류소.',
 'A distillery on the Highland line famed for using no peat at all and for its exceptionally slow distillation.',
 NOW(6), NOW(6)),
('아벨펠디', 'Aberfeldy', '스코틀랜드', 'Highland', 'https://www.aberfeldy.com', 1896,
 '듀어스 블렌드의 핵심 몰트. 꿀처럼 달콤한 풍미로 ''황금빛 드램''이라 불린다.',
 'The heart malt of the Dewar''s blend, dubbed the "Golden Dram" for its honeyed sweetness.',
 NOW(6), NOW(6)),
('달위니', 'Dalwhinnie', '스코틀랜드', 'Highland', NULL, 1897,
 '스코틀랜드에서 가장 높고 추운 곳에 위치한 증류소 중 하나. 부드러운 꿀·헤더 풍미가 특징이다.',
 'One of the highest and coldest distilleries in Scotland, characterised by gentle honey and heather notes.',
 NOW(6), NOW(6)),
('올드 풀트니', 'Old Pulteney', '스코틀랜드', 'Highland', 'https://www.oldpulteney.com', 1826,
 '북부 해안 도시 위크에 위치한 ''바다의 몰트''. 해풍을 머금은 짭조름한 풍미로 알려져 있다.',
 'The "Maritime Malt" from the northern coastal town of Wick, known for its salty, sea-influenced character.',
 NOW(6), NOW(6)),
('클라이넬리시', 'Clynelish', '스코틀랜드', 'Highland', NULL, 1967,
 '왁스 같은 독특한 질감으로 유명한 노던 하이랜드 증류소. 조니워커 블렌드의 핵심 몰트이기도 하다.',
 'A Northern Highland distillery famed for its distinctive waxy texture and a key malt in the Johnnie Walker blend.',
 NOW(6), NOW(6)),
('발블레어', 'Balblair', '스코틀랜드', 'Highland', 'https://www.balblair.com', 1790,
 '스코틀랜드에서 가장 오래된 가동 증류소 중 하나로, 빈티지 릴리스 전략으로 잘 알려져 있다.',
 'One of the oldest operating distilleries in Scotland, well known for its vintage-led release strategy.',
 NOW(6), NOW(6)),
('글렌 오드', 'Glen Ord', '스코틀랜드', 'Highland', NULL, 1838,
 '싱글톤 브랜드로도 출시되는 노던 하이랜드 증류소. 진한 몰트·과실 풍미가 특징이다.',
 'A Northern Highland distillery also released as The Singleton, noted for rich malty, fruity flavours.',
 NOW(6), NOW(6)),
('에드라두어', 'Edradour', '스코틀랜드', 'Highland', 'https://www.edradour.com', 1825,
 '오랫동안 스코틀랜드에서 가장 작은 증류소로 불려온 수공예 증류소. 진하고 오일리한 풍미를 낸다.',
 'Long regarded as one of Scotland''s smallest distilleries, a hands-on craft operation producing rich, oily spirit.',
 NOW(6), NOW(6)),
('토마틴', 'Tomatin', '스코틀랜드', 'Highland', 'https://www.tomatin.com', 1897,
 '한때 스코틀랜드 최대 규모였던 하이랜드 증류소. 부드럽고 접근성 좋은 스타일로 가성비가 뛰어나다.',
 'A Highland distillery once the largest in Scotland, offering a smooth, approachable and great-value style.',
 NOW(6), NOW(6)),
('로열 로크나가', 'Royal Lochnagar', '스코틀랜드', 'Highland', NULL, 1845,
 '밸모럴 성 인근에 위치해 ''로열'' 칭호를 받은 소규모 증류소. 묵직하고 셰리한 풍미를 낸다.',
 'A small distillery near Balmoral Castle granted a "Royal" warrant, producing a robust, sherried style.',
 NOW(6), NOW(6)),
('아녹', 'anCnoc (Knockdhu)', '스코틀랜드', 'Highland', 'https://www.ancnoc.com', 1894,
 '녹두(Knockdhu) 증류소에서 생산하며, 다른 브랜드와 혼동을 피하려 ''anCnoc''이라는 이름으로 출시한다.',
 'Produced at the Knockdhu distillery and bottled as "anCnoc" to avoid confusion with other brands.',
 NOW(6), NOW(6)),
('글렌터렛', 'The Glenturret', '스코틀랜드', 'Highland', 'https://www.theglenturret.com', 1763,
 '1763년 기원을 주장하는, 스코틀랜드에서 가장 오래된 가동 증류소 중 하나. 전통 수공예 방식을 고수한다.',
 'Claiming origins in 1763, one of the oldest working distilleries in Scotland, retaining traditional hands-on methods.',
 NOW(6), NOW(6)),
('로크 로몬드', 'Loch Lomond', '스코틀랜드', 'Highland', 'https://www.lochlomondwhiskies.com', 1964,
 '직선형·전통형 증류기를 모두 갖춰 다양한 스타일을 생산하는 대형 증류소. 디 오픈 골프 공식 위스키로도 유명하다.',
 'A large distillery with both straight-neck and traditional stills producing varied styles, also famed as the official whisky of The Open.',
 NOW(6), NOW(6)),
('딘스톤', 'Deanston', '스코틀랜드', 'Highland', 'https://www.deanstonmalt.com', 1965,
 '옛 면방직 공장을 개조한 증류소로 자체 수력 발전을 사용한다. 비냉각여과·천연 색의 몰트로 알려져 있다.',
 'A distillery converted from a former cotton mill and powered by its own hydro-electricity, known for non-chill-filtered, natural-colour malt.',
 NOW(6), NOW(6)),
('페터케언', 'Fettercairn', '스코틀랜드', 'Highland', 'https://www.fettercairnwhisky.com', 1824,
 '증류기 목에 찬물을 흘려보내는 독특한 냉각 기법을 쓰는 동부 하이랜드 증류소.',
 'An eastern Highland distillery using a unique technique of running cool water over the still necks during distillation.',
 NOW(6), NOW(6)),
('툴리바딘', 'Tullibardine', '스코틀랜드', 'Highland', 'https://www.tullibardine.com', 1949,
 '퍼스셔에 위치한 증류소로 다양한 와인·셰리 캐스크 피니시 릴리스를 선보인다.',
 'A Perthshire distillery offering a range of releases finished in various wine and sherry casks.',
 NOW(6), NOW(6)),
('아드나머칸', 'Ardnamurchan', '스코틀랜드', 'Highland', 'https://www.ardnamurchandistillery.com', 2014,
 '독립 병입사 아델피가 외딴 아드나머칸 반도에 세운 친환경 증류소. 피티드·비피티드 원액을 함께 생산한다.',
 'An eco-friendly distillery built by independent bottler Adelphi on the remote Ardnamurchan peninsula, making both peated and unpeated spirit.',
 NOW(6), NOW(6)),
('울프번', 'Wolfburn', '스코틀랜드', 'Highland', 'https://www.wolfburn.com', 2013,
 '스코틀랜드 본토 최북단의 소규모 증류소. 19세기 옛 증류소 이름을 이어받아 2013년 새로 가동했다.',
 'A small distillery on the northernmost part of the Scottish mainland, revived in 2013 reusing the name of a 19th-century distillery.',
 NOW(6), NOW(6)),
('눅니안', 'Nc''nean', '스코틀랜드', 'Highland', 'https://www.ncnean.com', 2017,
 '유기농 보리와 100% 재생에너지를 사용하는 지속가능성 중심의 신생 증류소.',
 'A new sustainability-focused distillery using organic barley and 100% renewable energy.',
 NOW(6), NOW(6)),
-- Highland (폐쇄)
('브로라', 'Brora', '스코틀랜드', 'Highland', NULL, 1819,
 '구 클라이넬리시로 출발해 1983년 폐쇄된 노던 하이랜드의 명문 증류소. 2021년 디아지오가 복원·재가동했다.',
 'A celebrated Northern Highland distillery (originally the old Clynelish) closed in 1983 and restored and reopened by Diageo in 2021.',
 NOW(6), NOW(6)),
('글렌 모어', 'Glen Mhor', '스코틀랜드', 'Highland', NULL, 1892,
 '인버네스에 있던 증류소. 1983년 폐쇄 후 철거되어 그 자리에 상업시설이 들어섰다.',
 'An Inverness distillery closed in 1983 and demolished, replaced by a retail development.',
 NOW(6), NOW(6)),
('밀번', 'Millburn', '스코틀랜드', 'Highland', NULL, 1807,
 '인버네스의 가장 오래된 증류소 중 하나. 1985년 폐쇄되었고 건물은 현재 레스토랑으로 쓰인다.',
 'One of Inverness''s oldest distilleries, closed in 1985; its building now houses a restaurant.',
 NOW(6), NOW(6)),
('밴프', 'Banff', '스코틀랜드', 'Highland', NULL, 1863,
 '밴프셔 해안의 증류소. 화재·폭발 등 사고로 유명했으며 1983년 폐쇄 후 철거되었다.',
 'A Banffshire coastal distillery notorious for fires and explosions, closed in 1983 and demolished.',
 NOW(6), NOW(6)),
('글렌유기', 'Glenugie', '스코틀랜드', 'Highland', NULL, 1834,
 '피터헤드에 있던 스코틀랜드 본토 최동단 증류소. 1983년 폐쇄되었다.',
 'A Peterhead distillery, the easternmost on the Scottish mainland, closed in 1983.',
 NOW(6), NOW(6)),
('글렌로키', 'Glenlochy', '스코틀랜드', 'Highland', NULL, 1898,
 '포트 윌리엄에 있던 증류소. 1983년 폐쇄되어 대부분 철거되었다.',
 'A Fort William distillery closed in 1983 and largely demolished.',
 NOW(6), NOW(6)),
('글렌유리 로열', 'Glenury Royal', '스코틀랜드', 'Highland', NULL, 1825,
 '스톤헤이븐에 있던 ''로열'' 칭호의 증류소. 1985년 폐쇄되었다.',
 'A "Royal"-titled distillery at Stonehaven, closed in 1985.',
 NOW(6), NOW(6)),
('록사이드', 'Lochside', '스코틀랜드', 'Highland', NULL, 1957,
 '몬트로즈의 옛 양조장 부지에 세워진 증류소. 1992년 폐쇄, 2005년 철거되었다.',
 'A Montrose distillery built on a former brewery site, closed in 1992 and demolished in 2005.',
 NOW(6), NOW(6)),
('노스 포트', 'North Port', '스코틀랜드', 'Highland', NULL, 1820,
 '브레친(Brechin)에 있던 증류소로 ''브레친''이라는 이름으로도 출시되었다. 1983년 폐쇄·철거되었다.',
 'A Brechin distillery also bottled under the name "Brechin," closed and demolished in 1983.',
 NOW(6), NOW(6)),
-- =========================== 스코틀랜드 — Islay ===========================
('아드벡', 'Ardbeg', '스코틀랜드', 'Islay', 'https://www.ardbeg.com', 1815,
 '강렬한 피트와 스모키함으로 컬트적 인기를 누리는 아일라 증류소. 복합적이면서 균형 잡힌 피트 몰트의 정석.',
 'An Islay distillery with a cult following for its intense peat and smoke, a benchmark for complex yet balanced peated malt.',
 NOW(6), NOW(6)),
('라가불린', 'Lagavulin', '스코틀랜드', 'Islay', NULL, 1816,
 '깊고 묵직한 피트·해조류 풍미의 16년이 대표작인 아일라의 클래식 증류소.',
 'A classic Islay distillery whose 16-year-old, with deep peat and seaweed notes, is its flagship.',
 NOW(6), NOW(6)),
('라프로익', 'Laphroaig', '스코틀랜드', 'Islay', 'https://www.laphroaig.com', 1815,
 '요오드·소독약을 연상시키는 강렬한 메디시널 피트 풍미로 호불호가 갈리는 아일라의 상징적 증류소.',
 'An iconic Islay distillery polarising drinkers with its intense medicinal peat reminiscent of iodine and antiseptic.',
 NOW(6), NOW(6)),
('보모어', 'Bowmore', '스코틀랜드', 'Islay', 'https://www.bowmore.com', 1779,
 '아일라에서 가장 오래된 증류소. 피트 스모크와 트로피컬 과실, 바닷내음이 어우러진 균형감이 특징이다.',
 'The oldest distillery on Islay, balancing peat smoke with tropical fruit and a salty sea breeze.',
 NOW(6), NOW(6)),
('브룩라디', 'Bruichladdich', '스코틀랜드', 'Islay', 'https://www.bruichladdich.com', 1881,
 '테루아와 비피티드 라디·강피트 옥토모어 등 다양한 라인업을 선보이는 진보적 아일라 증류소.',
 'A progressive Islay distillery championing terroir, with lines ranging from unpeated Laddie to heavily peated Octomore.',
 NOW(6), NOW(6)),
('부나하벤', 'Bunnahabhain', '스코틀랜드', 'Islay', 'https://www.bunnahabhain.com', 1881,
 '대체로 비피티드 스타일을 추구하는 아일라 북동부 증류소. 셰리 캐스크 숙성과 부드러운 풍미로 알려져 있다.',
 'A north-eastern Islay distillery largely producing an unpeated style, known for sherry cask maturation and a soft character.',
 NOW(6), NOW(6)),
('카올 일라', 'Caol Ila', '스코틀랜드', 'Islay', NULL, 1846,
 '아일라 최대 생산량을 자랑하는 증류소로 조니워커 블렌드의 핵심. 깔끔하고 오일리한 스모키 풍미가 특징이다.',
 'Islay''s largest distillery by output and a core of the Johnnie Walker blend, with a clean, oily, smoky character.',
 NOW(6), NOW(6)),
('킬호만', 'Kilchoman', '스코틀랜드', 'Islay', 'https://www.kilchomandistillery.com', 2005,
 '124년 만에 아일라에 새로 생긴 농장형 증류소. 보리 재배부터 병입까지 모든 과정을 섬에서 진행한다.',
 'A farm distillery, the first new one on Islay in 124 years, carrying out everything from barley growing to bottling on the island.',
 NOW(6), NOW(6)),
('아드나호', 'Ardnahoe', '스코틀랜드', 'Islay', 'https://www.ardnahoedistillery.com', 2018,
 '아일라에서 가장 최근에 가동을 시작한 증류소 중 하나. 웜텁 응축기를 사용한 피트 몰트를 생산한다.',
 'One of the most recently commissioned distilleries on Islay, producing peated malt using worm-tub condensers.',
 NOW(6), NOW(6)),
-- Islay (폐쇄)
('포트 엘렌', 'Port Ellen', '스코틀랜드', 'Islay', NULL, 1825,
 '1983년 폐쇄된 아일라의 전설적 증류소. 희소성으로 수집가들에게 ''유령 위스키''의 대명사였으며, 2024년 디아지오가 재가동했다.',
 'A legendary Islay distillery closed in 1983, the archetypal collectors'' "ghost whisky," reopened by Diageo in 2024.',
 NOW(6), NOW(6)),
-- =========================== 스코틀랜드 — Islands(섬) ===========================
('탈리스커', 'Talisker', '스코틀랜드', 'Isle of Skye', NULL, 1830,
 '스카이 섬의 유일한 클래식 증류소. 후추 같은 매콤함과 해풍·스모크가 어우러진 강렬한 풍미로 유명하다.',
 'The classic distillery of the Isle of Skye, famed for a powerful style combining peppery heat with sea spray and smoke.',
 NOW(6), NOW(6)),
('토라베이그', 'Torabhaig', '스코틀랜드', 'Isle of Skye', 'https://www.torabhaig.com', 2017,
 '탈리스커에 이은 스카이 섬의 두 번째 증류소. 피티드 싱글몰트에 집중한다.',
 'The second distillery on the Isle of Skye after Talisker, focusing on peated single malt.',
 NOW(6), NOW(6)),
('하이랜드 파크', 'Highland Park', '스코틀랜드', 'Orkney', 'https://www.highlandparkwhisky.com', 1798,
 '스코틀랜드 최북단 오크니 제도의 증류소. 헤더 피트와 셰리 캐스크가 어우러진 균형 잡힌 풍미가 특징이다.',
 'A distillery on the far-northern Orkney Islands, balancing heather peat with sherry-cask maturation.',
 NOW(6), NOW(6)),
('아일 오브 주라', 'Isle of Jura', '스코틀랜드', 'Isle of Jura', 'https://www.jurawhisky.com', 1810,
 '아일라 이웃 섬 주라의 유일한 증류소. 비교적 가볍고 접근성 좋은 스타일을 낸다.',
 'The only distillery on Jura, the island neighbouring Islay, producing a relatively light and approachable style.',
 NOW(6), NOW(6)),
('아란', 'Arran', '스코틀랜드', 'Isle of Arran', 'https://www.arranwhisky.com', 1995,
 '아란 섬에 들어선 현대적 증류소. 깨끗하고 과실미 가득한 스타일과 피트 라인(로흐란자)을 함께 선보인다.',
 'A modern distillery on the Isle of Arran offering a clean, fruity style alongside a peated line.',
 NOW(6), NOW(6)),
('라그', 'Lagg', '스코틀랜드', 'Isle of Arran', 'https://www.laggwhisky.com', 2019,
 '아란 섬 남부에 세워진 아란 증류소의 자매 증류소. 강하게 피트한 스타일을 전문으로 한다.',
 'A sister distillery to Arran built on the south of the island, specialising in a heavily peated style.',
 NOW(6), NOW(6)),
('토버모리', 'Tobermory', '스코틀랜드', 'Isle of Mull', 'https://www.tobermorydistillery.com', 1798,
 '멀 섬의 유일한 증류소. 비피티드 토버모리와 피티드 레칙(Ledaig) 두 가지 스타일을 생산한다.',
 'The only distillery on the Isle of Mull, producing unpeated Tobermory and peated Ledaig.',
 NOW(6), NOW(6)),
('아일 오브 라세이', 'Isle of Raasay', '스코틀랜드', 'Isle of Raasay', 'https://www.raasaydistillery.com', 2017,
 '스카이 인근 라세이 섬 최초의 합법 증류소. 피티드·비피티드 원액을 블렌딩한 스타일을 낸다.',
 'The first legal distillery on the Isle of Raasay near Skye, producing a style blending peated and unpeated spirit.',
 NOW(6), NOW(6)),
-- =========================== 스코틀랜드 — Lowland ===========================
('오큰토션', 'Auchentoshan', '스코틀랜드', 'Lowland', 'https://www.auchentoshan.com', 1823,
 '전통적인 로우랜드 3회 증류를 고수하는 증류소. 가볍고 부드러운 스타일로 입문용으로도 인기가 높다.',
 'A distillery that retains the traditional Lowland triple distillation, producing a light, smooth and approachable style.',
 NOW(6), NOW(6)),
('글렌킨치', 'Glenkinchie', '스코틀랜드', 'Lowland', NULL, 1837,
 '에든버러 인근의 로우랜드 클래식 몰트. 가볍고 꽃향 가득한 스타일을 낸다.',
 'A Lowland Classic Malt near Edinburgh, producing a light, floral style.',
 NOW(6), NOW(6)),
('블라드녹', 'Bladnoch', '스코틀랜드', 'Lowland', 'https://www.bladnoch.com', 1817,
 '스코틀랜드 최남단 증류소 중 하나. 오랜 휴면을 거쳐 부활했으며 신선하고 시트러스한 풍미가 특징이다.',
 'One of the southernmost distilleries in Scotland, revived after long dormancy, with fresh, citrusy character.',
 NOW(6), NOW(6)),
('대프트밀', 'Daftmill', '스코틀랜드', 'Lowland', 'https://www.daftmill.com', 2005,
 '파이프의 농장에서 운영되는 초소형 증류소. 농번기 외 시간에만 증류하는 ''계절 증류'' 방식으로 소량 생산한다.',
 'A tiny farm distillery in Fife producing small batches via "seasonal distillation," operating only outside the busy farming periods.',
 NOW(6), NOW(6)),
('킹스반스', 'Kingsbarns', '스코틀랜드', 'Lowland', 'https://www.kingsbarnsdistillery.com', 2014,
 '파이프의 옛 농장 건물을 개조한 로우랜드 증류소. 가볍고 과실미 가득한 스타일을 추구한다.',
 'A Lowland distillery converted from an old farm steading in Fife, aiming for a light, fruity style.',
 NOW(6), NOW(6)),
('린도어스 애비', 'Lindores Abbey', '스코틀랜드', 'Lowland', 'https://www.lindoresabbeydistillery.com', 2017,
 '1494년 위스키 증류 최초 문헌 기록이 남은 수도원 부지에 세워진 증류소. ''스카치의 정신적 고향''을 표방한다.',
 'A distillery built on the abbey site linked to the earliest 1494 written record of whisky distilling, styling itself the "spiritual home of Scotch".',
 NOW(6), NOW(6)),
('글래스고', 'The Glasgow Distillery', '스코틀랜드', 'Lowland', 'https://www.glasgowdistillery.com', 2014,
 '한 세기 만에 글래스고에 다시 생긴 몰트 증류소. ''1770'' 싱글몰트 브랜드로 알려져 있다.',
 'The first malt distillery to open in Glasgow in a century, known for its "1770" single malt brand.',
 NOW(6), NOW(6)),
('애넌데일', 'Annandale', '스코틀랜드', 'Lowland', 'https://www.annandaledistillery.com', 2014,
 '1836년 설립 후 폐쇄되었다가 2014년 복원·재가동한 로우랜드 증류소. 피티드(맨 오 소드)·비피티드(맨 오 워즈)를 함께 만든다.',
 'A Lowland distillery founded in 1836, closed, then restored and reopened in 2014, making both peated (Man O''Sword) and unpeated (Man O''Words).',
 NOW(6), NOW(6)),
('클라이드사이드', 'The Clydeside', '스코틀랜드', 'Lowland', 'https://www.theclydeside.com', 2017,
 '글래스고 클라이드강 변 옛 항만 펌프하우스에 자리한 도심 증류소.',
 'An urban distillery housed in a former dockside pump house on the banks of the Clyde in Glasgow.',
 NOW(6), NOW(6)),
-- Lowland (폐쇄)
('로즈뱅크', 'Rosebank', '스코틀랜드', 'Lowland', 'https://www.rosebank.com', 1840,
 '''로우랜드의 제왕''으로 불린 3회 증류 증류소. 1993년 폐쇄되었다가 이안 맥레오드가 2023년 재가동했다.',
 'A triple-distilled distillery dubbed "The King of the Lowlands," closed in 1993 and reopened by Ian Macleod in 2023.',
 NOW(6), NOW(6)),
('리틀밀', 'Littlemill', '스코틀랜드', 'Lowland', NULL, 1772,
 '스코틀랜드에서 가장 오래된 증류소 중 하나로 꼽히던 로우랜드 증류소. 1994년 폐쇄, 2004년 화재로 소실되었다.',
 'A Lowland distillery regarded as one of Scotland''s oldest; closed in 1994 and destroyed by fire in 2004.',
 NOW(6), NOW(6)),
('세인트 막달레네', 'St. Magdalene', '스코틀랜드', 'Lowland', NULL, 1798,
 '린리스고(Linlithgow)에 있던 로우랜드 증류소. 1983년 폐쇄되어 일부는 주거시설로 전환되었다.',
 'A Lowland distillery at Linlithgow, closed in 1983 with parts converted into housing.',
 NOW(6), NOW(6)),
('인버레븐', 'Inverleven', '스코틀랜드', 'Lowland', NULL, 1938,
 '덤바턴 그레인 단지 내에 있던 로우랜드 몰트 증류소. 1991년 폐쇄되었다.',
 'A Lowland malt distillery within the Dumbarton grain complex, closed in 1991.',
 NOW(6), NOW(6)),
-- =========================== 스코틀랜드 — Campbeltown ===========================
('스프링뱅크', 'Springbank', '스코틀랜드', 'Campbeltown', 'https://springbank.scot', 1828,
 '모든 공정을 자체적으로 수행하는 캠벨타운의 가족 증류소. 컬트적 인기를 누리며 비피티드 헤이즐번·강피트 롱로우도 생산한다.',
 'A family-owned Campbeltown distillery performing every process in-house, with a cult following and also making Hazelburn and Longrow.',
 NOW(6), NOW(6)),
('글렌 스코시아', 'Glen Scotia', '스코틀랜드', 'Campbeltown', 'https://www.glenscotia.com', 1832,
 '캠벨타운에 남은 세 증류소 중 하나. 짭조름한 해풍과 묵직한 풍미의 전통 캠벨타운 스타일을 낸다.',
 'One of the three remaining Campbeltown distilleries, producing the traditional salty, robust Campbeltown style.',
 NOW(6), NOW(6)),
('글렌가일', 'Glengyle (Kilkerran)', '스코틀랜드', 'Campbeltown', 'https://kilkerran.scot', 1872,
 '1872년 설립 후 폐쇄되었다가 2004년 부활한 증류소. 상표 문제로 위스키는 킬커란(Kilkerran)이라는 이름으로 출시된다.',
 'Founded in 1872, closed, then revived in 2004; due to a trademark issue its whisky is released under the name Kilkerran.',
 NOW(6), NOW(6)),
-- =========================== 아일랜드 (아이리시 위스키) ===========================
('부시밀스', 'Bushmills', '아일랜드', '북아일랜드 (앤트림)', 'https://www.bushmills.com', 1608,
 '1608년 증류 라이선스를 받은, 세계에서 가장 오래된 라이선스 증류소. 지리적으로는 북아일랜드(영국)에 위치한다.',
 'Holder of a 1608 distilling licence and regarded as the oldest licensed distillery in the world; located in Northern Ireland (UK).',
 NOW(6), NOW(6)),
('미들턴', 'Midleton', '아일랜드', '코크', 'https://www.jamesonwhiskey.com', 1825,
 '제임슨·레드브레스트·파워스 등을 생산하는 아일랜드 최대 증류소. 아이리시 위스키의 핵심 생산 거점이다.',
 'Ireland''s largest distillery, producing Jameson, Redbreast and Powers; the heart of Irish whiskey production.',
 NOW(6), NOW(6)),
('틸링', 'Teeling', '아일랜드', '더블린', 'https://www.teelingdistillery.com', 2015,
 '125년 만에 더블린 시내에 새로 문을 연 증류소. 도시 증류 전통을 부활시킨 상징적 존재다.',
 'The first new distillery to open in Dublin city in 125 years, symbolically reviving the city''s distilling tradition.',
 NOW(6), NOW(6)),
('틀라모어', 'Tullamore Distillery', '아일랜드', '오펄리 (틀라모어)', 'https://www.tullamoredew.com', 1829,
 '틀라모어 듀 브랜드의 본고장. 삼중 증류·삼중 블렌드(몰트·그레인·팟스틸) 스타일로 알려져 있다.',
 'Home of the Tullamore D.E.W. brand, known for triple distillation and a triple-blend of malt, grain and pot still whiskey.',
 NOW(6), NOW(6)),
('쿨리', 'Cooley', '아일랜드', '라우스', 'https://www.kilbeggandistillery.com', 1987,
 '코너마라(피티드)·킬베간·티르코넬 등 다양한 아이리시 위스키를 생산하는 증류소.',
 'A distillery producing a range of Irish whiskeys including the peated Connemara, Kilbeggan and Tyrconnell.',
 NOW(6), NOW(6)),
('딩글', 'Dingle', '아일랜드', '케리 (딩글)', 'https://www.dingledistillery.ie', 2012,
 '아일랜드 크래프트 증류 부흥을 이끈 독립 소규모 증류소.',
 'An independent small-batch distillery that helped lead the revival of Irish craft distilling.',
 NOW(6), NOW(6)),
('워터포드', 'Waterford', '아일랜드', '워터포드', 'https://www.waterfordwhisky.com', 2015,
 '브룩라디 출신 마크 레이니어가 설립. 보리 산지별 테루아를 추구하는 실험적 증류소다.',
 'Founded by ex-Bruichladdich''s Mark Reynier, an experimental distillery pursuing barley terroir by farm.',
 NOW(6), NOW(6)),
('슬레인', 'Slane', '아일랜드', '미스 (슬레인)', 'https://www.slaneirishwhiskey.com', 2017,
 '슬레인 성 부지에 자리한 증류소. 세 가지 캐스크를 블렌딩하는 트리플 캐스크 스타일로 알려져 있다.',
 'A distillery on the grounds of Slane Castle, known for its triple-casked blending style.',
 NOW(6), NOW(6)),
('그레이트 노던', 'Great Northern Distillery', '아일랜드', '라우스 (던도크)', 'https://www.gndireland.com', 2015,
 '쿨리 설립자 존 틸링이 옛 양조장 부지에 세운 대형 증류소. 다양한 아이리시 위스키를 독립 브랜드에 공급한다.',
 'A large distillery built on a former brewery site by Cooley founder John Teeling, supplying varied Irish whiskey to independent brands.',
 NOW(6), NOW(6)),
-- =========================== 미국 (버번 / 테네시 / 라이) ===========================
('짐 빔', 'Jim Beam', '미국', '켄터키', 'https://www.jimbeam.com', 1795,
 '7대째 빔 가문이 이어온, 세계에서 가장 많이 팔리는 버번 중 하나.',
 'Carried on by seven generations of the Beam family, one of the best-selling bourbons in the world.',
 NOW(6), NOW(6)),
('메이커스 마크', 'Maker''s Mark', '미국', '켄터키', 'https://www.makersmark.com', 1953,
 '겨울밀(wheated)을 사용해 부드러운 버번을 만드는 증류소. 손으로 담근 붉은 왁스 봉인이 트레이드마크다.',
 'A distillery making soft, wheated bourbon, instantly recognisable by its hand-dipped red wax seal.',
 NOW(6), NOW(6)),
('와일드 터키', 'Wild Turkey', '미국', '켄터키', 'https://www.wildturkeybourbon.com', 1869,
 '높은 도수와 진한 풍미로 유명한 버번 증류소. 전설적 마스터 디스틸러 지미 러셀로 잘 알려져 있다.',
 'A bourbon distillery famed for high-proof, full-flavoured whiskey and its legendary master distiller Jimmy Russell.',
 NOW(6), NOW(6)),
('버팔로 트레이스', 'Buffalo Trace', '미국', '켄터키', 'https://www.buffalotracedistillery.com', 1773,
 '미국에서 가장 오래 연속 가동된 증류소 중 하나. 패피 반 윙클·이글 레어 등 명품 버번을 생산한다.',
 'One of the longest continuously operating distilleries in the US, producing prized bourbons like Pappy Van Winkle and Eagle Rare.',
 NOW(6), NOW(6)),
('우드포드 리저브', 'Woodford Reserve', '미국', '켄터키', 'https://www.woodfordreserve.com', 1812,
 '구리 단식 증류기를 사용하는 소규모 프리미엄 버번 증류소. 켄터키 더비 공식 버번으로도 유명하다.',
 'A small-batch premium bourbon distillery using copper pot stills, also famed as the official bourbon of the Kentucky Derby.',
 NOW(6), NOW(6)),
('포 로지스', 'Four Roses', '미국', '켄터키', 'https://www.fourrosesbourbon.com', 1888,
 '두 종의 매시빌과 다섯 종의 효모를 조합해 10가지 레시피를 만드는 독특한 버번 증류소.',
 'A bourbon distillery uniquely combining two mash bills and five yeast strains to create ten distinct recipes.',
 NOW(6), NOW(6)),
('헤븐 힐', 'Heaven Hill', '미국', '켄터키', 'https://www.heavenhill.com', 1935,
 '미국 최대의 독립 가족 소유 증류·병입 회사. 에반 윌리엄스·엘리야 크레이그 등을 생산한다.',
 'The largest independent, family-owned distilled spirits producer in the US, making Evan Williams and Elijah Craig.',
 NOW(6), NOW(6)),
('올드 포레스터', 'Old Forester', '미국', '켄터키', 'https://www.oldforester.com', 1870,
 '최초로 병입 판매된 버번으로 알려진 브랜드. 금주법 시대에도 합법적으로 생산을 이어갔다.',
 'Known as the first bourbon sold exclusively in sealed bottles, and one that legally continued production through Prohibition.',
 NOW(6), NOW(6)),
('잭 다니엘스', 'Jack Daniel''s', '미국', '테네시', 'https://www.jackdaniels.com', 1866,
 '숯으로 여과하는 ''링컨 카운티 프로세스''를 거치는 테네시 위스키의 대표 주자.',
 'The flagship Tennessee whiskey, charcoal-mellowed through the "Lincoln County Process".',
 NOW(6), NOW(6)),
('조지 디켈', 'George Dickel', '미국', '테네시', 'https://www.georgedickel.com', 1870,
 '차가운 숯 여과를 거치는 테네시 위스키 증류소. 잭 다니엘스와 함께 테네시 스타일을 대표한다.',
 'A Tennessee whiskey distillery using chilled charcoal mellowing, representing the Tennessee style alongside Jack Daniel''s.',
 NOW(6), NOW(6)),
('윌렛', 'Willett', '미국', '켄터키', 'https://www.willettdistillery.com', 1936,
 '바즈타운의 가족 소유 증류소. 독특한 호리병 모양 병의 ''패밀리 이스테이트'' 버번·라이로 유명하다.',
 'A family-owned Bardstown distillery famed for its "Family Estate" bourbon and rye in distinctive pot-shaped bottles.',
 NOW(6), NOW(6)),
('믹터스', 'Michter''s', '미국', '켄터키', 'https://www.michters.com', 1753,
 '1753년 펜실베이니아 기원을 주장하는 유서 깊은 브랜드. 1990년대 켄터키에서 부활해 루이빌에서 프리미엄 버번·라이를 생산한다.',
 'A heritage brand claiming 1753 Pennsylvania origins, revived in Kentucky in the 1990s and now producing premium bourbon and rye in Louisville.',
 NOW(6), NOW(6)),
('휘슬피그', 'WhistlePig', '미국', '버몬트', 'https://www.whistlepigwhiskey.com', 2007,
 '버몬트 농장에 자리한 라이 위스키 전문 증류소. 고숙성 라이로 미국 라이 위스키 붐을 이끌었다.',
 'A rye-focused distillery on a Vermont farm that helped lead the American rye whiskey boom with its aged ryes.',
 NOW(6), NOW(6)),
('하이 웨스트', 'High West', '미국', '유타', 'https://www.highwest.com', 2006,
 '금주법 이후 유타 최초의 합법 증류소. 다양한 원액을 블렌딩하는 방식으로 명성을 얻었다.',
 'The first legal distillery in Utah since Prohibition, renowned for its art of blending sourced and own-made whiskeys.',
 NOW(6), NOW(6)),
('발코네스', 'Balcones', '미국', '텍사스', 'https://www.balconesdistilling.com', 2008,
 '텍사스 웨이코의 크래프트 증류소. 블루 콘(옥수수)을 사용한 독특한 싱글몰트·버번으로 주목받는다.',
 'A craft distillery in Waco, Texas, noted for distinctive single malts and bourbons made with blue corn.',
 NOW(6), NOW(6)),
('스트라나한스', 'Stranahan''s', '미국', '콜로라도', 'https://www.stranahans.com', 2004,
 '로키산맥 물을 사용하는 콜로라도 덴버의 아메리칸 싱글몰트 선구 증류소.',
 'A pioneering American single malt distillery in Denver, Colorado, using Rocky Mountain water.',
 NOW(6), NOW(6)),
('웨스트랜드', 'Westland', '미국', '워싱턴', 'https://www.westlanddistillery.com', 2010,
 '태평양 북서부 테루아를 강조하는 시애틀의 아메리칸 싱글몰트 증류소.',
 'A Seattle American single malt distillery emphasising Pacific Northwest terroir.',
 NOW(6), NOW(6)),
('개리슨 브라더스', 'Garrison Brothers', '미국', '텍사스', 'https://www.garrisonbros.com', 2006,
 '텍사스 힐 컨트리 최초의 합법 버번 증류소. 무더운 기후에서 빠르게 숙성하는 진한 버번을 만든다.',
 'The first legal bourbon distillery in the Texas Hill Country, making rich bourbon that matures quickly in the hot climate.',
 NOW(6), NOW(6)),
-- =========================== 일본 (재패니즈 위스키) ===========================
('야마자키', 'Yamazaki', '일본', '오사카', 'https://www.suntory.com', 1923,
 '산토리가 세운 일본 최초의 몰트 위스키 증류소. 재패니즈 위스키의 발상지로 불린다.',
 'Japan''s first malt whisky distillery, founded by Suntory, often called the birthplace of Japanese whisky.',
 NOW(6), NOW(6)),
('하쿠슈', 'Hakushu', '일본', '야마나시', 'https://www.suntory.com', 1973,
 '산토리가 ''숲의 증류소''라 부르는 고지대 증류소. 신선하고 허브향·가벼운 스모크가 어우러진다.',
 'A high-altitude Suntory distillery dubbed the "forest distillery," producing fresh, herbal and lightly smoky whisky.',
 NOW(6), NOW(6)),
('요이치', 'Yoichi', '일본', '홋카이도', 'https://www.nikka.com', 1934,
 '닛카 창립자 다케츠루 마사타카가 세운 증류소. 석탄 직화 증류로 묵직하고 피트한 풍미를 낸다.',
 'Founded by Nikka''s Masataka Taketsuru, producing robust, peaty whisky via traditional coal-fired direct distillation.',
 NOW(6), NOW(6)),
('미야기쿄', 'Miyagikyo', '일본', '미야기', 'https://www.nikka.com', 1969,
 '닛카의 두 번째 증류소. 요이치와 대비되는 부드럽고 우아한 과실 풍미를 낸다.',
 'Nikka''s second distillery, producing a soft, elegant and fruity style contrasting with Yoichi.',
 NOW(6), NOW(6)),
('치치부', 'Chichibu', '일본', '사이타마', NULL, 2008,
 '이치로 아쿠토가 설립한 벤처위스키의 소규모 증류소. ''이치로스 몰트''로 세계적 컬트 인기를 누린다.',
 'A small Venture Whisky distillery founded by Ichiro Akuto, with a global cult following for its "Ichiro''s Malt".',
 NOW(6), NOW(6)),
('후지 고텐바', 'Fuji Gotemba', '일본', '시즈오카', 'https://www.fujiwhisky.com', 1973,
 '후지산 기슭에 위치한 기린 소유 증류소. 몰트와 그레인을 모두 생산하는 ''후지'' 브랜드의 본거지다.',
 'A Kirin-owned distillery at the foot of Mt. Fuji, home of the Fuji brand and producing both malt and grain whisky.',
 NOW(6), NOW(6)),
('마르스 신슈', 'Mars Shinshu', '일본', '나가노', 'https://www.mars-whisky.com', 1985,
 '혼보 주조가 운영하는, 일본에서 가장 높은 곳에 위치한 증류소 중 하나.',
 'Operated by Hombo Shuzo, one of the highest-altitude distilleries in Japan.',
 NOW(6), NOW(6)),
('아카시 (화이트 오크)', 'Akashi (White Oak)', '일본', '효고', 'https://www.whiteoakwhisky.com', 1919,
 '에이가시마 주조가 운영하는 소규모 증류소. ''아카시'' 싱글몰트로 알려져 있다.',
 'A small distillery operated by Eigashima Shuzo, known for its "Akashi" single malt.',
 NOW(6), NOW(6)),
('아케시', 'Akkeshi', '일본', '홋카이도', 'https://akkeshi-distillery.com', 2016,
 '홋카이도 동부 해안 마을 아케시에 자리한 증류소. 아일라를 연상시키는 피티드 스타일로 호평받는다.',
 'A distillery in the eastern Hokkaido coastal town of Akkeshi, acclaimed for an Islay-style peated character.',
 NOW(6), NOW(6)),
('카노스케', 'Kanosuke', '일본', '가고시마', 'https://kanosuke.com', 2017,
 '소주 명가 고마사 양조가 세운 가고시마의 증류소. 세 개의 단식 증류기로 다층적 풍미를 만든다.',
 'A Kagoshima distillery established by renowned shochu maker Komasa Jyozo, using three pot stills for a layered character.',
 NOW(6), NOW(6)),
('마르스 츠누키', 'Mars Tsunuki', '일본', '가고시마', NULL, 2016,
 '혼보 주조가 가고시마에 세운 두 번째 증류소. 일본 최남단 증류소 중 하나다.',
 'Hombo Shuzo''s second distillery, built in Kagoshima — one of the southernmost distilleries in Japan.',
 NOW(6), NOW(6)),
('시즈오카', 'Shizuoka', '일본', '시즈오카', 'https://shizuoka-distillery.jp', 2016,
 '폐쇄된 카루이자와의 증류기를 일부 도입한 것으로 알려진 증류소. 현지 삼나무 발효조와 장작 직화 증류가 특징이다.',
 'A distillery known for incorporating a still from the closed Karuizawa, with local cedar washbacks and wood-fired direct distillation.',
 NOW(6), NOW(6)),
('사쿠라오', 'Sakurao', '일본', '히로시마', 'https://www.sakuraodistillery.com', 2017,
 '히로시마의 주류 제조사 사쿠라오 B&D가 운영하는 증류소. 세토 내해의 해양 기후에서 숙성한다.',
 'A distillery run by Hiroshima drinks maker Sakurao B&D, maturing whisky in the maritime climate of the Seto Inland Sea.',
 NOW(6), NOW(6)),
-- 일본 (폐쇄)
('카루이자와', 'Karuizawa', '일본', '나가노', NULL, 1955,
 '2000년 가동을 멈추고 2016년 철거된 전설적 증류소. 셰리 캐스크 원액이 경매에서 최고가를 경신하는 ''유령 위스키''의 정점.',
 'A legendary distillery that ceased production in 2000 and was demolished in 2016; its sherry-cask malts set record auction prices as the pinnacle of "ghost whisky".',
 NOW(6), NOW(6)),
('하뉴', 'Hanyu', '일본', '사이타마', NULL, 1980,
 '2000년 폐쇄된 사이타마의 증류소. 이치로 아쿠토의 ''카드 시리즈''로 컬트적 명성을 얻었으며, 그 정신은 치치부로 이어졌다.',
 'A Saitama distillery closed in 2000, cult-famous for Ichiro Akuto''s "Card Series," whose spirit lives on at Chichibu.',
 NOW(6), NOW(6)),
-- =========================== 대만 ===========================
('카발란', 'Kavalan', '대만', '이란', 'https://www.kavalanwhisky.com', 2005,
 '아열대 기후에서 빠른 숙성을 이뤄내며 세계 시상식을 휩쓴 대만의 대표 증류소.',
 'Taiwan''s flagship distillery, achieving rapid maturation in a subtropical climate and sweeping international awards.',
 NOW(6), NOW(6)),
('오마르', 'Omar (Nantou Distillery)', '대만', '난터우', 'https://omarwhisky.com.tw', 1977,
 '국영 타이완 담배주류공사(TTL)가 운영하는 난터우 증류소의 싱글몰트. 2008년 위스키 생산을 시작해 카발란과 함께 대만을 대표한다.',
 'The single malt of the state-owned TTL''s Nantou Distillery, which began whisky production in 2008 and, with Kavalan, represents Taiwan.',
 NOW(6), NOW(6)),
-- =========================== 대한민국 ===========================
('기원(쓰리소사이어티스)', 'Ki One(Three Societies)', '대한민국', '경기도', 'https://kione.co.kr', 2020,
 '한국 최초의 싱글몰트 위스키 증류소. 한국계 미국인 브라이언 도와 스코틀랜드 디스틸러 앤드루 샌드가 설립해 ''기원(Ki One)''을 출시했다.',
 'South Korea''s first single malt distillery, founded by Korean-American Bryan Do and Scottish distiller Andrew Shand, producing "Ki One".',
 NOW(6), NOW(6)),
('김창수 위스키 증류소', 'Kim Chang-soo Whisky Distillery', '대한민국', '경기도', 'https://www.instagram.com/kimchangsoodistillery', 2020,
 '경기도 김포 통진읍에 자리한 한국의 소규모 싱글몰트 증류소. 마스터 디스틸러 김창수가 직접 운영하며 한정 릴리스로 큰 화제를 모았다.',
 'A small Korean single malt distillery in Gimpo, Gyeonggi, run by master distiller Kim Chang-soo, drawing great attention with its limited releases.',
 NOW(6), NOW(6)),
-- =========================== 인도 ===========================
('암룻', 'Amrut', '인도', '벵갈루루', 'https://www.amrutdistilleries.com', 1948,
 '인도 싱글몰트를 세계 무대에 알린 선구적 증류소. 더운 기후에서 빠르게 숙성된 진한 풍미가 특징이다.',
 'A pioneering distillery that put Indian single malt on the world map, with intense flavour from rapid maturation in a hot climate.',
 NOW(6), NOW(6)),
('폴 존', 'Paul John', '인도', '고아', 'https://www.pauljohnwhisky.com', 1996,
 '인도 고아에 위치한 증류소(존 디스틸러리스). 인도산 보리로 만든 싱글몰트로 호평받는다.',
 'A Goa-based distillery (John Distilleries) acclaimed for single malt made from Indian barley.',
 NOW(6), NOW(6)),
('인드리', 'Indri', '인도', '하리아나 (인드리)', 'https://www.indri.in', 2021,
 '피카딜리 디스틸러리가 하리아나 인드리에서 생산하는 싱글몰트. 2021년 출시 후 세계 시상식에서 잇따라 수상하며 급부상했다.',
 'A single malt produced by Piccadily Distillery in Indri, Haryana; launched in 2021, it rapidly rose to fame with international awards.',
 NOW(6), NOW(6)),
('람푸르', 'Rampur', '인도', '우타르프라데시 (람푸르)', 'https://rampursinglemalt.com', 1943,
 '1943년 설립된 라디코 카이탄의 람푸르 증류소에서 만드는 인도 싱글몰트. 히말라야 기슭의 물과 보리를 사용한다.',
 'An Indian single malt from Radico Khaitan''s Rampur distillery (est. 1943), using Himalayan-foothill water and barley.',
 NOW(6), NOW(6)),
-- =========================== 캐나다 ===========================
('캐나디안 클럽 (하이람 워커)', 'Canadian Club (Hiram Walker)', '캐나다', '온타리오', 'https://www.canadianclubwhisky.com', 1858,
 '하이람 워커가 세운 캐나다의 상징적 증류소. 부드러운 블렌디드 캐나디안 위스키로 유명하다.',
 'An iconic Canadian distillery founded by Hiram Walker, famed for smooth blended Canadian whisky.',
 NOW(6), NOW(6)),
-- =========================== 웨일스 ===========================
('펜더린', 'Penderyn', '웨일스', '브레컨 비콘스', 'https://penderyn.wales', 2000,
 '100여 년 만에 웨일스에 다시 문을 연 증류소. 독특한 패러데이 단일 증류기를 사용한다.',
 'The first distillery to reopen in Wales in over a century, using a unique single Faraday still.',
 NOW(6), NOW(6)),
-- =========================== 스웨덴 ===========================
('막미라', 'Mackmyra', '스웨덴', '옙플레', 'https://mackmyra.com', 1999,
 '스웨덴 최초의 몰트 위스키 증류소. 현지 보리·노간주나무 연기, 친환경 ''중력식'' 증류소로 알려져 있다.',
 'Sweden''s first malt whisky distillery, known for local barley, juniper smoke and its eco-friendly gravity-fed facility.',
 NOW(6), NOW(6)),
('하이 코스트', 'High Coast', '스웨덴', '회가 쿠스텐', 'https://highcoastwhisky.se', 2010,
 '스웨덴 북부 회가 쿠스텐(High Coast)에 자리한 증류소. 옛 ''박스(Box)''라는 이름으로도 알려져 있으며 극단적 사계절 기후에서 숙성한다.',
 'A distillery in northern Sweden''s High Coast (formerly known as "Box"), maturing whisky through extreme seasonal temperature swings.',
 NOW(6), NOW(6)),
-- =========================== 호주 ===========================
('스타워드', 'Starward', '호주', '멜버른', 'https://starward.com.au', 2007,
 '호주산 와인(쉬라즈 등) 캐스크 숙성으로 차별화한 멜버른의 현대적 증류소.',
 'A modern Melbourne distillery differentiated by maturation in Australian wine (e.g. Shiraz) casks.',
 NOW(6), NOW(6)),
('설리번스 코브', 'Sullivans Cove', '호주', '태즈메이니아', 'https://sullivanscove.com', 1994,
 '2014년 ''세계 최고의 싱글몰트''로 선정되며 세계적 명성을 얻은 태즈메이니아의 싱글 캐스크 증류소.',
 'A Tasmanian single-cask distillery that gained worldwide fame after being named World''s Best Single Malt in 2014.',
 NOW(6), NOW(6)),
('라크', 'Lark', '호주', '태즈메이니아', 'https://www.larkdistillery.com', 1992,
 '현대 태즈메이니아 위스키 산업의 부흥을 일으킨 선구적 증류소. 호주 위스키의 아버지로 불리는 빌 라크가 설립했다.',
 'A pioneering distillery that sparked the revival of the modern Tasmanian whisky industry, founded by Bill Lark, "the godfather of Australian whisky".',
 NOW(6), NOW(6)),
-- =========================== 잉글랜드 ===========================
('코츠월드', 'Cotswolds', '잉글랜드', '코츠월드', 'https://www.cotswoldsdistillery.com', 2014,
 '잉글랜드 코츠월드 지방의 증류소. 현지 재배 보리를 사용한 풍부하고 과실미 가득한 싱글몰트로 잉글리시 위스키 부흥을 이끈다.',
 'A distillery in England''s Cotswolds using locally grown barley to make a rich, fruity single malt, leading the English whisky revival.',
 NOW(6), NOW(6)),
('더 레이크스', 'The Lakes', '잉글랜드', '컴브리아', 'https://www.lakesdistillery.com', 2014,
 '잉글랜드 레이크 디스트릭트에 자리한 증류소. 셰리 캐스크 위주의 ''더 위스키메이커스 리저브'' 시리즈로 알려져 있다.',
 'A distillery in England''s Lake District, known for its sherry-cask-led "Whiskymaker''s Reserve" series.',
 NOW(6), NOW(6)),
('빔버', 'Bimber', '잉글랜드', '런던', 'https://bimberdistillery.co.uk', 2015,
 '런던의 수공예 증류소. 플로어 몰팅·장시간 발효 등 전통 공정을 고집하며 컬트적 인기를 누린다.',
 'A London craft distillery with a cult following, insisting on traditional methods such as floor malting and long fermentation.',
 NOW(6), NOW(6)),
('잉글리시 위스키 (세인트 조지스)', 'The English Whisky Co. (St. George''s)', '잉글랜드', '노퍽', 'https://www.englishwhisky.co.uk', 2006,
 '100여 년 만에 잉글랜드에 다시 문을 연 증류소. 노퍽에 위치하며 현대 잉글리시 위스키의 출발점으로 평가된다.',
 'The first distillery to open in England in over a century, located in Norfolk and regarded as the starting point of modern English whisky.',
 NOW(6), NOW(6)),
-- =========================== 프랑스 ===========================
('아르모릭 (바랑겜)', 'Armorik (Warenghem)', '프랑스', '브르타뉴', 'https://www.distillerie-warenghem.com', 1900,
 '1900년 설립된 브르타뉴의 바랑겜 증류소에서 만드는 프랑스 싱글몰트. 1998년 프랑스 최초의 싱글몰트를 선보였다.',
 'A French single malt from the Warenghem distillery in Brittany (est. 1900), which released France''s first single malt in 1998.',
 NOW(6), NOW(6)),
-- =========================== 네덜란드 ===========================
('밀스톤 (자위담)', 'Millstone (Zuidam)', '네덜란드', '바를러나사우', 'https://www.zuidam.eu', 1975,
 '가족 경영 자위담 증류소가 만드는 네덜란드 싱글몰트. 자체 제분한 곡물과 풍차에서 유래한 ''밀스톤''이라는 이름이 특징이다.',
 'A Dutch single malt from the family-run Zuidam distillery, named "Millstone" after its windmill-milled grain.',
 NOW(6), NOW(6)),
-- =========================== 독일 ===========================
('슐리어스', 'Slyrs', '독일', '바이에른', 'https://www.slyrs.com', 1999,
 '바이에른 알프스 기슭에 자리한 독일 싱글몰트 증류소. 현지 보리와 너도밤나무 훈연 방식으로 알려져 있다.',
 'A German single malt distillery at the foot of the Bavarian Alps, known for local barley and beechwood smoking.',
 NOW(6), NOW(6)),
-- =========================== 이스라엘 ===========================
('밀크 앤 허니', 'Milk & Honey (M&H)', '이스라엘', '텔아비브', 'https://mh-distillery.com', 2014,
 '이스라엘 최초의 위스키 증류소. 지중해성 더운 기후에서 빠르게 숙성하는 싱글몰트를 생산한다.',
 'Israel''s first whisky distillery, producing single malt that matures rapidly in the hot Mediterranean climate.',
 NOW(6), NOW(6)),
-- =========================== 남아프리카공화국 ===========================
('제임스 세지윅', 'James Sedgwick Distillery', '남아프리카공화국', '웰링턴', NULL, 1886,
 '쓰리 십스·베인스 등을 생산하는 남아공의 대표 증류소. 아프리카 위스키의 중심지로 꼽힌다.',
 'South Africa''s flagship distillery producing Three Ships and Bain''s, regarded as the home of African whisky.',
 NOW(6), NOW(6));


ALTER TABLE producer ALTER COLUMN type DROP DEFAULT;
