ALTER TABLE inquiry
    MODIFY COLUMN category ENUM (
        'ACCOUNT_INQUIRY',
        'BUG_REPORT',
        'CORRECTION_REQUEST',
        'FEATURE_REQUEST',
        'PARTNERSHIP_INQUIRY',
        'OTHER'
    ) NOT NULL COMMENT '분류 — ACCOUNT_INQUIRY/BUG_REPORT/CORRECTION_REQUEST/FEATURE_REQUEST/PARTNERSHIP_INQUIRY/OTHER';
