-- 기존 생산자/주류의 자유 입력 지역을 WineRegion 코드에 연결한다.
-- 정규 산지의 단일 소스는 WineRegion enum 이며, 아래 값은 V4~V6 생산자 시드의 호환 스냅샷이다.
-- 복수 산지·카탈로그 미지원 값은 추측하지 않고 NULL 로 남겨 주류별 수동 선택 대상으로 둔다.

ALTER TABLE producer
    ADD COLUMN region_code VARCHAR(40) NULL
        COMMENT '기본 산지 코드(WineRegion) — 주류 등록 시 제안값' AFTER region;

CREATE TEMPORARY TABLE tmp_legacy_region_mapping (
    category VARCHAR(10) NOT NULL,
    country VARCHAR(100) NOT NULL,
    legacy_region VARCHAR(100) NOT NULL,
    region_code VARCHAR(40) NOT NULL,
    canonical_l1_name VARCHAR(100) NOT NULL,
    PRIMARY KEY (category, country, legacy_region)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO tmp_legacy_region_mapping
    (category, country, legacy_region, region_code, canonical_l1_name)
VALUES
    ('COGNAC', '프랑스', '꼬냑', 'FR_COGNAC', '꼬냑'),
    ('WHISKY', '남아프리카공화국', '웰링턴', 'ZA_CAPE_WINELANDS', '케이프 와인랜드'),
    ('WHISKY', '네덜란드', '바를러나사우', 'NL_NOORD_BRABANT', '노르트브라반트'),
    ('WHISKY', '대만', '난터우', 'TW_NANTOU', '난터우'),
    ('WHISKY', '대만', '이란', 'TW_YILAN', '이란'),
    ('WHISKY', '대한민국', '경기도', 'KR_GYEONGGI', '경기도'),
    ('WHISKY', '덴마크', '윌란 (서부)', 'DK_MIDTJYLLAND', '윌란'),
    ('WHISKY', '독일', '바이에른', 'DE_BAYERN', '바이에른'),
    ('WHISKY', '미국', '뉴욕', 'US_NEW_YORK', '뉴욕'),
    ('WHISKY', '미국', '메릴랜드', 'US_MARYLAND', '메릴랜드'),
    ('WHISKY', '미국', '버몬트', 'US_VERMONT', '버몬트'),
    ('WHISKY', '미국', '버지니아', 'US_VIRGINIA', '버지니아'),
    ('WHISKY', '미국', '워싱턴', 'US_WASHINGTON', '워싱턴'),
    ('WHISKY', '미국', '유타', 'US_UTAH', '유타'),
    ('WHISKY', '미국', '인디애나', 'US_INDIANA', '인디애나'),
    ('WHISKY', '미국', '켄터키', 'US_KENTUCKY', '켄터키'),
    ('WHISKY', '미국', '콜로라도', 'US_COLORADO', '콜로라도'),
    ('WHISKY', '미국', '테네시', 'US_TENNESSEE', '테네시'),
    ('WHISKY', '미국', '텍사스', 'US_TEXAS', '텍사스'),
    ('WHISKY', '스웨덴', '옙플레', 'SE_GAVLEBORG', '옙플레'),
    ('WHISKY', '스웨덴', '회가 쿠스텐', 'SE_VASTERNORRLAND', '회가 쿠스텐'),
    ('WHISKY', '스코틀랜드', 'Campbeltown', 'GB_SCT_CAMPBELTOWN', '캠벨타운'),
    ('WHISKY', '스코틀랜드', 'Highland', 'GB_SCT_HIGHLAND', '하이랜드'),
    ('WHISKY', '스코틀랜드', 'Island', 'GB_SCT_ISLANDS', '아일랜드 (섬)'),
    ('WHISKY', '스코틀랜드', 'Islay', 'GB_SCT_ISLAY', '아일라'),
    ('WHISKY', '스코틀랜드', 'Isle of Arran', 'GB_SCT_ISLANDS', '아일랜드 (섬)'),
    ('WHISKY', '스코틀랜드', 'Isle of Jura', 'GB_SCT_ISLANDS', '아일랜드 (섬)'),
    ('WHISKY', '스코틀랜드', 'Isle of Mull', 'GB_SCT_ISLANDS', '아일랜드 (섬)'),
    ('WHISKY', '스코틀랜드', 'Isle of Raasay', 'GB_SCT_ISLANDS', '아일랜드 (섬)'),
    ('WHISKY', '스코틀랜드', 'Isle of Skye', 'GB_SCT_ISLANDS', '아일랜드 (섬)'),
    ('WHISKY', '스코틀랜드', 'Lowland', 'GB_SCT_LOWLAND', '로우랜드'),
    ('WHISKY', '스코틀랜드', 'Orkney', 'GB_SCT_ISLANDS', '아일랜드 (섬)'),
    ('WHISKY', '스코틀랜드', 'Speyside', 'GB_SCT_SPEYSIDE', '스페이사이드'),
    ('WHISKY', '아일랜드', '더블린', 'IE_DUBLIN', '더블린'),
    ('WHISKY', '아일랜드', '라우스', 'IE_LOUTH', '라우스'),
    ('WHISKY', '아일랜드', '라우스 (던도크)', 'IE_LOUTH', '라우스'),
    ('WHISKY', '아일랜드', '미스 (슬레인)', 'IE_MEATH', '미스'),
    ('WHISKY', '아일랜드', '북아일랜드 (앤트림)', 'GB_NIR_ANTRIM', '앤트림'),
    ('WHISKY', '아일랜드', '오펄리 (틀라모어)', 'IE_OFFALY', '오펄리'),
    ('WHISKY', '아일랜드', '워터포드', 'IE_WATERFORD', '워터포드'),
    ('WHISKY', '아일랜드', '웨스트미스 (킬베간)', 'IE_WESTMEATH', '웨스트미스'),
    ('WHISKY', '아일랜드', '케리 (딩글)', 'IE_KERRY', '케리'),
    ('WHISKY', '아일랜드', '코크', 'IE_CORK', '코크'),
    ('WHISKY', '웨일스', '브레컨 비콘스', 'GB_WLS_POWYS', '포이스'),
    ('WHISKY', '이스라엘', '텔아비브', 'IL_TEL_AVIV', '텔아비브'),
    ('WHISKY', '인도', '고아', 'IN_GOA', '고아'),
    ('WHISKY', '인도', '벵갈루루', 'IN_KARNATAKA', '카르나타카'),
    ('WHISKY', '인도', '우타르프라데시 (람푸르)', 'IN_UTTAR_PRADESH', '우타르프라데시'),
    ('WHISKY', '인도', '하리아나 (인드리)', 'IN_HARYANA', '하리아나'),
    ('WHISKY', '일본', '가고시마', 'JP_KAGOSHIMA', '가고시마'),
    ('WHISKY', '일본', '나가노', 'JP_NAGANO', '나가노'),
    ('WHISKY', '일본', '도야마', 'JP_TOYAMA', '도야마'),
    ('WHISKY', '일본', '미야기', 'JP_MIYAGI', '미야기'),
    ('WHISKY', '일본', '사이타마', 'JP_SAITAMA', '사이타마'),
    ('WHISKY', '일본', '시가', 'JP_SHIGA', '시가'),
    ('WHISKY', '일본', '시즈오카', 'JP_SHIZUOKA', '시즈오카'),
    ('WHISKY', '일본', '아이치', 'JP_AICHI', '아이치'),
    ('WHISKY', '일본', '야마나시', 'JP_YAMANASHI', '야마나시'),
    ('WHISKY', '일본', '오사카', 'JP_OSAKA', '오사카'),
    ('WHISKY', '일본', '홋카이도', 'JP_HOKKAIDO', '홋카이도'),
    ('WHISKY', '일본', '효고', 'JP_HYOGO', '효고'),
    ('WHISKY', '일본', '후쿠시마', 'JP_FUKUSHIMA', '후쿠시마'),
    ('WHISKY', '일본', '히로시마', 'JP_HIROSHIMA', '히로시마'),
    ('WHISKY', '잉글랜드', '노퍽', 'GB_ENG_NORFOLK', '노퍽'),
    ('WHISKY', '잉글랜드', '더비셔', 'GB_ENG_DERBYSHIRE', '더비셔'),
    ('WHISKY', '잉글랜드', '런던', 'GB_ENG_LONDON', '런던'),
    ('WHISKY', '잉글랜드', '요크셔', 'GB_ENG_YORKSHIRE', '요크셔'),
    ('WHISKY', '잉글랜드', '컴브리아', 'GB_ENG_CUMBRIA', '컴브리아'),
    ('WHISKY', '잉글랜드', '코츠월드', 'GB_ENG_COTSWOLDS', '코츠월드'),
    ('WHISKY', '캐나다', '매니토바', 'CA_MANITOBA', '매니토바'),
    ('WHISKY', '캐나다', '앨버타', 'CA_ALBERTA', '앨버타'),
    ('WHISKY', '캐나다', '온타리오', 'CA_ONTARIO', '온타리오'),
    ('WHISKY', '프랑스', '브르타뉴', 'FR_BRETAGNE', '브르타뉴'),
    ('WHISKY', '핀란드', '이소키로', 'FI_OSTROBOTHNIA', '오스트로보스니아'),
    ('WHISKY', '호주', '멜버른', 'AU_VICTORIA', '빅토리아'),
    ('WHISKY', '호주', '서오스트레일리아 (앨버니)', 'AU_WESTERN_AUSTRALIA', '웨스턴 오스트레일리아'),
    ('WHISKY', '호주', '태즈메이니아', 'AU_TASMANIA', '태즈메이니아'),
    ('WINE', '그리스', '나우사', 'GR_MACEDONIA', '마케도니아'),
    ('WINE', '그리스', '산토리니', 'GR_AEGEAN', '에게해 섬'),
    ('WINE', '그리스', '아민데오', 'GR_MACEDONIA', '마케도니아'),
    ('WINE', '남아공', '스와틀란트', 'ZA_WEST_COAST', '웨스트 코스트'),
    ('WINE', '남아공', '스텔렌보스', 'ZA_CAPE_WINELANDS_STELLENBOSCH', '케이프 와인랜드'),
    ('WINE', '남아공', '헤멜엔아르더', 'ZA_OVERBERG', '오버버그'),
    ('WINE', '남아프리카공화국', '스텔렌보스', 'ZA_CAPE_WINELANDS_STELLENBOSCH', '케이프 와인랜드'),
    ('WINE', '남아프리카공화국', '콘스탄시아', 'ZA_CAPE_TOWN', '케이프타운'),
    ('WINE', '남아프리카공화국', '프란스후크', 'ZA_CAPE_WINELANDS_FRANSCHHOEK', '케이프 와인랜드'),
    ('WINE', '뉴질랜드', '마틴버러', 'NZ_WAIRARAPA', '와이라라파'),
    ('WINE', '뉴질랜드', '말버러', 'NZ_MARLBOROUGH', '말버러'),
    ('WINE', '뉴질랜드', '센트럴 오타고', 'NZ_OTAGO_CENTRAL_OTAGO', '오타고'),
    ('WINE', '뉴질랜드', '센트럴오타고', 'NZ_OTAGO_CENTRAL_OTAGO', '오타고'),
    ('WINE', '뉴질랜드', '오클랜드', 'NZ_AUCKLAND', '오클랜드'),
    ('WINE', '뉴질랜드', '호크스 베이', 'NZ_HAWKES_BAY', '호크스 베이'),
    ('WINE', '뉴질랜드', '혹스베이', 'NZ_HAWKES_BAY', '호크스 베이'),
    ('WINE', '독일', '나에', 'DE_NAHE', '나헤'),
    ('WINE', '독일', '라인가우', 'DE_RHEINGAU', '라인가우'),
    ('WINE', '독일', '라인헤센', 'DE_RHEINHESSEN', '라인헤센'),
    ('WINE', '독일', '모젤', 'DE_MOSEL', '모젤'),
    ('WINE', '독일', '바덴', 'DE_BADEN', '바덴'),
    ('WINE', '레바논', '베카 밸리', 'LB_BEQAA', '베카 밸리'),
    ('WINE', '미국', '나파 밸리', 'US_CALIFORNIA_NAPA_VALLEY', '캘리포니아'),
    ('WINE', '미국', '나파 밸리 (러더퍼드)', 'US_CALIFORNIA_NAPA_VALLEY', '캘리포니아'),
    ('WINE', '미국', '나파 밸리 (세인트헬레나)', 'US_CALIFORNIA_NAPA_VALLEY', '캘리포니아'),
    ('WINE', '미국', '나파 밸리 (스택스 립)', 'US_CALIFORNIA_NAPA_VALLEY', '캘리포니아'),
    ('WINE', '미국', '나파 밸리 (오크빌)', 'US_CALIFORNIA_NAPA_VALLEY', '캘리포니아'),
    ('WINE', '미국', '나파 밸리 (용트빌)', 'US_CALIFORNIA_NAPA_VALLEY', '캘리포니아'),
    ('WINE', '미국', '나파 밸리 (캘리스토가)', 'US_CALIFORNIA_NAPA_VALLEY', '캘리포니아'),
    ('WINE', '미국', '소노마', 'US_CALIFORNIA_SONOMA', '캘리포니아'),
    ('WINE', '미국', '소노마 (러시안 리버 밸리)', 'US_CALIFORNIA_SONOMA', '캘리포니아'),
    ('WINE', '미국', '소노마 (소노마 코스트)', 'US_CALIFORNIA_SONOMA', '캘리포니아'),
    ('WINE', '미국', '오리건', 'US_OREGON', '오리건'),
    ('WINE', '미국', '워싱턴', 'US_WASHINGTON', '워싱턴'),
    ('WINE', '미국', '워싱턴 (왈라 왈라)', 'US_WASHINGTON_WALLA_WALLA', '워싱턴'),
    ('WINE', '미국', '캘리포니아', 'US_CALIFORNIA', '캘리포니아'),
    ('WINE', '미국', '캘리포니아 (나이츠 밸리)', 'US_CALIFORNIA', '캘리포니아'),
    ('WINE', '미국', '캘리포니아 (산타바버라)', 'US_CALIFORNIA', '캘리포니아'),
    ('WINE', '미국', '캘리포니아 (스타 라인 밸리)', 'US_CALIFORNIA', '캘리포니아'),
    ('WINE', '미국', '캘리포니아 (파소 로블레스)', 'US_CALIFORNIA_PASO_ROBLES', '캘리포니아'),
    ('WINE', '스페인', '리베라 델 두에로', 'ES_CASTILLA_Y_LEON_RIBERA_DEL_DUERO', '카스티야 이 레온'),
    ('WINE', '스페인', '리아스 바이사스', 'ES_GALICIA_RIAS_BAIXAS', '갈리시아'),
    ('WINE', '스페인', '리오하', 'ES_RIOJA', '리오하'),
    ('WINE', '스페인', '산루카르 (만사니야)', 'ES_ANDALUCIA_JEREZ', '안달루시아'),
    ('WINE', '스페인', '엘 푸에르토 데 산타 마리아', 'ES_ANDALUCIA_JEREZ', '안달루시아'),
    ('WINE', '스페인', '카스티야 이 레온', 'ES_CASTILLA_Y_LEON', '카스티야 이 레온'),
    ('WINE', '스페인', '카탈루냐 (카바)', 'ES_CATALUNYA', '카탈루냐'),
    ('WINE', '스페인', '카탈루냐 (페네데스)', 'ES_CATALUNYA_PENEDES', '카탈루냐'),
    ('WINE', '스페인', '토로', 'ES_CASTILLA_Y_LEON_TORO', '카스티야 이 레온'),
    ('WINE', '스페인', '프리오라트', 'ES_CATALUNYA_PRIORAT', '카탈루냐'),
    ('WINE', '스페인', '헤레스 (셰리)', 'ES_ANDALUCIA_JEREZ', '안달루시아'),
    ('WINE', '스페인', '후미야', 'ES_MURCIA_JUMILLA', '무르시아'),
    ('WINE', '아르헨티나', '멘도사', 'AR_MENDOZA', '멘도사'),
    ('WINE', '아르헨티나', '살타 (칼차키 밸리)', 'AR_SALTA', '살타'),
    ('WINE', '오스트리아', '바하우', 'AT_NIEDEROSTERREICH_WACHAU', '니더외스터라이히'),
    ('WINE', '오스트리아', '캄프탈', 'AT_NIEDEROSTERREICH_KAMPTAL', '니더외스터라이히'),
    ('WINE', '우루과이', '마이도나도', 'UY_MALDONADO', '마이도나도'),
    ('WINE', '이탈리아', '롬바르디아 (프란차코르타)', 'IT_LOMBARDIA', '롬바르디아'),
    ('WINE', '이탈리아', '베네토', 'IT_VENETO', '베네토'),
    ('WINE', '이탈리아', '베네토 (소아베)', 'IT_VENETO_SOAVE', '베네토'),
    ('WINE', '이탈리아', '사르데냐', 'IT_SARDEGNA', '사르데냐'),
    ('WINE', '이탈리아', '시칠리아', 'IT_SICILIA', '시칠리아'),
    ('WINE', '이탈리아', '시칠리아 (에트나)', 'IT_SICILIA', '시칠리아'),
    ('WINE', '이탈리아', '알토 아디제', 'IT_TRENTINO_ALTO_ADIGE', '트렌티노 알토 아디제'),
    ('WINE', '이탈리아', '캄파니아', 'IT_CAMPANIA', '캄파니아'),
    ('WINE', '이탈리아', '토스카나', 'IT_TOSCANA', '토스카나'),
    ('WINE', '이탈리아', '프리울리', 'IT_FRIULI', '프리울리'),
    ('WINE', '이탈리아', '피에몬테', 'IT_PIEMONTE', '피에몬테'),
    ('WINE', '인도', '나시크 (마하라슈트라)', 'IN_MAHARASHTRA', '마하라슈트라'),
    ('WINE', '인도', '난디 힐스 (카르나타카)', 'IN_KARNATAKA', '카르나타카'),
    ('WINE', '일본', '도치기 (아시카가)', 'JP_TOCHIGI', '도치기'),
    ('WINE', '일본', '야마나시', 'JP_YAMANASHI', '야마나시'),
    ('WINE', '조지아', '카헤티', 'GE_KAKHETI', '카헤티'),
    ('WINE', '중국', '닝샤', 'CN_NINGXIA', '닝샤'),
    ('WINE', '중국', '산둥 (옌타이)', 'CN_SHANDONG', '산둥'),
    ('WINE', '중국', '산시 (山西)', 'CN_SHANXI', '산시'),
    ('WINE', '중국', '윈난', 'CN_YUNNAN', '윈난'),
    ('WINE', '칠레', '마이포', 'CL_CENTRAL_VALLEY_MAIPO', '센트럴 밸리'),
    ('WINE', '칠레', '마이포 밸리', 'CL_CENTRAL_VALLEY_MAIPO', '센트럴 밸리'),
    ('WINE', '칠레', '아콩카과', 'CL_ACONCAGUA', '아콩카과'),
    ('WINE', '칠레', '콜차과', 'CL_CENTRAL_VALLEY_COLCHAGUA', '센트럴 밸리'),
    ('WINE', '칠레', '콜차과 (아팔타)', 'CL_CENTRAL_VALLEY_COLCHAGUA', '센트럴 밸리'),
    ('WINE', '칠레', '푸엔테 알토 (마이포)', 'CL_CENTRAL_VALLEY_MAIPO', '센트럴 밸리'),
    ('WINE', '캐나다', '온타리오', 'CA_ONTARIO', '온타리오'),
    ('WINE', '포르투갈', '도루', 'PT_DOURO', '도루'),
    ('WINE', '포르투갈', '마데이라', 'PT_MADEIRA', '마데이라'),
    ('WINE', '포르투갈', '바이라다', 'PT_BAIRRADA', '바이라다'),
    ('WINE', '포르투갈', '알렌테주', 'PT_ALENTEJO', '알렌테주'),
    ('WINE', '프랑스', '론', 'FR_RHONE', '론'),
    ('WINE', '프랑스', '론 (에르미타주)', 'FR_RHONE', '론'),
    ('WINE', '프랑스', '루아르', 'FR_LOIRE', '루아르'),
    ('WINE', '프랑스', '루아르 (부브레)', 'FR_LOIRE_VOUVRAY', '루아르'),
    ('WINE', '프랑스', '보르도', 'FR_BORDEAUX', '보르도'),
    ('WINE', '프랑스', '보졸레', 'FR_BEAUJOLAIS', '보졸레'),
    ('WINE', '프랑스', '부르고뉴', 'FR_BOURGOGNE', '부르고뉴'),
    ('WINE', '프랑스', '샴페인', 'FR_CHAMPAGNE', '샹파뉴'),
    ('WINE', '프랑스', '알자스', 'FR_ALSACE', '알자스'),
    ('WINE', '프랑스', '프로방스', 'FR_PROVENCE', '프로방스'),
    ('WINE', '프랑스', '프로방스 (방돌)', 'FR_PROVENCE', '프로방스'),
    ('WINE', '헝가리', '토카이', 'HU_TOKAJ', '토카이'),
    ('WINE', '호주', '뉴사우스웨일스', 'AU_NEW_SOUTH_WALES', '뉴사우스웨일스'),
    ('WINE', '호주', '마가렛 리버', 'AU_WESTERN_AUSTRALIA_MARGARET_RIVER', '웨스턴 오스트레일리아'),
    ('WINE', '호주', '맥라렌 베일', 'AU_SOUTH_AUSTRALIA_MCLAREN_VALE', '사우스 오스트레일리아'),
    ('WINE', '호주', '바로사 밸리', 'AU_SOUTH_AUSTRALIA_BAROSSA_VALLEY', '사우스 오스트레일리아'),
    ('WINE', '호주', '빅토리아', 'AU_VICTORIA', '빅토리아'),
    ('WINE', '호주', '빅토리아 (비치워스)', 'AU_VICTORIA', '빅토리아'),
    ('WINE', '호주', '사우스오스트레일리아', 'AU_SOUTH_AUSTRALIA', '사우스 오스트레일리아'),
    ('WINE', '호주', '사우스오스트레일리아 (클레어 밸리)', 'AU_SOUTH_AUSTRALIA_CLARE_VALLEY', '사우스 오스트레일리아'),
    ('WINE', '호주', '야라 밸리', 'AU_VICTORIA_YARRA_VALLEY', '빅토리아'),
    ('WINE', '호주', '웨스턴오스트레일리아', 'AU_WESTERN_AUSTRALIA', '웨스턴 오스트레일리아'),
    ('WINE', '호주', '캔버라', 'AU_NEW_SOUTH_WALES_CANBERRA_DISTRICT', '뉴사우스웨일스'),
    ('WINE', '호주', '헌터 밸리', 'AU_NEW_SOUTH_WALES_HUNTER_VALLEY', '뉴사우스웨일스');

-- 기존 spirit.region 에 한글/영문 정규명이 저장된 경우도 함께 보정한다.
INSERT IGNORE INTO tmp_legacy_region_mapping
    (category, country, legacy_region, region_code, canonical_l1_name)
VALUES
    ('COGNAC', '프랑스', 'Cognac', 'FR_COGNAC', '꼬냑'),
    ('WHISKY', '남아프리카공화국', '케이프 와인랜드', 'ZA_CAPE_WINELANDS', '케이프 와인랜드'),
    ('WHISKY', '남아프리카공화국', 'Cape Winelands', 'ZA_CAPE_WINELANDS', '케이프 와인랜드'),
    ('WHISKY', '네덜란드', '노르트브라반트', 'NL_NOORD_BRABANT', '노르트브라반트'),
    ('WHISKY', '네덜란드', 'North Brabant', 'NL_NOORD_BRABANT', '노르트브라반트'),
    ('WHISKY', '대만', 'Nantou', 'TW_NANTOU', '난터우'),
    ('WHISKY', '대만', 'Yilan', 'TW_YILAN', '이란'),
    ('WHISKY', '대한민국', 'Gyeonggi', 'KR_GYEONGGI', '경기도'),
    ('WHISKY', '덴마크', '윌란', 'DK_MIDTJYLLAND', '윌란'),
    ('WHISKY', '덴마크', 'Jutland', 'DK_MIDTJYLLAND', '윌란'),
    ('WHISKY', '독일', 'Bavaria', 'DE_BAYERN', '바이에른'),
    ('WHISKY', '미국', 'New York', 'US_NEW_YORK', '뉴욕'),
    ('WHISKY', '미국', 'Maryland', 'US_MARYLAND', '메릴랜드'),
    ('WHISKY', '미국', 'Vermont', 'US_VERMONT', '버몬트'),
    ('WHISKY', '미국', 'Virginia', 'US_VIRGINIA', '버지니아'),
    ('WHISKY', '미국', 'Washington', 'US_WASHINGTON', '워싱턴'),
    ('WHISKY', '미국', 'Utah', 'US_UTAH', '유타'),
    ('WHISKY', '미국', 'Indiana', 'US_INDIANA', '인디애나'),
    ('WHISKY', '미국', 'Kentucky', 'US_KENTUCKY', '켄터키'),
    ('WHISKY', '미국', 'Colorado', 'US_COLORADO', '콜로라도'),
    ('WHISKY', '미국', 'Tennessee', 'US_TENNESSEE', '테네시'),
    ('WHISKY', '미국', 'Texas', 'US_TEXAS', '텍사스'),
    ('WHISKY', '스웨덴', 'Gävle', 'SE_GAVLEBORG', '옙플레'),
    ('WHISKY', '스웨덴', 'High Coast', 'SE_VASTERNORRLAND', '회가 쿠스텐'),
    ('WHISKY', '스코틀랜드', '캠벨타운', 'GB_SCT_CAMPBELTOWN', '캠벨타운'),
    ('WHISKY', '스코틀랜드', '하이랜드', 'GB_SCT_HIGHLAND', '하이랜드'),
    ('WHISKY', '스코틀랜드', '아일랜드 (섬)', 'GB_SCT_ISLANDS', '아일랜드 (섬)'),
    ('WHISKY', '스코틀랜드', 'Islands', 'GB_SCT_ISLANDS', '아일랜드 (섬)'),
    ('WHISKY', '스코틀랜드', '아일라', 'GB_SCT_ISLAY', '아일라'),
    ('WHISKY', '스코틀랜드', '로우랜드', 'GB_SCT_LOWLAND', '로우랜드'),
    ('WHISKY', '스코틀랜드', '스페이사이드', 'GB_SCT_SPEYSIDE', '스페이사이드'),
    ('WHISKY', '아일랜드', 'Dublin', 'IE_DUBLIN', '더블린'),
    ('WHISKY', '아일랜드', 'Louth', 'IE_LOUTH', '라우스'),
    ('WHISKY', '아일랜드', '미스', 'IE_MEATH', '미스'),
    ('WHISKY', '아일랜드', 'Meath', 'IE_MEATH', '미스'),
    ('WHISKY', '아일랜드', '앤트림', 'GB_NIR_ANTRIM', '앤트림'),
    ('WHISKY', '아일랜드', 'Antrim', 'GB_NIR_ANTRIM', '앤트림'),
    ('WHISKY', '아일랜드', '오펄리', 'IE_OFFALY', '오펄리'),
    ('WHISKY', '아일랜드', 'Offaly', 'IE_OFFALY', '오펄리'),
    ('WHISKY', '아일랜드', 'Waterford', 'IE_WATERFORD', '워터포드'),
    ('WHISKY', '아일랜드', '웨스트미스', 'IE_WESTMEATH', '웨스트미스'),
    ('WHISKY', '아일랜드', 'Westmeath', 'IE_WESTMEATH', '웨스트미스'),
    ('WHISKY', '아일랜드', '케리', 'IE_KERRY', '케리'),
    ('WHISKY', '아일랜드', 'Kerry', 'IE_KERRY', '케리'),
    ('WHISKY', '아일랜드', 'Cork', 'IE_CORK', '코크'),
    ('WHISKY', '웨일스', '포이스', 'GB_WLS_POWYS', '포이스'),
    ('WHISKY', '웨일스', 'Powys', 'GB_WLS_POWYS', '포이스'),
    ('WHISKY', '이스라엘', 'Tel Aviv', 'IL_TEL_AVIV', '텔아비브'),
    ('WHISKY', '인도', 'Goa', 'IN_GOA', '고아'),
    ('WHISKY', '인도', '카르나타카', 'IN_KARNATAKA', '카르나타카'),
    ('WHISKY', '인도', 'Karnataka', 'IN_KARNATAKA', '카르나타카'),
    ('WHISKY', '인도', '우타르프라데시', 'IN_UTTAR_PRADESH', '우타르프라데시'),
    ('WHISKY', '인도', 'Uttar Pradesh', 'IN_UTTAR_PRADESH', '우타르프라데시'),
    ('WHISKY', '인도', '하리아나', 'IN_HARYANA', '하리아나'),
    ('WHISKY', '인도', 'Haryana', 'IN_HARYANA', '하리아나'),
    ('WHISKY', '일본', 'Kagoshima', 'JP_KAGOSHIMA', '가고시마'),
    ('WHISKY', '일본', 'Nagano', 'JP_NAGANO', '나가노'),
    ('WHISKY', '일본', 'Toyama', 'JP_TOYAMA', '도야마'),
    ('WHISKY', '일본', 'Miyagi', 'JP_MIYAGI', '미야기'),
    ('WHISKY', '일본', 'Saitama', 'JP_SAITAMA', '사이타마'),
    ('WHISKY', '일본', 'Shiga', 'JP_SHIGA', '시가'),
    ('WHISKY', '일본', 'Shizuoka', 'JP_SHIZUOKA', '시즈오카'),
    ('WHISKY', '일본', 'Aichi', 'JP_AICHI', '아이치'),
    ('WHISKY', '일본', 'Yamanashi', 'JP_YAMANASHI', '야마나시'),
    ('WHISKY', '일본', 'Osaka', 'JP_OSAKA', '오사카'),
    ('WHISKY', '일본', 'Hokkaido', 'JP_HOKKAIDO', '홋카이도'),
    ('WHISKY', '일본', 'Hyogo', 'JP_HYOGO', '효고'),
    ('WHISKY', '일본', 'Fukushima', 'JP_FUKUSHIMA', '후쿠시마'),
    ('WHISKY', '일본', 'Hiroshima', 'JP_HIROSHIMA', '히로시마'),
    ('WHISKY', '잉글랜드', 'Norfolk', 'GB_ENG_NORFOLK', '노퍽'),
    ('WHISKY', '잉글랜드', 'Derbyshire', 'GB_ENG_DERBYSHIRE', '더비셔'),
    ('WHISKY', '잉글랜드', 'London', 'GB_ENG_LONDON', '런던'),
    ('WHISKY', '잉글랜드', 'Yorkshire', 'GB_ENG_YORKSHIRE', '요크셔'),
    ('WHISKY', '잉글랜드', 'Cumbria', 'GB_ENG_CUMBRIA', '컴브리아'),
    ('WHISKY', '잉글랜드', 'Cotswolds', 'GB_ENG_COTSWOLDS', '코츠월드'),
    ('WHISKY', '캐나다', 'Manitoba', 'CA_MANITOBA', '매니토바'),
    ('WHISKY', '캐나다', 'Alberta', 'CA_ALBERTA', '앨버타'),
    ('WHISKY', '캐나다', 'Ontario', 'CA_ONTARIO', '온타리오'),
    ('WHISKY', '프랑스', 'Brittany', 'FR_BRETAGNE', '브르타뉴'),
    ('WHISKY', '핀란드', '오스트로보스니아', 'FI_OSTROBOTHNIA', '오스트로보스니아'),
    ('WHISKY', '핀란드', 'Ostrobothnia', 'FI_OSTROBOTHNIA', '오스트로보스니아'),
    ('WHISKY', '호주', '빅토리아', 'AU_VICTORIA', '빅토리아'),
    ('WHISKY', '호주', 'Victoria', 'AU_VICTORIA', '빅토리아'),
    ('WHISKY', '호주', '웨스턴 오스트레일리아', 'AU_WESTERN_AUSTRALIA', '웨스턴 오스트레일리아'),
    ('WHISKY', '호주', 'Western Australia', 'AU_WESTERN_AUSTRALIA', '웨스턴 오스트레일리아'),
    ('WHISKY', '호주', 'Tasmania', 'AU_TASMANIA', '태즈메이니아'),
    ('WINE', '그리스', '마케도니아', 'GR_MACEDONIA', '마케도니아'),
    ('WINE', '그리스', 'Macedonia', 'GR_MACEDONIA', '마케도니아'),
    ('WINE', '그리스', '에게해 섬', 'GR_AEGEAN', '에게해 섬'),
    ('WINE', '그리스', 'Aegean Islands', 'GR_AEGEAN', '에게해 섬'),
    ('WINE', '남아공', '웨스트 코스트', 'ZA_WEST_COAST', '웨스트 코스트'),
    ('WINE', '남아공', 'West Coast', 'ZA_WEST_COAST', '웨스트 코스트'),
    ('WINE', '남아공', 'Stellenbosch', 'ZA_CAPE_WINELANDS_STELLENBOSCH', '케이프 와인랜드'),
    ('WINE', '남아공', '오버버그', 'ZA_OVERBERG', '오버버그'),
    ('WINE', '남아공', 'Overberg', 'ZA_OVERBERG', '오버버그'),
    ('WINE', '남아프리카공화국', 'Stellenbosch', 'ZA_CAPE_WINELANDS_STELLENBOSCH', '케이프 와인랜드'),
    ('WINE', '남아프리카공화국', '케이프타운', 'ZA_CAPE_TOWN', '케이프타운'),
    ('WINE', '남아프리카공화국', 'Cape Town', 'ZA_CAPE_TOWN', '케이프타운'),
    ('WINE', '남아프리카공화국', '프란슈크', 'ZA_CAPE_WINELANDS_FRANSCHHOEK', '케이프 와인랜드'),
    ('WINE', '남아프리카공화국', 'Franschhoek', 'ZA_CAPE_WINELANDS_FRANSCHHOEK', '케이프 와인랜드'),
    ('WINE', '뉴질랜드', '와이라라파', 'NZ_WAIRARAPA', '와이라라파'),
    ('WINE', '뉴질랜드', 'Wairarapa', 'NZ_WAIRARAPA', '와이라라파'),
    ('WINE', '뉴질랜드', 'Marlborough', 'NZ_MARLBOROUGH', '말버러'),
    ('WINE', '뉴질랜드', 'Central Otago', 'NZ_OTAGO_CENTRAL_OTAGO', '오타고'),
    ('WINE', '뉴질랜드', 'Auckland', 'NZ_AUCKLAND', '오클랜드'),
    ('WINE', '뉴질랜드', 'Hawke''s Bay', 'NZ_HAWKES_BAY', '호크스 베이'),
    ('WINE', '독일', '나헤', 'DE_NAHE', '나헤'),
    ('WINE', '독일', 'Nahe', 'DE_NAHE', '나헤'),
    ('WINE', '독일', 'Rheingau', 'DE_RHEINGAU', '라인가우'),
    ('WINE', '독일', 'Rheinhessen', 'DE_RHEINHESSEN', '라인헤센'),
    ('WINE', '독일', 'Mosel', 'DE_MOSEL', '모젤'),
    ('WINE', '독일', 'Baden', 'DE_BADEN', '바덴'),
    ('WINE', '레바논', 'Beqaa Valley', 'LB_BEQAA', '베카 밸리'),
    ('WINE', '미국', 'Napa Valley', 'US_CALIFORNIA_NAPA_VALLEY', '캘리포니아'),
    ('WINE', '미국', 'Sonoma County', 'US_CALIFORNIA_SONOMA', '캘리포니아'),
    ('WINE', '미국', 'Oregon', 'US_OREGON', '오리건'),
    ('WINE', '미국', 'Washington', 'US_WASHINGTON', '워싱턴'),
    ('WINE', '미국', '왈라 왈라', 'US_WASHINGTON_WALLA_WALLA', '워싱턴'),
    ('WINE', '미국', 'Walla Walla Valley', 'US_WASHINGTON_WALLA_WALLA', '워싱턴'),
    ('WINE', '미국', 'California', 'US_CALIFORNIA', '캘리포니아'),
    ('WINE', '미국', '파소 로블스', 'US_CALIFORNIA_PASO_ROBLES', '캘리포니아'),
    ('WINE', '미국', 'Paso Robles', 'US_CALIFORNIA_PASO_ROBLES', '캘리포니아'),
    ('WINE', '스페인', 'Ribera del Duero', 'ES_CASTILLA_Y_LEON_RIBERA_DEL_DUERO', '카스티야 이 레온'),
    ('WINE', '스페인', 'Rías Baixas', 'ES_GALICIA_RIAS_BAIXAS', '갈리시아'),
    ('WINE', '스페인', 'Rioja', 'ES_RIOJA', '리오하'),
    ('WINE', '스페인', '헤레스', 'ES_ANDALUCIA_JEREZ', '안달루시아'),
    ('WINE', '스페인', 'Jerez-Xérès-Sherry', 'ES_ANDALUCIA_JEREZ', '안달루시아'),
    ('WINE', '스페인', 'Castilla y León', 'ES_CASTILLA_Y_LEON', '카스티야 이 레온'),
    ('WINE', '스페인', '카탈루냐', 'ES_CATALUNYA', '카탈루냐'),
    ('WINE', '스페인', 'Catalonia', 'ES_CATALUNYA', '카탈루냐'),
    ('WINE', '스페인', '페네데스', 'ES_CATALUNYA_PENEDES', '카탈루냐'),
    ('WINE', '스페인', 'Penedès', 'ES_CATALUNYA_PENEDES', '카탈루냐'),
    ('WINE', '스페인', 'Toro', 'ES_CASTILLA_Y_LEON_TORO', '카스티야 이 레온'),
    ('WINE', '스페인', 'Priorat', 'ES_CATALUNYA_PRIORAT', '카탈루냐'),
    ('WINE', '스페인', 'Jumilla', 'ES_MURCIA_JUMILLA', '무르시아'),
    ('WINE', '아르헨티나', 'Mendoza', 'AR_MENDOZA', '멘도사'),
    ('WINE', '아르헨티나', '살타', 'AR_SALTA', '살타'),
    ('WINE', '아르헨티나', 'Salta', 'AR_SALTA', '살타'),
    ('WINE', '오스트리아', 'Wachau', 'AT_NIEDEROSTERREICH_WACHAU', '니더외스터라이히'),
    ('WINE', '오스트리아', 'Kamptal', 'AT_NIEDEROSTERREICH_KAMPTAL', '니더외스터라이히'),
    ('WINE', '우루과이', 'Maldonado', 'UY_MALDONADO', '마이도나도'),
    ('WINE', '이탈리아', '롬바르디아', 'IT_LOMBARDIA', '롬바르디아'),
    ('WINE', '이탈리아', 'Lombardy', 'IT_LOMBARDIA', '롬바르디아'),
    ('WINE', '이탈리아', 'Veneto', 'IT_VENETO', '베네토'),
    ('WINE', '이탈리아', '소아베', 'IT_VENETO_SOAVE', '베네토'),
    ('WINE', '이탈리아', 'Soave', 'IT_VENETO_SOAVE', '베네토'),
    ('WINE', '이탈리아', 'Sardinia', 'IT_SARDEGNA', '사르데냐'),
    ('WINE', '이탈리아', 'Sicily', 'IT_SICILIA', '시칠리아'),
    ('WINE', '이탈리아', '트렌티노 알토 아디제', 'IT_TRENTINO_ALTO_ADIGE', '트렌티노 알토 아디제'),
    ('WINE', '이탈리아', 'Trentino-Alto Adige', 'IT_TRENTINO_ALTO_ADIGE', '트렌티노 알토 아디제'),
    ('WINE', '이탈리아', 'Campania', 'IT_CAMPANIA', '캄파니아'),
    ('WINE', '이탈리아', 'Tuscany', 'IT_TOSCANA', '토스카나'),
    ('WINE', '이탈리아', 'Friuli-Venezia Giulia', 'IT_FRIULI', '프리울리'),
    ('WINE', '이탈리아', 'Piedmont', 'IT_PIEMONTE', '피에몬테'),
    ('WINE', '인도', '마하라슈트라', 'IN_MAHARASHTRA', '마하라슈트라'),
    ('WINE', '인도', 'Maharashtra', 'IN_MAHARASHTRA', '마하라슈트라'),
    ('WINE', '인도', '카르나타카', 'IN_KARNATAKA', '카르나타카'),
    ('WINE', '인도', 'Karnataka', 'IN_KARNATAKA', '카르나타카'),
    ('WINE', '일본', '도치기', 'JP_TOCHIGI', '도치기'),
    ('WINE', '일본', 'Tochigi', 'JP_TOCHIGI', '도치기'),
    ('WINE', '일본', 'Yamanashi', 'JP_YAMANASHI', '야마나시'),
    ('WINE', '조지아', 'Kakheti', 'GE_KAKHETI', '카헤티'),
    ('WINE', '중국', 'Ningxia', 'CN_NINGXIA', '닝샤'),
    ('WINE', '중국', '산둥', 'CN_SHANDONG', '산둥'),
    ('WINE', '중국', 'Shandong', 'CN_SHANDONG', '산둥'),
    ('WINE', '중국', '산시', 'CN_SHANXI', '산시'),
    ('WINE', '중국', 'Shanxi', 'CN_SHANXI', '산시'),
    ('WINE', '중국', 'Yunnan', 'CN_YUNNAN', '윈난'),
    ('WINE', '칠레', 'Maipo Valley', 'CL_CENTRAL_VALLEY_MAIPO', '센트럴 밸리'),
    ('WINE', '칠레', 'Aconcagua', 'CL_ACONCAGUA', '아콩카과'),
    ('WINE', '칠레', 'Colchagua Valley', 'CL_CENTRAL_VALLEY_COLCHAGUA', '센트럴 밸리'),
    ('WINE', '캐나다', 'Ontario', 'CA_ONTARIO', '온타리오'),
    ('WINE', '포르투갈', 'Douro', 'PT_DOURO', '도루'),
    ('WINE', '포르투갈', 'Madeira', 'PT_MADEIRA', '마데이라'),
    ('WINE', '포르투갈', 'Bairrada', 'PT_BAIRRADA', '바이라다'),
    ('WINE', '포르투갈', 'Alentejo', 'PT_ALENTEJO', '알렌테주'),
    ('WINE', '프랑스', 'Rhône Valley', 'FR_RHONE', '론'),
    ('WINE', '프랑스', 'Loire Valley', 'FR_LOIRE', '루아르'),
    ('WINE', '프랑스', '부브레', 'FR_LOIRE_VOUVRAY', '루아르'),
    ('WINE', '프랑스', 'Vouvray', 'FR_LOIRE_VOUVRAY', '루아르'),
    ('WINE', '프랑스', 'Bordeaux', 'FR_BORDEAUX', '보르도'),
    ('WINE', '프랑스', 'Beaujolais', 'FR_BEAUJOLAIS', '보졸레'),
    ('WINE', '프랑스', 'Burgundy', 'FR_BOURGOGNE', '부르고뉴'),
    ('WINE', '프랑스', '샹파뉴', 'FR_CHAMPAGNE', '샹파뉴'),
    ('WINE', '프랑스', 'Champagne', 'FR_CHAMPAGNE', '샹파뉴'),
    ('WINE', '프랑스', 'Alsace', 'FR_ALSACE', '알자스'),
    ('WINE', '프랑스', 'Provence', 'FR_PROVENCE', '프로방스'),
    ('WINE', '헝가리', 'Tokaj', 'HU_TOKAJ', '토카이'),
    ('WINE', '호주', 'New South Wales', 'AU_NEW_SOUTH_WALES', '뉴사우스웨일스'),
    ('WINE', '호주', 'Margaret River', 'AU_WESTERN_AUSTRALIA_MARGARET_RIVER', '웨스턴 오스트레일리아'),
    ('WINE', '호주', 'McLaren Vale', 'AU_SOUTH_AUSTRALIA_MCLAREN_VALE', '사우스 오스트레일리아'),
    ('WINE', '호주', 'Barossa Valley', 'AU_SOUTH_AUSTRALIA_BAROSSA_VALLEY', '사우스 오스트레일리아'),
    ('WINE', '호주', 'Victoria', 'AU_VICTORIA', '빅토리아'),
    ('WINE', '호주', '사우스 오스트레일리아', 'AU_SOUTH_AUSTRALIA', '사우스 오스트레일리아'),
    ('WINE', '호주', 'South Australia', 'AU_SOUTH_AUSTRALIA', '사우스 오스트레일리아'),
    ('WINE', '호주', '클레어 밸리', 'AU_SOUTH_AUSTRALIA_CLARE_VALLEY', '사우스 오스트레일리아'),
    ('WINE', '호주', 'Clare Valley', 'AU_SOUTH_AUSTRALIA_CLARE_VALLEY', '사우스 오스트레일리아'),
    ('WINE', '호주', 'Yarra Valley', 'AU_VICTORIA_YARRA_VALLEY', '빅토리아'),
    ('WINE', '호주', '웨스턴 오스트레일리아', 'AU_WESTERN_AUSTRALIA', '웨스턴 오스트레일리아'),
    ('WINE', '호주', 'Western Australia', 'AU_WESTERN_AUSTRALIA', '웨스턴 오스트레일리아'),
    ('WINE', '호주', '캔버라 디스트릭트', 'AU_NEW_SOUTH_WALES_CANBERRA_DISTRICT', '뉴사우스웨일스'),
    ('WINE', '호주', 'Canberra District', 'AU_NEW_SOUTH_WALES_CANBERRA_DISTRICT', '뉴사우스웨일스'),
    ('WINE', '호주', 'Hunter Valley', 'AU_NEW_SOUTH_WALES_HUNTER_VALLEY', '뉴사우스웨일스');

-- 생산자 원문 region 은 위치 설명과 운영 확인에 계속 사용하므로 보존한다.
UPDATE producer p
JOIN tmp_legacy_region_mapping m
  ON m.category = CASE p.type
        WHEN 'DISTILLERY' THEN 'WHISKY'
        WHEN 'WINERY' THEN 'WINE'
        WHEN 'COGNAC_HOUSE' THEN 'COGNAC'
        WHEN 'OTHER' THEN 'OTHER'
     END
 AND m.country = TRIM(p.country)
 AND m.legacy_region = TRIM(p.region)
SET p.region_code = m.region_code
WHERE p.region_code IS NULL;

-- 기존 검색·필터·SEO 가 쓰는 spirit.region 은 현재 규약대로 L1 한글명으로 동기화한다.
UPDATE spirit s
JOIN tmp_legacy_region_mapping m
  ON m.category = s.category
 AND m.country = TRIM(s.country)
 AND m.legacy_region = TRIM(s.region)
SET s.region_code = m.region_code,
    s.region = m.canonical_l1_name
WHERE s.region_code IS NULL;

-- 에디션은 마스터와 같은 산지 코드를 사용한다.
UPDATE spirit child
JOIN spirit parent ON parent.id = child.parent_id
SET child.region_code = parent.region_code,
    child.region = parent.region
WHERE child.region_code IS NULL
  AND parent.region_code IS NOT NULL;

DROP TEMPORARY TABLE tmp_legacy_region_mapping;
