-- =============================================================================
-- CaskByCask 기초데이터 — 꼬냑 하우스 (Cognac house seed)
-- =============================================================================
-- 통합: 구 V4(메인) + 구 V14(보강) 의 꼬냑 INSERT + 구 V9 의 Camus 검색 별칭.
-- producer.type 은 기본값 없는 NOT NULL → INSERT 동안만 'COGNAC_HOUSE' 기본값을 지정 후 해제.
-- =============================================================================

ALTER TABLE producer ALTER COLUMN type SET DEFAULT 'COGNAC_HOUSE';

INSERT INTO producer
    (name_ko, name_en, country, region, website, founded_year, description_ko, description_en, created_at, updated_at)
VALUES
-- ===================== 대형 메종 (Major houses) =====================
('헤네시', 'Hennessy', '프랑스', '꼬냑', 'https://www.hennessy.com', 1765,
 '세계 최대의 꼬냑 메종. VSOP·XO 등급의 기준을 세웠으며 전 세계 꼬냑 판매의 큰 비중을 차지한다.',
 'The world''s largest Cognac house, which helped define the VSOP and XO grades and accounts for a large share of global Cognac sales.',
 NOW(6), NOW(6)),
('레미 마르탱', 'Rémy Martin', '프랑스', '꼬냑', 'https://www.remymartin.com', 1724,
 '그랑드/프티트 샹파뉴 끄뤼만 사용하는 ''핀 샹파뉴'' 꼬냑으로 유명한 메종. 켄타우로스 로고가 상징이다.',
 'A house famed for "Fine Champagne" Cognac sourced only from the Grande and Petite Champagne crus, symbolised by its centaur logo.',
 NOW(6), NOW(6)),
('마르텔', 'Martell', '프랑스', '꼬냑', 'https://www.martell.com', 1715,
 '현존하는 가장 오래된 대형 꼬냑 메종 중 하나. 부드럽고 우아한 스타일로 정평이 나 있다.',
 'One of the oldest of the great Cognac houses still operating, esteemed for its smooth, elegant style.',
 NOW(6), NOW(6)),
('쿠르부아지에', 'Courvoisier', '프랑스', '꼬냑', 'https://www.courvoisier.com', 1809,
 '''나폴레옹의 꼬냑''으로 알려진 자르낙의 메종. 4대 메이저 꼬냑 하우스 중 하나다.',
 'A Jarnac house known as "the Cognac of Napoleon," one of the four major Cognac houses.',
 NOW(6), NOW(6)),
('카뮈', 'Camus', '프랑스', '꼬냑', 'https://www.camus.fr', 1863,
 '5대째 이어지는 세계 최대의 독립 가족 꼬냑 메종. 보르드리 끄뤼 중심의 향기로운 스타일이 특징이다.',
 'The largest independent family-owned Cognac house, in its fifth generation, known for an aromatic, Borderies-driven style.',
 NOW(6), NOW(6)),
('비스키', 'Bisquit & Dubouché', '프랑스', '꼬냑', NULL, 1819,
 '알렉상드르 비스키가 설립한 역사적 메종. 루야크의 대규모 증류소를 갖췄으며 현재 남아공 디스텔 그룹 소유다.',
 'A historic house founded by Alexandre Bisquit, with a large distillery at Rouillac, now owned by South Africa''s Distell group.',
 NOW(6), NOW(6)),
('루이 루아예', 'Louis Royer', '프랑스', '꼬냑', 'https://www.louis-royer.com', 1853,
 '벌집 로고로 알려진 자르낙의 메종. 폭넓은 끄뤼의 균형 잡힌 블렌드로 유명하다.',
 'A Jarnac house known by its honeybee logo, recognised for balanced blends drawn from a wide range of crus.',
 NOW(6), NOW(6)),
('뫼코', 'Meukow', '프랑스', '꼬냑', 'https://www.meukow.com', 1862,
 '검은 표범 보틀로 유명한 메종. 본래 러시아 황실 공급을 위해 설립되었다.',
 'A house famous for its black panther bottle, originally established to supply the Russian Imperial court.',
 NOW(6), NOW(6)),
-- ===================== 프레스티지 독립 메종 (Prestige houses) =====================
('하인', 'Hine', '프랑스', '꼬냑', 'https://www.hine.com', 1763,
 '자르낙의 명문 메종. 영국 왕실 납품 인증을 받았으며 우아하고 섬세한 ''얼리 랜디드'' 꼬냑으로 유명하다.',
 'A prestigious Jarnac house, holder of a British Royal Warrant, famed for its elegant, "Early Landed" Cognacs.',
 NOW(6), NOW(6)),
('바롱 오타르 (샤토 드 꼬냑)', 'Baron Otard (Château de Cognac)', '프랑스', '꼬냑', 'https://www.baronotard.com', 1795,
 '프랑수아 1세가 태어난 꼬냑 성(샤토 드 꼬냑)에서 숙성하는 역사적 메종.',
 'A historic house ageing its Cognac in the Château de Cognac, the castle where King François I was born.',
 NOW(6), NOW(6)),
('A. 아르디', 'A. Hardy', '프랑스', '꼬냑', 'https://www.cognac-hardy.com', 1863,
 '영국계 가문이 세운 독립 가족 메종. 고숙성·럭셔리 보틀(노아·페를르 등)로 유명하다.',
 'An independent family house of British origin, known for its aged, luxury decanters such as Noces and Perfection.',
 NOW(6), NOW(6)),
('고티에', 'Gautier', '프랑스', '꼬냑', NULL, 1755,
 '현존하는 가장 오래된 꼬냑 메종 중 하나. 18세기 왕실 인가를 받은 유서 깊은 생산자다.',
 'One of the oldest surviving Cognac houses, a heritage producer granted royal authorisation in the 18th century.',
 NOW(6), NOW(6)),
('메종 페랑 (피에르 페랑)', 'Maison Ferrand (Pierre Ferrand)', '프랑스', '꼬냑', 'https://www.cognacferrand.com', 1989,
 '알렉상드르 가브리엘이 부활시킨 그랑드 샹파뉴 메종. 페랑 가문 내력은 더 오래되었으며 장인적 꼬냑으로 정평이 나 있다.',
 'A Grande Champagne house revived by Alexandre Gabriel; the Ferrand family''s roots run deeper, and it is acclaimed for artisanal Cognac.',
 NOW(6), NOW(6)),
('파크', 'Park (Tessendier)', '프랑스', '꼬냑', 'https://www.cognacpark.com', 1880,
 '테센디에 가문이 운영하는 메종의 대표 브랜드. 정교한 블렌딩으로 국제 시장에서 호평받는다.',
 'The flagship brand of the Tessendier family''s house, well received internationally for its meticulous blending.',
 NOW(6), NOW(6)),
('테세롱', 'Tesseron', '프랑스', '꼬냑', NULL, 1905,
 '방대한 고숙성 원액 재고로 유명한 가족 메종. 빈티지·숙성 단계(로트) 표기 꼬냑으로 잘 알려져 있다.',
 'A family house famed for its vast stocks of very old eaux-de-vie, well known for its "Lot"-numbered, extra-aged Cognacs.',
 NOW(6), NOW(6)),
('프뤼니에', 'Prunier', '프랑스', '꼬냑', 'https://www.prunier-cognac.com', 1700,
 '1700년 기원을 주장하는 가장 오래된 꼬냑 무역 가문 중 하나. 고숙성·빈티지 꼬냑으로 정평이 나 있다.',
 'One of the oldest Cognac trading families, claiming origins in 1700, esteemed for its aged and vintage Cognacs.',
 NOW(6), NOW(6)),
('A. 드 퓌시니', 'A. de Fussigny', '프랑스', '꼬냑', NULL, 1814,
 '소규모 장인 메종으로, 끄뤼·빈티지를 강조한 개성 있는 꼬냑으로 애호가들에게 알려져 있다.',
 'A small artisanal house known among connoisseurs for characterful Cognacs emphasising specific crus and vintages.',
 NOW(6), NOW(6)),
-- ===================== 그랑드 샹파뉴 싱글 이스테이트 / 그로어 (Grower-producers) =====================
('프라팽', 'Frapin', '프랑스', '꼬냑', 'https://www.cognac-frapin.com', 1270,
 '그랑드 샹파뉴 단일 끄뤼의 자체 포도밭만 사용하는 ''싱글 에스테이트'' 꼬냑 명가. 가문 내력이 수백 년에 이른다.',
 'A "single estate" house using only its own Grande Champagne single-cru vineyards, with a family lineage stretching back centuries.',
 NOW(6), NOW(6)),
('들라맹', 'Delamain', '프랑스', '꼬냑', 'https://www.delamain-cognac.com', 1824,
 '그랑드 샹파뉴 고숙성 꼬냑만 전문으로 하는 소규모 명가. 섬세하고 드라이한 스타일로 추앙받는다.',
 'A small house specialising exclusively in aged Grande Champagne Cognac, revered for its delicate, dry style.',
 NOW(6), NOW(6)),
('라뇨 사부랭', 'Ragnaud-Sabourin', '프랑스', '꼬냑', NULL, 1850,
 '그랑드 샹파뉴의 명문 그로어 가문. 자체 재배·증류·숙성으로 만든 고품질 싱글 이스테이트 꼬냑으로 유명하다.',
 'A celebrated Grande Champagne grower family, renowned for high-quality single-estate Cognac grown, distilled and aged in-house.',
 NOW(6), NOW(6)),
('장 피유', 'Jean Fillioux', '프랑스', '꼬냑', 'https://www.jeanfillioux.com', 1880,
 '쥐야크르코크의 그랑드 샹파뉴 그로어. 단일 밭 ''라 푸야드'' 등 장인적 꼬냑으로 애호가들의 사랑을 받는다.',
 'A Grande Champagne grower in Juillac-le-Coq, beloved by enthusiasts for artisanal Cognacs such as its single-vineyard "La Pouyade".',
 NOW(6), NOW(6)),
('프랑수아 부아예', 'François Voyer', '프랑스', '꼬냑', 'https://www.francois-voyer.com', 1870,
 '그랑드 샹파뉴의 가족 경영 그로어. 순수하고 우아한 싱글 끄뤼 꼬냑으로 정평이 나 있다.',
 'A family-run Grande Champagne grower esteemed for its pure, elegant single-cru Cognacs.',
 NOW(6), NOW(6)),
('다니엘 부주', 'Daniel Bouju', '프랑스', '꼬냑', NULL, 1805,
 '그랑드 샹파뉴의 전통 그로어. 고도수·무가당·무착색의 내추럴한 스타일로 마니아층의 지지를 받는다.',
 'A traditional Grande Champagne grower with a cult following for its natural style — high proof, no added sugar or colouring.',
 NOW(6), NOW(6)),
('노르망댕 메르시에', 'Normandin-Mercier', '프랑스', '꼬냑', 'https://www.normandin-mercier.com', 1872,
 '라로셸 인근에서 해양성 셀러 숙성을 하는 가족 메종. 프티트 샹파뉴 중심의 섬세한 꼬냑을 만든다.',
 'A family house ageing in maritime cellars near La Rochelle, producing delicate Cognac centred on Petite Champagne.',
 NOW(6), NOW(6)),
('레로 (르로)', 'Lhéraud', '프랑스', '꼬냑', 'https://www.lheraud.com', 1680,
 '프티트 샹파뉴의 그로어 가문. 빈티지 꼬냑과 진하고 풍미 가득한 스타일로 잘 알려져 있다.',
 'A Petite Champagne grower family well known for vintage-dated Cognacs and a rich, full-flavoured style.',
 NOW(6), NOW(6));

INSERT INTO producer
    (name_ko, name_en, country, region, website, founded_year, description_ko, description_en, created_at, updated_at)
VALUES
('고데', 'Godet', '프랑스', '꼬냑', 'https://www.godet.fr', 1838,
 '라로셸에 본거지를 둔 역사적 가족 메종. 가문 내력은 16세기까지 거슬러 올라가며 섬세한 스타일로 유명하다.',
 'A historic family house based in La Rochelle, with roots tracing to the 16th century, known for its delicate style.',
 NOW(6), NOW(6)),
('라르센', 'Larsen', '프랑스', '꼬냑', 'https://www.larsencognac.com', 1926,
 '노르웨이 출신 옌스 라르센이 세운 메종. 바이킹 배 모양 보틀로 스칸디나비아·아시아에서 큰 인기를 누린다.',
 'A house founded by Norwegian-born Jens Reidar Larsen, hugely popular in Scandinavia and Asia for its Viking-ship bottles.',
 NOW(6), NOW(6)),
('바슈-가브리엘센', 'Bache-Gabrielsen', '프랑스', '꼬냑', 'https://www.bache-gabrielsen.com', 1905,
 '노르웨이계 가문이 세운 자르낙의 가족 메종. 보르드리 끄뤼 중심의 균형 잡힌 스타일로 정평이 나 있다.',
 'A Jarnac family house of Norwegian origin, esteemed for a balanced style centred on the Borderies cru.',
 NOW(6), NOW(6)),
('브라스타드 (티퐁)', 'Braastad (Tiffon)', '프랑스', '꼬냑', 'https://www.cognac-tiffon.com', 1875,
 '티퐁 메종이 운영하는 브랜드. 노르웨이계 브라스타드 가문이 이끌며 자체 포도밭과 숙성고를 갖췄다.',
 'A brand of the Tiffon house, led by the Norwegian-descended Braastad family, with its own vineyards and cellars.',
 NOW(6), NOW(6)),
('드 뤼즈', 'De Luze', '프랑스', '꼬냑', 'https://www.deluze.com', 1822,
 '보르도 무역에서 출발한 역사적 메종. 핀 샹파뉴 중심의 우아하고 향기로운 꼬냑으로 알려져 있다.',
 'A historic house with roots in the Bordeaux trade, known for elegant, aromatic Fine Champagne Cognac.',
 NOW(6), NOW(6)),
('막심 트리욜', 'Maxime Trijol', '프랑스', '꼬냑', 'https://www.maximetrijol.com', 1859,
 '대규모 증류 설비를 갖춘 가족 생산자. 자체 증류와 폭넓은 끄뤼로 다수 브랜드에 원액을 공급한다.',
 'A family producer with large distillation capacity, supplying spirit to many brands through its own stills and wide range of crus.',
 NOW(6), NOW(6)),
('크루아제', 'Croizet', '프랑스', '꼬냑', NULL, 1805,
 '그랑드 샹파뉴의 역사적 가족 메종. 희소한 빈티지 꼬냑으로 컬렉터들에게 잘 알려져 있다.',
 'A historic Grande Champagne family house, well known to collectors for its rare vintage Cognacs.',
 NOW(6), NOW(6)),
('샤토 드 몽티포', 'Château de Montifaud', '프랑스', '꼬냑', 'https://www.montifaud.com', 1866,
 '프티트 샹파뉴의 명문 그로어(발레 가문). 자체 재배·증류·숙성하는 싱글 이스테이트 꼬냑으로 애호가들의 사랑을 받는다.',
 'A renowned Petite Champagne grower (the Vallet family), beloved by enthusiasts for single-estate Cognac grown, distilled and aged in-house.',
 NOW(6), NOW(6)),
('폴 지로', 'Paul Giraud', '프랑스', '꼬냑', NULL, 1937,
 '부트빌의 그랑드 샹파뉴 그로어. 무가당·무착색에 가까운 순수하고 진한 싱글 끄뤼 꼬냑으로 유명하다.',
 'A Grande Champagne grower in Bouteville famed for pure, rich single-cru Cognac with little or no added sugar or colouring.',
 NOW(6), NOW(6)),
('발랭 테르시니에', 'Vallein Tercinier', '프랑스', '꼬냑', 'https://www.cognac-vallein-tercinier.com', 1850,
 '5대째 이어지는 그로어 가문. 내추럴(무가당·무착색) 스타일과 ''로트'' 표기 꼬냑으로 애호가들에게 큰 인기를 누린다.',
 'A fifth-generation grower family with a strong enthusiast following for its natural (no sugar or colouring) style and "Lot"-numbered Cognacs.',
 NOW(6), NOW(6)),
('그로스페랭', 'Grosperrin', '프랑스', '꼬냑', 'https://www.grosperrin.com', 1992,
 '오래된 빈티지·끄뤼 원액을 발굴·병입하는 것으로 유명한 전문 하우스. 희소한 고숙성 꼬냑으로 추앙받는다.',
 'A house famed for sourcing and bottling old vintage and single-cru eaux-de-vie, revered for rare extra-aged Cognacs.',
 NOW(6), NOW(6)),
('ABK6', 'ABK6', '프랑스', '꼬냑', 'https://www.abk6-cognac.com', 2010,
 '아베카시스 가문의 싱글 이스테이트 꼬냑 브랜드. 자체 포도밭에서 일관 생산하는 현대적 스타일로 인기를 얻고 있다.',
 'A single-estate Cognac brand of the Abécassis family, gaining popularity for a modern style produced end-to-end from its own vineyards.',
 NOW(6), NOW(6)),
('뒤도뇽', 'Dudognon', '프랑스', '꼬냑', NULL, 1776,
 '그랑드 샹파뉴의 전통 그로어 가문. 자체 재배·증류한 진하고 풍미 가득한 싱글 끄뤼 꼬냑으로 알려져 있다.',
 'A traditional Grande Champagne grower family, known for rich, full-flavoured single-cru Cognac grown and distilled in-house.',
 NOW(6), NOW(6)),
('오드리', 'Audry', '프랑스', '꼬냑', NULL, 1878,
 '소량 생산의 프레스티지 메종. 고숙성·빈티지 꼬냑과 정교한 디캔터로 애호가들에게 잘 알려져 있다.',
 'A small-production prestige house well known among connoisseurs for aged, vintage Cognacs and elegant decanters.',
 NOW(6), NOW(6)),
('도 (부아노)', 'Deau (Boinaud)', '프랑스', '꼬냑', 'https://www.cognac-deau.com', 1846,
 '꼬냑 최대급 자가 포도밭을 보유한 부아노 도멘의 브랜드. 싱글 이스테이트 기반의 안정적 품질로 유명하다.',
 'A brand of the Boinaud estate, holder of one of Cognac''s largest family-owned vineyards, known for consistent single-estate quality.',
 NOW(6), NOW(6)),
('장-뤽 파스케', 'Jean-Luc Pasquet', '프랑스', '꼬냑', 'https://www.jeanlucpasquet.com', 1730,
 '그랑드 샹파뉴의 유기농 그로어 가문. 무가당·무착색의 ''내추럴'' 빈티지 꼬냑으로 애호가들에게 추앙받는다.',
 'An organic Grande Champagne grower family revered by enthusiasts for its natural, no-sugar, no-colouring vintage Cognacs.',
 NOW(6), NOW(6));

-- 카뮈(Camus) — 국내 통용 표기 '까뮤'로도 검색되도록 별칭 부여 (구 V9)
UPDATE producer SET search_keywords = '까뮤 까뮈 Camus' WHERE name_en = 'Camus';

ALTER TABLE producer ALTER COLUMN type DROP DEFAULT;
