package com.drinkindex.domain.score.entity.enums;

public enum ScoreActionType {
    POST_WRITE_GENERAL,
    POST_WRITE_QUESTION,
    POST_WRITE_REVIEW,
    POST_WRITE_SHARING,
    POST_WRITE_DISTILLERY_TOUR,
    POST_WRITE_NOTICE,
    POST_DELETE,
    POST_LOCKED,
    POST_LIKED,
    COMMENT_WRITE,
    SPIRIT_REVIEW_WRITE,
    SPIRIT_REQUEST,
    SPIRIT_REQUEST_APPROVED,
    WISHLIST_ADD,
    ATTENDANCE,
    ATTENDANCE_STREAK_7,
    ATTENDANCE_STREAK_30,
    ADMIN_ADJUST
}
