package com.caskbycask.domain.spirit.entity.enums;

public enum WhiskyCaskType {
    EX_BOURBON,
    EX_SHERRY,
    EX_FINO,
    EX_MANZANILLA,
    EX_AMONTILLADO,
    EX_OLOROSO,
    EX_PALO_CORTADO,
    EX_PX,
    EX_PORT,
    EX_MADEIRA,
    EX_SAUTERNES,
    EX_MARSALA,
    EX_MALAGA,
    EX_TOKAJI,
    EX_VERMOUTH,
    EX_WINE,
    VINO_BARRIQUE,
    EX_RUM,
    EX_COGNAC,
    EX_BRANDY,
    EX_CALVADOS,
    EX_ARMAGNAC,
    EX_MEZCAL_TEQUILA,
    EX_BEER,
    NEW_OAK, // 뉴(버진) 오크 — 버진 오크와 동일 개념으로 통합
    FRENCH_OAK,
    CHINKAPIN,
    MIZUNARA,
    EX_UMESHU,
    TEAK_WOOD,
    PEATED_CASK,
    OTHER
}
