// 출처: BNIC (Bureau National Interprofessionnel du Cognac) Aroma Wheel
// https://www.cognac.fr/wp-content/uploads/20240228_210x297mm_roue_des_aromes_uk_vect.pdf
import type { AromaCategory } from './whiskyAromas'

export const COGNAC_AROMA_CATEGORIES: AromaCategory[] = [
  // ── SPRING · 봄 ───────────────────────────────────────────────────
  {
    id: 'cg_spring',
    ko: '봄 (꽃향)',
    en: 'Spring (Floral)',
    items: [
      { id: 'cg_almond',         icon: '🌰', ko: '아몬드',      en: 'Almond' },
      { id: 'cg_fleur_de_vigne', icon: '🍇', ko: '포도나무꽃',  en: 'Fleur de Vigne' },
      { id: 'cg_menthol',        icon: '🌱', ko: '멘톨',        en: 'Menthol' },
      { id: 'cg_rose',           icon: '🌹', ko: '장미',        en: 'Rose' },
      { id: 'cg_acacia',         icon: '🌼', ko: '아카시아',    en: 'Acacia' },
      { id: 'cg_may_blossom',    icon: '🌸', ko: '산사나무꽃',  en: 'May Blossom' },
      { id: 'cg_iris',           icon: '💜', ko: '아이리스',    en: 'Iris' },
      { id: 'cg_jasmin',         icon: '🌸', ko: '재스민',      en: 'Jasmin' },
      { id: 'cg_lilac',          icon: '💜', ko: '라일락',      en: 'Lilac' },
      { id: 'cg_butter',         icon: '🧈', ko: '버터',        en: 'Butter' },
      { id: 'cg_honeysuckle',    icon: '🌼', ko: '인동초',      en: 'Honeysuckle' },
      { id: 'cg_orange_blossom', icon: '🌸', ko: '오렌지꽃',    en: 'Orange Blossom' },
      { id: 'cg_violet',         icon: '🟣', ko: '제비꽃',      en: 'Violet' },
    ],
  },
  // ── SUMMER · 여름 ─────────────────────────────────────────────────
  {
    id: 'cg_summer',
    ko: '여름 (과일향)',
    en: 'Summer (Fruity)',
    items: [
      { id: 'cg_wild_carnation', icon: '🌸', ko: '야생 카네이션', en: 'Wild Carnation' },
      { id: 'cg_orange',         icon: '🍊', ko: '오렌지',        en: 'Orange' },
      { id: 'cg_lime',           icon: '🍈', ko: '라임',          en: 'Lime' },
      { id: 'cg_flower_tea',     icon: '🍵', ko: '꽃차',          en: 'Flower Tea' },
      { id: 'cg_apricot',        icon: '🍑', ko: '살구',          en: 'Apricot' },
      { id: 'cg_banana',         icon: '🍌', ko: '바나나',        en: 'Banana' },
      { id: 'cg_lemon',          icon: '🍋', ko: '레몬',          en: 'Lemon' },
      { id: 'cg_fresh_fig',      icon: '🌰', ko: '생무화과',      en: 'Fresh Fig' },
      { id: 'cg_peach',          icon: '🍑', ko: '복숭아',        en: 'Peach' },
      { id: 'cg_plum',           icon: '🟣', ko: '자두',          en: 'Plum' },
      { id: 'cg_hay',            icon: '🌾', ko: '건초',          en: 'Hay' },
      { id: 'cg_passion_fruit',  icon: '🌺', ko: '패션프루트',    en: 'Passion Fruit' },
      { id: 'cg_mango',          icon: '🥭', ko: '망고',          en: 'Mango' },
      { id: 'cg_rose_petals',    icon: '🌹', ko: '장미꽃잎',      en: 'Rose Petals' },
      { id: 'cg_pear',           icon: '🍐', ko: '배',            en: 'Pear' },
    ],
  },
  // ── AUTUMN · 가을 ─────────────────────────────────────────────────
  {
    id: 'cg_autumn',
    ko: '가을 (향신료)',
    en: 'Autumn (Spicy)',
    items: [
      { id: 'cg_dried_apricot',   icon: '🍑', ko: '살구건조',      en: 'Dried Apricot' },
      { id: 'cg_caramel',         icon: '🍮', ko: '카라멜',        en: 'Caramel' },
      { id: 'cg_mushroom',        icon: '🍄', ko: '버섯',          en: 'Mushroom' },
      { id: 'cg_chocolate_cocoa', icon: '🍫', ko: '초콜릿/코코아', en: 'Chocolate/Cocoa' },
      { id: 'cg_dried_fig',       icon: '🌰', ko: '무화과건조',    en: 'Dried Fig' },
      { id: 'cg_apple',           icon: '🍎', ko: '사과',          en: 'Apple' },
      { id: 'cg_muscat_grape',    icon: '🍇', ko: '머스캣 포도',   en: 'Muscat Grape' },
      { id: 'cg_saffron',         icon: '🌸', ko: '사프란',        en: 'Saffron' },
      { id: 'cg_cinnamon',        icon: '🌿', ko: '시나몬',        en: 'Cinnamon' },
      { id: 'cg_clove',           icon: '🟤', ko: '정향',          en: 'Clove' },
      { id: 'cg_ginger',          icon: '🫚', ko: '생강',          en: 'Ginger' },
      { id: 'cg_coconut',         icon: '🥥', ko: '코코넛',        en: 'Coconut' },
      { id: 'cg_nutmeg',          icon: '🟤', ko: '육두구',        en: 'Nutmeg' },
      { id: 'cg_liquorice',       icon: '🖤', ko: '감초',          en: 'Liquorice' },
      { id: 'cg_toffee',          icon: '🍬', ko: '토피',          en: 'Toffee' },
    ],
  },
  // ── WINTER · 겨울 ─────────────────────────────────────────────────
  {
    id: 'cg_winter',
    ko: '겨울 (우디)',
    en: 'Winter (Wooded)',
    items: [
      { id: 'cg_candied_fruit',  icon: '🍬', ko: '설탕절임 과일',    en: 'Candied Fruit' },
      { id: 'cg_lychee',         icon: '🔴', ko: '리치',             en: 'Lychee' },
      { id: 'cg_hazelnut',       icon: '🌰', ko: '헤이즐넛',         en: 'Hazelnut' },
      { id: 'cg_walnut',         icon: '🌰', ko: '호두',             en: 'Walnut' },
      { id: 'cg_prune',          icon: '🍇', ko: '프룬',             en: 'Prune' },
      { id: 'cg_coffee',         icon: '☕', ko: '커피',             en: 'Coffee' },
      { id: 'cg_leather',        icon: '🧳', ko: '가죽',             en: 'Leather' },
      { id: 'cg_smoked',         icon: '💨', ko: '스모키',           en: 'Smoked' },
      { id: 'cg_toasted_bread',  icon: '🍞', ko: '구운 빵',          en: 'Toasted Bread' },
      { id: 'cg_pepper',         icon: '🌶️', ko: '후추',             en: 'Pepper' },
      { id: 'cg_vanilla',        icon: '🍦', ko: '바닐라',           en: 'Vanilla' },
      { id: 'cg_cigar_box',      icon: '🚬', ko: '시가 박스',        en: 'Cigar Box' },
      { id: 'cg_humus_oak_moss', icon: '🌿', ko: '부엽토/오크 이끼', en: 'Humus / Oak Moss' },
      { id: 'cg_underwood',      icon: '🌲', ko: '숲속 나무',        en: 'Underwood' },
      { id: 'cg_tobacco',        icon: '🚬', ko: '담배',             en: 'Tobacco' },
      { id: 'cg_truffle',        icon: '🍄', ko: '트러플',           en: 'Truffle' },
      { id: 'cg_cedarwood',      icon: '🌲', ko: '시더우드',         en: 'Cedarwood' },
      { id: 'cg_oakwood',        icon: '🪵', ko: '오크우드',         en: 'Oakwood' },
      { id: 'cg_sandalwood',     icon: '🪵', ko: '샌달우드',         en: 'Sandalwood' },
      { id: 'cg_orange_zest',    icon: '🟠', ko: '오렌지 제스트',    en: 'Orange Zest' },
    ],
  },
]
