-- =============================================================================
-- 닉네임 금지 단어 시드 데이터
-- 카테고리: 욕설/비속어, 성적표현, 혐오/비하, 관리자사칭, 브랜드사칭
-- =============================================================================

INSERT IGNORE INTO nickname_bad_words (word, is_active, created_at, updated_at) VALUES

-- ===== 욕설 / 비속어 (한국어) =====
('씨발',   1, NOW(), NOW()),
('시발',   1, NOW(), NOW()),
('씨팔',   1, NOW(), NOW()),
('시팔',   1, NOW(), NOW()),
('씨바',   1, NOW(), NOW()),
('시바',   1, NOW(), NOW()),
('씨빨',   1, NOW(), NOW()),
('ㅅㅂ',   1, NOW(), NOW()),
('ㅆㅂ',   1, NOW(), NOW()),
('개새끼', 1, NOW(), NOW()),
('개놈',   1, NOW(), NOW()),
('개년',   1, NOW(), NOW()),
('개새',   1, NOW(), NOW()),
('개자식', 1, NOW(), NOW()),
('개차반', 1, NOW(), NOW()),
('개같은', 1, NOW(), NOW()),
('개돼지', 1, NOW(), NOW()),
('개소리', 1, NOW(), NOW()),
('병신',   1, NOW(), NOW()),
('벙신',   1, NOW(), NOW()),
('병신새끼', 1, NOW(), NOW()),
('ㅂㅅ',   1, NOW(), NOW()),
('미친놈', 1, NOW(), NOW()),
('미친년', 1, NOW(), NOW()),
('미친새끼', 1, NOW(), NOW()),
('미친',   1, NOW(), NOW()),
('존나',   1, NOW(), NOW()),
('존내',   1, NOW(), NOW()),
('ㅈㄴ',   1, NOW(), NOW()),
('좆',     1, NOW(), NOW()),
('좆같은', 1, NOW(), NOW()),
('씹',     1, NOW(), NOW()),
('씹새끼', 1, NOW(), NOW()),
('씹놈',   1, NOW(), NOW()),
('씹년',   1, NOW(), NOW()),
('니미',   1, NOW(), NOW()),
('니미럴', 1, NOW(), NOW()),
('니애미', 1, NOW(), NOW()),
('엄마보지', 1, NOW(), NOW()),
('보지',   1, NOW(), NOW()),
('자지',   1, NOW(), NOW()),
('후장',   1, NOW(), NOW()),
('창녀',   1, NOW(), NOW()),
('창년',   1, NOW(), NOW()),
('창기',   1, NOW(), NOW()),
('사창가', 1, NOW(), NOW()),
('걸레년', 1, NOW(), NOW()),
('걸레놈', 1, NOW(), NOW()),
('잡년',   1, NOW(), NOW()),
('잡놈',   1, NOW(), NOW()),
('지랄',   1, NOW(), NOW()),
('지럴',   1, NOW(), NOW()),
('썅',     1, NOW(), NOW()),
('쌍놈',   1, NOW(), NOW()),
('쌍년',   1, NOW(), NOW()),
('빌어먹을', 1, NOW(), NOW()),
('닥쳐',   1, NOW(), NOW()),
('꺼져',   1, NOW(), NOW()),
('돌대가리', 1, NOW(), NOW()),
('찐따',   1, NOW(), NOW()),
('애미',   1, NOW(), NOW()),
('애비',   1, NOW(), NOW()),

-- ===== 욕설 / 비속어 (영어) =====
('fuck',   1, NOW(), NOW()),
('fxck',   1, NOW(), NOW()),
('fucker', 1, NOW(), NOW()),
('fucking', 1, NOW(), NOW()),
('shit',   1, NOW(), NOW()),
('bitch',  1, NOW(), NOW()),
('bastard', 1, NOW(), NOW()),
('asshole', 1, NOW(), NOW()),
('dickhead', 1, NOW(), NOW()),
('motherfucker', 1, NOW(), NOW()),
('cunt',   1, NOW(), NOW()),
('whore',  1, NOW(), NOW()),
('slut',   1, NOW(), NOW()),
('nigger', 1, NOW(), NOW()),
('nigga',  1, NOW(), NOW()),
('retard', 1, NOW(), NOW()),
('faggot', 1, NOW(), NOW()),

-- ===== 성적 / 음란 표현 =====
('야동',   1, NOW(), NOW()),
('야사',   1, NOW(), NOW()),
('야설',   1, NOW(), NOW()),
('포르노', 1, NOW(), NOW()),
('porno',  1, NOW(), NOW()),
('porn',   1, NOW(), NOW()),
('강간',   1, NOW(), NOW()),
('윤간',   1, NOW(), NOW()),
('성폭행', 1, NOW(), NOW()),
('성추행', 1, NOW(), NOW()),
('성매매', 1, NOW(), NOW()),
('매춘부', 1, NOW(), NOW()),
('원조교제', 1, NOW(), NOW()),
('원조',   1, NOW(), NOW()),
('원나잇', 1, NOW(), NOW()),
('자위',   1, NOW(), NOW()),
('딸딸이', 1, NOW(), NOW()),
('변태',   1, NOW(), NOW()),
('로리',   1, NOW(), NOW()),
('로리타', 1, NOW(), NOW()),
('lolita', 1, NOW(), NOW()),
('섹스',   1, NOW(), NOW()),
('섹녀',   1, NOW(), NOW()),
('섹남',   1, NOW(), NOW()),

-- ===== 혐오 / 지역비하 / 차별 =====
('홍어',   1, NOW(), NOW()),
('빨갱이', 1, NOW(), NOW()),
('빨갱',   1, NOW(), NOW()),
('짱깨',   1, NOW(), NOW()),
('짱꼴라', 1, NOW(), NOW()),
('쪽바리', 1, NOW(), NOW()),
('검둥이', 1, NOW(), NOW()),
('양놈',   1, NOW(), NOW()),
('보슬아치', 1, NOW(), NOW()),
('맘충',   1, NOW(), NOW()),
('한남충', 1, NOW(), NOW()),
('틀딱',   1, NOW(), NOW()),
('급식충', 1, NOW(), NOW()),
('된장녀', 1, NOW(), NOW()),
('페미나치', 1, NOW(), NOW()),
('일베',   1, NOW(), NOW()),
('김치녀', 1, NOW(), NOW()),
('김치남', 1, NOW(), NOW()),
('탈조선', 1, NOW(), NOW()),

-- ===== 관리자 / 운영진 사칭 =====
('관리자', 1, NOW(), NOW()),
('운영자', 1, NOW(), NOW()),
('운영진', 1, NOW(), NOW()),
('관리인', 1, NOW(), NOW()),
('admin',  1, NOW(), NOW()),
('administrator', 1, NOW(), NOW()),
('moderator', 1, NOW(), NOW()),
('mod',    1, NOW(), NOW()),
('master', 1, NOW(), NOW()),
('root',   1, NOW(), NOW()),
('staff',  1, NOW(), NOW()),
('스태프', 1, NOW(), NOW()),
('시스템', 1, NOW(), NOW()),
('system', 1, NOW(), NOW()),
('공식',   1, NOW(), NOW()),
('official', 1, NOW(), NOW()),
('공지',   1, NOW(), NOW()),
('운영팀', 1, NOW(), NOW()),
('서포터', 1, NOW(), NOW()),
('support', 1, NOW(), NOW()),

-- ===== 서비스 브랜드 사칭 =====
('드링크인덱스', 1, NOW(), NOW()),
('drinkindex',   1, NOW(), NOW()),

-- ===== 기타 사기 / 광고 유도 =====
('텔레그램', 1, NOW(), NOW()),
('telegram', 1, NOW(), NOW()),
('카카오톡', 1, NOW(), NOW()),
('홍보',     1, NOW(), NOW()),
('광고',     1, NOW(), NOW()),
('사기',     1, NOW(), NOW()),
('피싱',     1, NOW(), NOW()),
('phishing', 1, NOW(), NOW());
