-- =============================================================================
-- DrinkIndex 기초데이터 — 와이너리 추가분 2 (Winery seed, 대규모 보강)
-- =============================================================================
-- 작성 기준일: 2026-06-06
-- 범위: V3·V10 누락 보강 — Vivino 등에서 인기/대표 격인 전 세계 와이너리.
--       보르도 추가 그랑 크뤼 · 부르고뉴 도멘 · 론 · 샹파뉴 하우스 · 이탈리아
--       (피에몬테/토스카나/시칠리아/북부) · 스페인 · 포르투갈 · 독일 · 오스트리아 ·
--       미국(나파/소노마/오리건/워싱턴) · 호주 · 뉴질랜드 · 칠레 · 아르헨티나 ·
--       남아공 · 그리스/레바논/헝가리 + Vivino 인기 대중 브랜드.
--
-- [주의]
--   - Flyway 버전 마이그레이션입니다. 한 번 적용된 후에는 이 파일을 수정하지 마세요.
--   - producer.type 은 기본값이 없는 NOT NULL → INSERT 동안만 'WINERY' 기본값을 지정.
--   - search_keywords(V9 추가)는 생략 → NULL.
--   - 중복 방지: V3·V10 에 이미 있는 생산자는 제외했습니다.
--   - website 가 확실치 않은 경우 추측 URL 대신 NULL 로 두었습니다.
--   - founded_year 는 통상 인용되는 설립/현재 형태 성립 연도를 사용했습니다.
-- =============================================================================
ALTER TABLE producer ALTER COLUMN type SET DEFAULT 'WINERY';

INSERT INTO producer
    (name_ko, name_en, country, region, website, founded_year, description_ko, description_en, created_at, updated_at)
VALUES
-- ===================== 프랑스 — 보르도 (Bordeaux) 추가 =====================
('샤토 파비', 'Château Pavie', '프랑스', '보르도', 'https://www.vignoblesperse.com', 1998,
 '생테밀리옹 최고 등급(프르미에 그랑 크뤼 클라세 A) 샤토. 제라르 페르스 인수 후 농밀하고 풍만한 스타일로 정상에 올랐다.',
 'A Saint-Émilion Premier Grand Cru Classé A that rose to the top with a rich, opulent style after Gérard Perse''s acquisition.',
 NOW(6), NOW(6)),
('샤토 뒤크뤼 보카이우', 'Château Ducru-Beaucaillou', '프랑스', '보르도', 'https://www.chateau-ducru-beaucaillou.com', 1720,
 '생쥘리앵의 2등급 샤토. 우아함과 장기 숙성력을 겸비한 ''슈퍼 세컨드''의 대표격이다.',
 'A Saint-Julien Second Growth, a leading "Super Second" combining elegance with great ageing potential.',
 NOW(6), NOW(6)),
('샤토 몽로즈', 'Château Montrose', '프랑스', '보르도', 'https://www.chateau-montrose.com', 1815,
 '생테스테프의 2등급 샤토. 묵직하고 강건하며 장기 숙성형 스타일로 ''슈퍼 세컨드''로 꼽힌다.',
 'A Saint-Estèphe Second Growth, a "Super Second" known for its powerful, structured and long-lived style.',
 NOW(6), NOW(6)),
('샤토 레오빌 푸아페레', 'Château Léoville Poyferré', '프랑스', '보르도', 'https://www.leoville-poyferre.fr', 1840,
 '생쥘리앵의 2등급 샤토. 풍만하고 화려한 스타일로 ''슈퍼 세컨드'' 반열에 오른다.',
 'A Saint-Julien Second Growth, ranked among the "Super Seconds" for its rich, flamboyant style.',
 NOW(6), NOW(6)),
('샤토 레오빌 바르통', 'Château Léoville Barton', '프랑스', '보르도', 'https://www.leoville-barton.com', 1826,
 '생쥘리앵의 2등급 샤토. 바르통 가문이 200년 가까이 운영하며 전통적·고전적 스타일을 지켜왔다.',
 'A Saint-Julien Second Growth run by the Barton family for nearly two centuries, upholding a classic, traditional style.',
 NOW(6), NOW(6)),
('샤토 피숑 바롱', 'Château Pichon Baron', '프랑스', '보르도', 'https://www.pichonbaron.com', 1689,
 '포이약의 2등급 샤토. 카베르네 중심의 묵직하고 응축된 스타일로 ''슈퍼 세컨드''로 평가받는다.',
 'A Pauillac Second Growth, a "Super Second" known for its powerful, concentrated Cabernet-driven style.',
 NOW(6), NOW(6)),
('샤토 베슈벨', 'Château Beychevelle', '프랑스', '보르도', 'https://www.beychevelle.com', 1565,
 '생쥘리앵의 4등급 샤토. 돛을 내린 배 그림(''용의 배'')으로 유명하며 우아한 스타일로 사랑받는다.',
 'A Saint-Julien Fourth Growth famed for its sailing-ship label ("the dragon boat"), beloved for its elegant style.',
 NOW(6), NOW(6)),
('샤토 그뤼오 라로즈', 'Château Gruaud Larose', '프랑스', '보르도', 'https://www.gruaud-larose.com', 1725,
 '생쥘리앵의 2등급 샤토. ''왕들의 와인, 와인들의 왕''을 표방하는 묵직하고 풍부한 스타일로 유명하다.',
 'A Saint-Julien Second Growth famed for its rich, powerful style under the motto "the wine of kings, the king of wines".',
 NOW(6), NOW(6)),
('샤토 탈보', 'Château Talbot', '프랑스', '보르도', 'https://www.chateau-talbot.com', 1855,
 '생쥘리앵의 4등급 샤토. 부드럽고 균형 잡힌 스타일과 화이트 ''카이유 블랑''으로도 유명하다.',
 'A Saint-Julien Fourth Growth known for its supple, balanced reds and its white "Caillou Blanc".',
 NOW(6), NOW(6)),
('샤토 로장 세글라', 'Château Rauzan-Ségla', '프랑스', '보르도', 'https://www.rauzan-segla.com', 1661,
 '마고의 2등급 샤토. 샤넬 그룹 소유로 향기롭고 정교한 마고 스타일을 보여준다.',
 'A Margaux Second Growth owned by the Chanel group, showcasing a perfumed, refined Margaux style.',
 NOW(6), NOW(6)),
('샤토 칼롱 세귀르', 'Château Calon-Ségur', '프랑스', '보르도', 'https://www.calon-segur.fr', 1718,
 '생테스테프의 3등급 샤토. 라벨의 하트 문양으로 유명하며 ''내 마음은 칼롱에 있다''는 일화로 사랑받는다.',
 'A Saint-Estèphe Third Growth famed for the heart on its label and the saying "my heart is in Calon".',
 NOW(6), NOW(6)),
('샤토 파프 클레망', 'Château Pape Clément', '프랑스', '보르도', 'https://www.chateau-pape-clement.fr', 1252,
 '페삭레오냥의 그랑 크뤼 클라세. 보르도에서 가장 오래된 포도밭 중 하나로 교황 클레멘스 5세에서 이름을 땄다.',
 'A Pessac-Léognan Grand Cru Classé on one of Bordeaux''s oldest vineyards, named after Pope Clement V.',
 NOW(6), NOW(6)),
('샤토 라 미시옹 오브리옹', 'Château La Mission Haut-Brion', '프랑스', '보르도', 'https://www.mission-haut-brion.com', 1540,
 '페삭레오냥의 그랑 크뤼 클라세. 오브리옹과 같은 소유로, 흙내음과 강건함을 지닌 명품으로 꼽힌다.',
 'A Pessac-Léognan Grand Cru Classé under the same ownership as Haut-Brion, prized for its earthy, powerful character.',
 NOW(6), NOW(6)),
('샤토 라 콩세이앙트', 'Château La Conseillante', '프랑스', '보르도', 'https://www.la-conseillante.com', 1735,
 '포므롤의 명문 샤토. 메를로·카베르네 프랑 블렌드의 향기롭고 우아한 스타일로 유명하다.',
 'A prestigious Pomerol estate known for a perfumed, elegant Merlot–Cabernet Franc blend.',
 NOW(6), NOW(6)),
('샤토 레방질', 'Château L''Évangile', '프랑스', '보르도', 'https://www.lafite.com', 1741,
 '포므롤의 명문 샤토. 도멘 바롱 드 로칠드(라피트) 소유로 페트뤼스·슈발 블랑과 이웃한다.',
 'A prestigious Pomerol estate owned by Domaines Barons de Rothschild (Lafite), neighbouring Petrus and Cheval Blanc.',
 NOW(6), NOW(6)),
('샤토 트로타누아', 'Château Trotanoy', '프랑스', '보르도', NULL, 1750,
 '포므롤의 명문 샤토. 페트뤼스를 운영하는 무엑스 가문 소유로 농밀하고 깊은 메를로로 유명하다.',
 'A prestigious Pomerol estate owned by the Moueix family of Petrus, famed for its dense, profound Merlot.',
 NOW(6), NOW(6)),
('샤토 카농', 'Château Canon', '프랑스', '보르도', 'https://www.chateau-canon.com', 1760,
 '생테밀리옹의 프르미에 그랑 크뤼 클라세. 샤넬 소유로 석회암 토양의 정교하고 우아한 스타일을 보여준다.',
 'A Saint-Émilion Premier Grand Cru Classé owned by Chanel, showing a refined, elegant style from limestone soils.',
 NOW(6), NOW(6)),
('샤토 트로롱 몽도', 'Château Troplong Mondot', '프랑스', '보르도', 'https://www.chateau-troplong-mondot.com', 1745,
 '생테밀리옹의 프르미에 그랑 크뤼 클라세. 고지대 석회암 비탈의 풍만하고 응축된 스타일로 유명하다.',
 'A Saint-Émilion Premier Grand Cru Classé known for a rich, concentrated style from its high limestone hillside.',
 NOW(6), NOW(6)),
-- ===================== 프랑스 — 부르고뉴 (Bourgogne) 추가 =====================
('도멘 조르주 루미에', 'Domaine Georges Roumier', '프랑스', '부르고뉴', NULL, 1924,
 '샹볼뮈지니의 정상급 도멘. 본 마르·뮈지니 등 그랑 크뤼로 부르고뉴 피노 누아의 기준으로 꼽힌다.',
 'A top Chambolle-Musigny domaine, a benchmark for Burgundian Pinot Noir through grand crus like Bonnes-Mares and Musigny.',
 NOW(6), NOW(6)),
('도멘 자크 프레데릭 뮈니에', 'Domaine Jacques-Frédéric Mugnier', '프랑스', '부르고뉴', NULL, 1863,
 '샹볼뮈지니의 명문 도멘. 뮈지니·레 자무뢰즈에서 극도로 섬세하고 향기로운 피노 누아를 만든다.',
 'A renowned Chambolle-Musigny domaine producing exquisitely delicate, perfumed Pinot Noir from Musigny and Les Amoureuses.',
 NOW(6), NOW(6)),
('도멘 퐁소', 'Domaine Ponsot', '프랑스', '부르고뉴', 'https://www.domaine-ponsot.com', 1872,
 '모레생드니의 역사적 도멘. 클로 드 라 로슈를 비롯한 그랑 크뤼와 혁신적 양조로 유명하다.',
 'A historic Morey-Saint-Denis domaine famed for grand crus such as Clos de la Roche and its innovative winemaking.',
 NOW(6), NOW(6)),
('도멘 데 콩트 라퐁', 'Domaine des Comtes Lafon', '프랑스', '부르고뉴', NULL, 1869,
 '뫼르소의 화이트 명문 도멘. 바이오다이내믹 농법의 풍부하고 장기 숙성형 샤르도네로 유명하다.',
 'A leading Meursault white-wine domaine famed for rich, age-worthy biodynamic Chardonnay.',
 NOW(6), NOW(6)),
('보노 뒤 마르트레', 'Bonneau du Martray', '프랑스', '부르고뉴', 'https://www.bonneaudumartray.com', 1969,
 '코르통 언덕의 단일 도멘. 코르통샤를마뉴 그랑 크뤼 화이트의 대표 생산자로 꼽힌다.',
 'A monopole-focused domaine on the hill of Corton, a leading producer of Corton-Charlemagne grand cru white.',
 NOW(6), NOW(6)),
('도멘 라모네', 'Domaine Ramonet', '프랑스', '부르고뉴', NULL, 1920,
 '샤사뉴몽라셰의 화이트 명문 도멘. 몽라셰 등 그랑 크뤼 샤르도네로 추앙받는다.',
 'A leading Chassagne-Montrachet white-wine domaine revered for grand cru Chardonnay including Montrachet.',
 NOW(6), NOW(6)),
('도멘 라보노 (샤블리)', 'Domaine Raveneau', '프랑스', '부르고뉴', NULL, 1948,
 '샤블리의 컬트 도멘. 레 클로·발뮈르 등 그랑 크뤼에서 미네랄하고 장기 숙성형 샤블리를 만든다.',
 'A cult Chablis domaine crafting mineral, age-worthy Chablis from grand crus such as Les Clos and Valmur.',
 NOW(6), NOW(6)),
('도멘 뱅상 도비사 (샤블리)', 'Domaine Vincent Dauvissat', '프랑스', '부르고뉴', NULL, 1931,
 '샤블리의 정상급 도멘. 라보노와 함께 순수하고 미네랄한 그랑 크뤼 샤블리의 양대 기준으로 꼽힌다.',
 'A top Chablis domaine regarded, alongside Raveneau, as a twin benchmark for pure, mineral grand cru Chablis.',
 NOW(6), NOW(6)),
('도멘 실뱅 카티아르', 'Domaine Sylvain Cathiard', '프랑스', '부르고뉴', NULL, 1969,
 '본로마네의 컬트 도멘. 로마네 생비방 등에서 향기롭고 정교한 피노 누아를 극소량 생산한다.',
 'A cult Vosne-Romanée domaine producing tiny amounts of perfumed, refined Pinot Noir from sites like Romanée-Saint-Vivant.',
 NOW(6), NOW(6)),
-- ===================== 프랑스 — 론 (Rhône) 추가 =====================
('도멘 뒤 비외 텔레그라프', 'Domaine du Vieux Télégraphe', '프랑스', '론', 'https://www.vignoblesbrunier.fr', 1898,
 '샤토뇌프뒤파프의 명문 도멘. 라 크로 고원의 자갈 토양에서 전통적이고 균형 잡힌 와인을 만든다.',
 'A leading Châteauneuf-du-Pape domaine making traditional, balanced wines from the pebbly La Crau plateau.',
 NOW(6), NOW(6)),
('클로 데 파프', 'Clos des Papes', '프랑스', '론', NULL, 1896,
 '샤토뇌프뒤파프의 정상급 가족 도멘. 레드·화이트 모두 단일 퀴베만 만드는 것으로 유명하다.',
 'A top family domaine in Châteauneuf-du-Pape, famed for producing only a single cuvée each in red and white.',
 NOW(6), NOW(6)),
('도멘 뒤 페고', 'Domaine du Pégaü', '프랑스', '론', 'https://www.pegau.com', 1987,
 '샤토뇌프뒤파프의 전통주의 명가. 묵직하고 야성적인 ''퀴베 다 카포'' 등으로 컬트적 인기를 누린다.',
 'A traditionalist Châteauneuf-du-Pape estate with a cult following for powerful, wild wines like "Cuvée da Capo".',
 NOW(6), NOW(6)),
('도멘 오귀스트 클라프', 'Domaine Auguste Clape', '프랑스', '론', NULL, 1950,
 '코르나스의 전설적 도멘. 100% 시라의 묵직하고 장기 숙성형 와인으로 북부 론의 기준을 세웠다.',
 'A legendary Cornas domaine that set a Northern Rhône standard with powerful, age-worthy 100% Syrah.',
 NOW(6), NOW(6)),
('도멘 조르주 베르네', 'Domaine Georges Vernay', '프랑스', '론', 'https://www.georges-vernay.fr', 1937,
 '콩드리외 비오니에를 부흥시킨 ''콩드리외의 교황''의 도멘. 향기로운 화이트로 유명하다.',
 'The domaine of the "Pope of Condrieu," who revived Condrieu Viognier, famed for its aromatic whites.',
 NOW(6), NOW(6)),
('델라스 프레르', 'Delas Frères', '프랑스', '론', 'https://www.delas.com', 1835,
 '북부·남부 론을 아우르는 명문 네고시앙 겸 도멘. 에르미타주 ''레 부세''로 유명하다.',
 'A leading Rhône négociant and domaine spanning north and south, famed for its Hermitage "Les Bessards".',
 NOW(6), NOW(6)),
-- ===================== 프랑스 — 샹파뉴 (Champagne) 추가 =====================
('모엣 샹동', 'Moët & Chandon', '프랑스', '샴페인', 'https://www.moet.com', 1743,
 '세계 최대의 샴페인 하우스. ''임페리얼'' 브뤼와 프레스티지 퀴베 동 페리뇽으로 샴페인의 대명사가 되었다.',
 'The world''s largest Champagne house, synonymous with the category through its "Impérial" Brut and the prestige cuvée Dom Pérignon.',
 NOW(6), NOW(6)),
('샤를 하이직', 'Charles Heidsieck', '프랑스', '샴페인', 'https://www.charlesheidsieck.com', 1851,
 '''샴페인 찰리''로 불린 창업자의 하우스. 다년 리저브 비중이 높은 농밀하고 복합적인 스타일로 추앙받는다.',
 'The house of the founder nicknamed "Champagne Charlie," revered for a rich, complex style with a high proportion of reserve wines.',
 NOW(6), NOW(6)),
('파이퍼 하이직', 'Piper-Heidsieck', '프랑스', '샴페인', 'https://www.piper-heidsieck.com', 1785,
 '신선하고 활기찬 스타일의 역사적 하우스. 마릴린 먼로와 영화계와의 인연으로도 유명하다.',
 'A historic house with a fresh, lively style, also famed for its ties to Marilyn Monroe and the film world.',
 NOW(6), NOW(6)),
('도츠', 'Deutz', '프랑스', '샴페인', 'https://www.champagne-deutz.com', 1838,
 '아이 마을의 명문 가족 하우스. 우아하고 섬세한 스타일과 프레스티지 퀴베 ''아무르 드 도츠''로 유명하다.',
 'A prestigious family house in Aÿ known for an elegant, refined style and its prestige cuvée "Amour de Deutz".',
 NOW(6), NOW(6)),
('필리포나', 'Philipponnat', '프랑스', '샴페인', 'https://www.philipponnat.com', 1910,
 '단일 밭 ''클로 데 고이스''로 유명한 가족 하우스. 피노 누아 중심의 깊은 스타일이 특징이다.',
 'A family house famed for its single-vineyard "Clos des Goisses," characterised by a deep, Pinot-Noir-driven style.',
 NOW(6), NOW(6)),
('자크송', 'Jacquesson', '프랑스', '샴페인', 'https://www.champagnejacquesson.com', 1798,
 '매년 최고의 블렌드만 만드는 ''퀴베 번호'' 시리즈로 유명한 장인적 하우스.',
 'An artisanal house famed for its numbered "Cuvée 7xx" series, releasing only the best blend it can make each year.',
 NOW(6), NOW(6)),
('고세', 'Gosset', '프랑스', '샴페인', 'https://www.champagne-gosset.com', 1584,
 '샹파뉴에서 가장 오래된 와인 하우스. 젖산 발효를 억제한 신선하고 농밀한 스타일로 유명하다.',
 'The oldest wine house in Champagne, known for a fresh, rich style achieved by limiting malolactic fermentation.',
 NOW(6), NOW(6)),
('자크 셀로스', 'Jacques Selosse', '프랑스', '샴페인', NULL, 1949,
 '부르고뉴식 양조를 도입한 그로워 샴페인의 선구자. 산화·복합적 스타일로 컬트적 추앙을 받는다.',
 'A pioneer of grower Champagne who introduced Burgundian winemaking, with a cult following for his oxidative, complex style.',
 NOW(6), NOW(6)),
('에글리 우리에', 'Egly-Ouriet', '프랑스', '샴페인', NULL, 1930,
 '암보네 그랑 크뤼의 정상급 그로워. 피노 누아 중심의 농밀하고 깊은 샴페인으로 유명하다.',
 'A top grower in the Ambonnay grand cru, famed for rich, deep Pinot-Noir-driven Champagne.',
 NOW(6), NOW(6)),
('포므리', 'Pommery', '프랑스', '샴페인', 'https://www.vrankenpommery.com', 1858,
 '랭스의 역사적 대형 하우스. 최초의 본격 브뤼(드라이) 샴페인을 대중화한 것으로 유명하다.',
 'A historic large house in Reims, famed for popularising the first true Brut (dry) Champagne.',
 NOW(6), NOW(6)),
('G.H. 멈', 'G.H. Mumm', '프랑스', '샴페인', 'https://www.mumm.com', 1827,
 '붉은 리본의 ''코르동 루즈''로 유명한 대형 하우스. 포뮬러 원 시상식 샴페인으로도 잘 알려져 있다.',
 'A large house famed for its red-ribboned "Cordon Rouge," also well known as the Champagne of Formula 1 podiums.',
 NOW(6), NOW(6)),
-- ===================== 프랑스 — 루아르 / 알자스 / 프로방스 추가 =====================
('니콜라 졸리 (쿨레 드 세랑)', 'Nicolas Joly (Coulée de Serrant)', '프랑스', '루아르', NULL, 1980,
 '바이오다이내믹 농법의 세계적 전도사. 사브니에르의 단독 아펠라시옹 ''쿨레 드 세랑'' 슈냉 블랑으로 유명하다.',
 'A global apostle of biodynamics, famed for the Chenin Blanc of "Coulée de Serrant," its own appellation in Savennières.',
 NOW(6), NOW(6)),
('앙리 부르주아', 'Henri Bourgeois', '프랑스', '루아르', 'https://www.henribourgeois.com', 1950,
 '상세르의 가족 명가. 미네랄하고 표현력 있는 소비뇽 블랑으로 루아르를 대표한다.',
 'A family estate in Sancerre representing the Loire with mineral, expressive Sauvignon Blanc.',
 NOW(6), NOW(6)),
('도멘 바인바흐', 'Domaine Weinbach', '프랑스', '알자스', 'https://www.domaineweinbach.com', 1898,
 '카이세르스베르의 명문 도멘. 클로 데 카퓌생을 중심으로 풍부하고 정교한 리슬링·게뷔르츠트라미너를 만든다.',
 'A leading Alsace domaine in Kaysersberg, crafting rich, refined Riesling and Gewurztraminer around its Clos des Capucins.',
 NOW(6), NOW(6)),
('샤토 데스클랑 (위스퍼링 엔젤)', 'Château d''Esclans', '프랑스', '프로방스', 'https://www.esclans.com', 2006,
 '프로방스 로제 열풍을 이끈 와이너리. 베스트셀러 ''위스퍼링 엔젤''과 프리미엄 ''가뤼''로 유명하다.',
 'The winery behind the Provence rosé boom, famed for the best-selling "Whispering Angel" and premium "Garrus".',
 NOW(6), NOW(6)),
-- ===================== 이탈리아 — 피에몬테 (Piemonte) 추가 =====================
('로베르토 보에르치오', 'Roberto Voerzio', '이탈리아', '피에몬테', NULL, 1986,
 '라 모라의 현대주의 바롤로 명가. 극단적 수확량 제한으로 응축된 단일 밭 바롤로를 만든다.',
 'A modernist Barolo estate in La Morra producing concentrated single-vineyard Barolo through extreme yield reduction.',
 NOW(6), NOW(6)),
('파올로 스카비노', 'Paolo Scavino', '이탈리아', '피에몬테', 'https://www.paoloscavino.com', 1921,
 '카스틸리오네 팔레토의 명가. 전통과 현대를 조화시킨 단일 밭 바롤로로 정평이 나 있다.',
 'A Castiglione Falletto estate esteemed for single-vineyard Barolo that blends tradition and modernity.',
 NOW(6), NOW(6)),
('루치아노 산드로네', 'Luciano Sandrone', '이탈리아', '피에몬테', 'https://www.sandroneluciano.com', 1978,
 '바롤로의 현대 명가. ''레 비뉴''와 ''칸누비 보스키스''로 우아하고 향기로운 네비올로를 보여준다.',
 'A modern Barolo estate showcasing elegant, perfumed Nebbiolo through its "Le Vigne" and "Cannubi Boschis".',
 NOW(6), NOW(6)),
('알도 콘테르노', 'Aldo Conterno', '이탈리아', '피에몬테', 'https://www.poderialdoconterno.com', 1969,
 '몬포르테 달바의 명문 도멘. 전통과 절제를 겸비한 바롤로 ''그란부시아''로 유명하다.',
 'A leading Monforte d''Alba estate famed for its balanced, traditional Barolo "Granbussia".',
 NOW(6), NOW(6)),
('G.D. 바이라', 'G.D. Vajra', '이탈리아', '피에몬테', 'https://www.gdvajra.it', 1972,
 '바롤로 ''브리코 델레 비올레'' 등으로 유명한 가족 명가. 우아하고 향기로운 고전적 스타일을 추구한다.',
 'A family estate famed for Barolo "Bricco delle Viole," pursuing an elegant, perfumed and classic style.',
 NOW(6), NOW(6)),
('주세페 리날디', 'Giuseppe Rinaldi', '이탈리아', '피에몬테', NULL, 1870,
 '바롤로 전통주의의 상징적 컬트 와이너리. 블렌딩 바롤로 ''브루나테''로 추앙받는다.',
 'An iconic cult winery of Barolo traditionalism, revered for its blended Barolo "Brunate".',
 NOW(6), NOW(6)),
('마솔리노', 'Massolino', '이탈리아', '피에몬테', 'https://www.massolino.it', 1896,
 '세라룽가 달바의 전통 명가. 단일 밭 ''비뉴 리온다'' 바롤로로 정평이 나 있다.',
 'A traditional Serralunga d''Alba estate esteemed for its single-vineyard "Vigna Rionda" Barolo.',
 NOW(6), NOW(6)),
('프로두토리 델 바르바레스코', 'Produttori del Barbaresco', '이탈리아', '피에몬테', 'https://www.produttoridelbarbaresco.com', 1958,
 '바르바레스코의 명문 협동조합. 단일 밭(크뤼) 리제르바로 뛰어난 가성비와 품질을 보여준다.',
 'A renowned Barbaresco cooperative offering outstanding value and quality through its single-vineyard (cru) Riservas.',
 NOW(6), NOW(6)),
('체레토', 'Ceretto', '이탈리아', '피에몬테', 'https://www.ceretto.com', 1930,
 '바롤로·바르바레스코를 아우르는 대형 명가. 단일 밭 와인과 현대 미술·건축으로도 유명하다.',
 'A large estate spanning Barolo and Barbaresco, also known for single-vineyard wines and its contemporary art and architecture.',
 NOW(6), NOW(6)),
('마르케시 디 바롤로', 'Marchesi di Barolo', '이탈리아', '피에몬테', 'https://www.marchesibarolo.com', 1807,
 '''바롤로''라는 이름의 기원과 얽힌 역사적 와이너리. 바롤로 마을의 대표 생산자다.',
 'A historic winery tied to the origins of the name "Barolo," a flagship producer in the village of Barolo.',
 NOW(6), NOW(6)),
-- ===================== 이탈리아 — 토스카나 (Toscana) 추가 =====================
('카스텔로 디 아마', 'Castello di Ama', '이탈리아', '토스카나', 'https://www.castellodiama.com', 1972,
 '키안티 클라시코의 정상급 에스테이트. 단일 밭 산지오베제와 현대 미술 설치로 유명하다.',
 'A top Chianti Classico estate famed for single-vineyard Sangiovese and its contemporary art installations.',
 NOW(6), NOW(6)),
('폰토디', 'Fontodi', '이탈리아', '토스카나', 'https://www.fontodi.com', 1968,
 '판차노의 바이오다이내믹 명가. 100% 산지오베제 ''플라치아넬로''로 키안티 클라시코를 대표한다.',
 'A biodynamic estate in Panzano representing Chianti Classico with its 100% Sangiovese "Flaccianello".',
 NOW(6), NOW(6)),
('이솔레 에 올레나', 'Isole e Olena', '이탈리아', '토스카나', NULL, 1956,
 '키안티 클라시코의 명가. 슈퍼 투스칸의 선구작 중 하나인 ''체파렐로''(100% 산지오베제)로 유명하다.',
 'A leading Chianti Classico estate famed for "Cepparello," one of the pioneering Super Tuscans (100% Sangiovese).',
 NOW(6), NOW(6)),
('펠시나', 'Fèlsina', '이탈리아', '토스카나', 'https://www.felsina.it', 1966,
 '키안티 클라시코 남단의 명가. 장기 숙성형 산지오베제 ''리세르바 란차''로 정평이 나 있다.',
 'A leading estate at the southern edge of Chianti Classico, esteemed for its age-worthy Sangiovese "Riserva Rancia".',
 NOW(6), NOW(6)),
('솔데라 (카제 바세)', 'Soldera (Case Basse)', '이탈리아', '토스카나', NULL, 1972,
 '몬탈치노의 전설적 컬트 와이너리. 극도의 전통 방식으로 만든 희소한 산지오베제로 추앙받는다.',
 'A legendary cult winery in Montalcino, revered for scarce Sangiovese made by ultra-traditional methods.',
 NOW(6), NOW(6)),
('레 마키올레', 'Le Macchiole', '이탈리아', '토스카나', 'https://www.lemacchiole.it', 1975,
 '볼게리의 명가. 단일 품종 와인 ''메소리오''(메를로)·''스크리오''(시라)로 컬트적 인기를 누린다.',
 'A Bolgheri estate with a cult following for its single-variety wines "Messorio" (Merlot) and "Scrio" (Syrah).',
 NOW(6), NOW(6)),
('투아 리타', 'Tua Rita', '이탈리아', '토스카나', 'https://www.tuarita.it', 1984,
 '토스카나 해안의 컬트 와이너리. 단일 메를로 ''레디가피''로 ''마세토의 라이벌''로 불린다.',
 'A cult Tuscan coastal winery whose single-vineyard Merlot "Redigaffi" is dubbed a "rival to Masseto".',
 NOW(6), NOW(6)),
('일 포조네', 'Il Poggione', '이탈리아', '토스카나', 'https://www.tenutailpoggione.it', 1890,
 '몬탈치노의 전통 명가. 안정적 품질과 뛰어난 가성비의 브루넬로 디 몬탈치노로 사랑받는다.',
 'A traditional Montalcino estate beloved for consistently styled, great-value Brunello di Montalcino.',
 NOW(6), NOW(6)),
('아비뇨네지', 'Avignonesi', '이탈리아', '토스카나', 'https://www.avignonesi.it', 1974,
 '몬테풀차노의 바이오다이내믹 명가. 비노 노빌레와 전설적 디저트 와인 ''빈 산토''로 유명하다.',
 'A biodynamic estate in Montepulciano famed for Vino Nobile and its legendary "Vin Santo" dessert wine.',
 NOW(6), NOW(6)),
-- ===================== 이탈리아 — 시칠리아 / 북부 / 기타 추가 =====================
('돈나푸가타', 'Donnafugata', '이탈리아', '시칠리아', 'https://www.donnafugata.it', 1983,
 '시칠리아의 현대적 명가. 토착 품종과 디저트 와인 ''벤 리에''로 폭넓게 사랑받는다.',
 'A modern Sicilian estate beloved for native-variety wines and its dessert wine "Ben Ryé".',
 NOW(6), NOW(6)),
('타스카 달메리타', 'Tasca d''Almerita', '이탈리아', '시칠리아', 'https://www.tascadalmerita.it', 1830,
 '시칠리아의 역사적 귀족 에스테이트. 레가렐리 영지의 ''로소 델 콘테''로 유명하다.',
 'A historic Sicilian noble estate famed for "Rosso del Conte" from its Regaleali property.',
 NOW(6), NOW(6)),
('아르지올라스', 'Argiolas', '이탈리아', '사르데냐', 'https://www.argiolas.it', 1938,
 '사르데냐의 대표 가족 와이너리. 토착 품종 카노나우·베르멘티노로 섬의 와인을 세계에 알렸다.',
 'A flagship Sardinian family winery that brought the island''s wines to the world through native Cannonau and Vermentino.',
 NOW(6), NOW(6)),
('페우디 디 산 그레고리오', 'Feudi di San Gregorio', '이탈리아', '캄파니아', 'https://www.feudi.it', 1986,
 '캄파니아의 현대적 대표 와이너리. 알리아니코·피아노·그레코 등 토착 품종의 부흥을 이끌었다.',
 'A leading modern Campania winery that drove the revival of native varieties such as Aglianico, Fiano and Greco.',
 NOW(6), NOW(6)),
('알로이스 라게더', 'Alois Lageder', '이탈리아', '알토 아디제', 'https://www.aloislageder.eu', 1823,
 '알토 아디제의 바이오다이내믹 선구 명가. 산뜻하고 정교한 알파인 화이트로 유명하다.',
 'A pioneering biodynamic estate in Alto Adige famed for crisp, refined Alpine white wines.',
 NOW(6), NOW(6)),
('예르만', 'Jermann', '이탈리아', '프리울리', 'https://www.jermann.it', 1881,
 '프리울리 화이트의 명가. 블렌드 화이트 ''빈탄지''로 이탈리아 화이트의 수준을 끌어올렸다.',
 'A leading Friuli white-wine estate that raised the bar for Italian whites with its blend "Vintage Tunina".',
 NOW(6), NOW(6)),
('리비오 펠루가', 'Livio Felluga', '이탈리아', '프리울리', 'https://www.liviofelluga.it', 1956,
 '프리울리의 대표 가족 명가. 지도 라벨의 화이트 블렌드 ''테레 알테''로 유명하다.',
 'A flagship Friuli family estate famed for its map-labelled white blend "Terre Alte".',
 NOW(6), NOW(6)),
('톰마시', 'Tommasi', '이탈리아', '베네토', 'https://www.tommasi.com', 1902,
 '발폴리첼라의 대형 가족 명가. 안정적 품질의 아마로네로 폭넓게 사랑받는다.',
 'A large Valpolicella family estate beloved for consistently styled Amarone.',
 NOW(6), NOW(6)),
('베르타니', 'Bertani', '이탈리아', '베네토', 'https://www.bertani.net', 1857,
 '발폴리첼라의 역사적 명가. 수십 년 숙성하는 전통 스타일 아마로네로 유명하다.',
 'A historic Valpolicella estate famed for its traditional-style Amarone capable of ageing for decades.',
 NOW(6), NOW(6)),
('루피노', 'Ruffino', '이탈리아', '토스카나', 'https://www.ruffino.com', 1877,
 '키안티의 역사적 대형 하우스. ''리세르바 두칼레''로 전 세계에 키안티를 알렸다.',
 'A historic large Chianti house that brought Chianti to the world with its "Riserva Ducale".',
 NOW(6), NOW(6)),
('산타 마르게리타', 'Santa Margherita', '이탈리아', '베네토', 'https://www.santamargherita.com', 1935,
 '핀치오 그리지오를 세계적 베스트셀러로 만든 대형 명가.',
 'A large estate that made Pinot Grigio a global best-seller.',
 NOW(6), NOW(6)),
-- ===================== 스페인 추가 =====================
('파밀리아 토레스', 'Familia Torres', '스페인', '카탈루냐 (페네데스)', 'https://www.torres.es', 1870,
 '스페인 최대의 가족 와인 명가. 페네데스를 본거지로 ''마스 라 플라나'' 등 국제적 명성의 와인을 만든다.',
 'Spain''s largest family wine house, based in Penedès, making internationally acclaimed wines such as "Mas La Plana".',
 NOW(6), NOW(6)),
('아르타디', 'Artadi', '스페인', '리오하', 'https://www.artadi.com', 1985,
 '리오하 알라베사의 현대 명가. 단일 밭 ''비냐 엘 피손''으로 스페인 정상급 템프라니요를 만든다.',
 'A modern Rioja Alavesa estate crafting top-tier Spanish Tempranillo from its single vineyard "Viña El Pisón".',
 NOW(6), NOW(6)),
('CVNE (쿠네)', 'CVNE', '스페인', '리오하', 'https://www.cvne.com', 1879,
 '아로의 역사적 대형 보데가. ''임페리얼''·''비냐 레알'' 등으로 전통 리오하를 대표한다.',
 'A historic large bodega in Haro representing traditional Rioja with labels such as "Imperial" and "Viña Real".',
 NOW(6), NOW(6)),
('마르케스 데 무리에타', 'Marqués de Murrieta', '스페인', '리오하', 'https://www.marquesdemurrieta.com', 1852,
 '리오하 최초의 상업 와이너리 중 하나. 전설적 ''카스티요 이가이'' 그란 레세르바로 유명하다.',
 'One of the first commercial wineries in Rioja, famed for its legendary "Castillo Ygay" Gran Reserva.',
 NOW(6), NOW(6)),
('보데가스 로다', 'Bodegas Roda', '스페인', '리오하', 'https://www.roda.es', 1987,
 '아로의 현대 명가. 올드 바인 템프라니요를 선별해 우아하고 현대적인 리오하를 만든다.',
 'A modern Haro estate making elegant, contemporary Rioja from selected old-vine Tempranillo.',
 NOW(6), NOW(6)),
('에밀리오 모로', 'Emilio Moro', '스페인', '리베라 델 두에로', 'https://www.emiliomoro.com', 1932,
 '리베라 델 두에로의 가족 명가. 100% 템프라니요(틴토 피노)의 깊고 현대적인 레드로 유명하다.',
 'A Ribera del Duero family estate famed for deep, modern reds from 100% Tempranillo (Tinto Fino).',
 NOW(6), NOW(6)),
('보데가스 아알토', 'Bodegas Aalto', '스페인', '리베라 델 두에로', 'https://www.aalto.es', 1999,
 '베가 시실리아 출신 마리아노 가르시아가 공동 설립한 현대 명가. 응축된 ''아알토 PS''로 유명하다.',
 'A modern estate co-founded by Mariano García (formerly of Vega Sicilia), famed for its concentrated "Aalto PS".',
 NOW(6), NOW(6)),
('누만시아', 'Numanthia', '스페인', '토로', NULL, 1998,
 '토로의 컬트 와이너리. 올드 바인 틴타 데 토로로 만든 농밀한 ''테르만시아''로 명성을 얻었다.',
 'A cult Toro winery that gained fame with "Termanthia," a dense red from old-vine Tinta de Toro.',
 NOW(6), NOW(6)),
('클로스 에라스무스', 'Clos Erasmus', '스페인', '프리오라트', NULL, 1989,
 '프리오라트 부흥을 이끈 5인방 중 하나. 극소량 생산되는 컬트 와인으로 추앙받는다.',
 'One of the five pioneers of the Priorat revival, revered for its tiny-production cult wine.',
 NOW(6), NOW(6)),
('코도르니우', 'Codorníu', '스페인', '카탈루냐 (카바)', 'https://www.codorniu.com', 1551,
 '스페인 전통 방식 스파클링 ''카바''를 창시한 역사적 하우스. 세계에서 가장 오래된 가족 기업 중 하나다.',
 'The historic house that created Spain''s traditional-method sparkling "Cava," among the oldest family businesses in the world.',
 NOW(6), NOW(6)),
('프레이셰넷', 'Freixenet', '스페인', '카탈루냐 (카바)', 'https://www.freixenet.com', 1861,
 '세계 최대 카바 생산자. 검은 병의 ''코르돈 네그로''로 전 세계에 카바를 알렸다.',
 'The world''s largest Cava producer, which brought Cava to the world with its black-bottled "Cordon Negro".',
 NOW(6), NOW(6)),
-- ===================== 포르투갈 추가 =====================
('키타 두 발 메앙', 'Quinta do Vale Meão', '포르투갈', '도루', 'https://www.quintadovalemeao.pt', 1999,
 '바로사 가문(옛 페레이라)의 역사적 싱글 킨타. 도루 최정상 스틸 레드로 꼽힌다.',
 'A historic single quinta of the Olazabal (former Ferreira) family, ranked among the finest Douro still reds.',
 NOW(6), NOW(6)),
('에스포랑', 'Esporão', '포르투갈', '알렌테주', 'https://www.esporao.com', 1973,
 '알렌테주의 대형 명가. 토착 품종 기반의 폭넓은 와인과 올리브유로도 유명하다.',
 'A large Alentejo estate famed for a wide range of native-variety wines and its olive oils.',
 NOW(6), NOW(6)),
('루이스 파투', 'Luís Pato', '포르투갈', '바이라다', 'https://www.luispato.com', 1980,
 '''바이라다의 아버지''로 불리는 양조가. 토착 적포도 바가의 잠재력을 세계에 알렸다.',
 'A vintner known as "the father of Bairrada," who revealed the potential of the native red grape Baga to the world.',
 NOW(6), NOW(6)),
('키타 두 베수비우', 'Quinta do Vesuvio', '포르투갈', '도루', NULL, 1827,
 '시밍턴 가문이 운영하는 역사적 싱글 킨타. 발로 으깨 만드는 전통 빈티지 포트로 유명하다.',
 'A historic single quinta run by the Symington family, famed for foot-trodden traditional Vintage Port.',
 NOW(6), NOW(6)),
-- ===================== 독일 / 오스트리아 추가 =====================
('되네호프', 'Weingut Dönnhoff', '독일', '나에', 'https://www.doennhoff.com', 1750,
 '나에 지방의 정상급 리슬링 에스테이트. 순수하고 미네랄한 그랑 크뤼 리슬링으로 세계적 명성을 얻었다.',
 'A top Riesling estate in the Nahe, world-renowned for pure, mineral grand cru Riesling.',
 NOW(6), NOW(6)),
('켈러', 'Weingut Keller', '독일', '라인헤센', NULL, 1789,
 '라인헤센의 컬트 에스테이트. 전설적 단일 밭 ''G-Max'' 리슬링은 독일 화이트의 정점으로 꼽힌다.',
 'A cult Rheinhessen estate whose legendary single-vineyard "G-Max" Riesling is regarded as a peak of German white wine.',
 NOW(6), NOW(6)),
('비트만', 'Weingut Wittmann', '독일', '라인헤센', 'https://www.weingutwittmann.com', 1663,
 '라인헤센의 바이오다이내믹 명가. 드라이 그랑 크뤼 리슬링(특히 ''모르슈타인'')으로 유명하다.',
 'A biodynamic Rheinhessen estate famed for dry grand cru Riesling, especially from the "Morstein" site.',
 NOW(6), NOW(6)),
('프리츠 하크', 'Weingut Fritz Haag', '독일', '모젤', 'https://www.weingut-fritz-haag.de', 1605,
 '모젤의 정상급 에스테이트. 브라우네베르거 유퍼 비탈에서 정교한 리슬링을 만든다.',
 'A top Mosel estate crafting precise Riesling from the steep Brauneberger Juffer slope.',
 NOW(6), NOW(6)),
('막시민 그륀하우스', 'Maximin Grünhaus', '독일', '모젤', 'https://www.vonschubert.com', 1882,
 '루버(모젤)의 역사적 에스테이트. 단일 밭 압츠베르크의 우아하고 장기 숙성형 리슬링으로 유명하다.',
 'A historic estate on the Ruwer (Mosel), famed for the elegant, age-worthy Riesling of its Abtsberg monopole.',
 NOW(6), NOW(6)),
('크놀', 'Weingut Knoll', '오스트리아', '바하우', NULL, 1825,
 '바하우의 전통 명가. 묵직하고 장기 숙성형 그뤼너 펠트리너·리슬링과 성 우르반 라벨로 유명하다.',
 'A traditional Wachau estate famed for powerful, age-worthy Grüner Veltliner and Riesling and its Saint Urban label.',
 NOW(6), NOW(6)),
('프라거', 'Weingut Prager', '오스트리아', '바하우', 'https://www.weingutprager.at', 1715,
 '바하우의 정상급 에스테이트. 가파른 테라스 밭의 정교한 리슬링·그뤼너 펠트리너로 유명하다.',
 'A top Wachau estate famed for refined Riesling and Grüner Veltliner from its steep terraced vineyards.',
 NOW(6), NOW(6)),
('니콜라이호프', 'Nikolaihof', '오스트리아', '바하우', 'https://www.nikolaihof.at', 1894,
 '로마 시대까지 거슬러 올라가는 바하우의 역사적 바이오다이내믹 에스테이트. 장기 숙성 리슬링으로 유명하다.',
 'A historic biodynamic Wachau estate with Roman-era roots, famed for its long-aged Riesling.',
 NOW(6), NOW(6)),
-- ===================== 미국 — 나파 밸리 추가 =====================
('샤퍼 빈야드', 'Shafer Vineyards', '미국', '나파 밸리 (스택스 립)', 'https://www.shafervineyards.com', 1972,
 '스택스 립 지구의 명가. 농밀하고 풍만한 카베르네 ''힐사이드 셀렉트''로 유명하다.',
 'A leading Stags Leap District estate famed for its rich, plush Cabernet "Hillside Select".',
 NOW(6), NOW(6)),
('조셉 펠프스', 'Joseph Phelps Vineyards', '미국', '나파 밸리', 'https://www.josephphelps.com', 1973,
 '나파 보르도 블렌드의 선구자. 최초의 캘리포니아 ''메리티지''로 꼽히는 ''인시그니아''로 유명하다.',
 'A pioneer of Napa Bordeaux blends, famed for "Insignia," regarded as a first California "Meritage".',
 NOW(6), NOW(6)),
('실버 오크', 'Silver Oak', '미국', '나파 밸리 (오크빌)', 'https://www.silveroak.com', 1972,
 '아메리칸 오크 숙성 카베르네 소비뇽만 고집하는 나파의 인기 명가. 부드럽고 풍만한 스타일로 사랑받는다.',
 'A popular Napa estate making only American-oak-aged Cabernet Sauvignon, beloved for its smooth, plush style.',
 NOW(6), NOW(6)),
('파 니엔테', 'Far Niente', '미국', '나파 밸리 (오크빌)', 'https://www.farniente.com', 1885,
 '1885년 설립 후 부활한 역사적 나파 명가. 카베르네 소비뇽과 샤르도네로 유명하다.',
 'A historic Napa estate founded in 1885 and later revived, famed for its Cabernet Sauvignon and Chardonnay.',
 NOW(6), NOW(6)),
('스폿츠우드', 'Spottswoode Estate', '미국', '나파 밸리 (세인트헬레나)', 'https://www.spottswoode.com', 1882,
 '세인트헬레나의 유기농 명가. 우아하고 정교한 카베르네 소비뇽으로 정평이 나 있다.',
 'An organic St. Helena estate esteemed for elegant, refined Cabernet Sauvignon.',
 NOW(6), NOW(6)),
('달라 발레', 'Dalla Valle Vineyards', '미국', '나파 밸리 (오크빌)', 'https://www.dallavallevineyards.com', 1986,
 '오크빌 동쪽 산비탈의 컬트 와이너리. 카베르네 프랑 중심의 ''마야''로 추앙받는다.',
 'A cult winery on Oakville''s eastern hills, revered for its Cabernet-Franc-driven "Maya".',
 NOW(6), NOW(6)),
('콘티뉴엄', 'Continuum Estate', '미국', '나파 밸리', 'https://www.continuumestate.com', 2005,
 '로버트 몬다비의 자녀 팀·마샤 몬다비가 설립한 명가. 프리처드 힐의 보르도 블렌드로 유명하다.',
 'An estate founded by Robert Mondavi''s children Tim and Marcia, famed for its Pritchard Hill Bordeaux blend.',
 NOW(6), NOW(6)),
('퀸테사', 'Quintessa', '미국', '나파 밸리 (러더퍼드)', 'https://www.quintessa.com', 1990,
 '러더퍼드의 유기농 단일 에스테이트. 단일 와인 보르도 블렌드로 명성을 얻었다.',
 'An organic single estate in Rutherford acclaimed for its single Bordeaux-blend wine.',
 NOW(6), NOW(6)),
('그르기치 힐스', 'Grgich Hills Estate', '미국', '나파 밸리 (러더퍼드)', 'https://www.grgich.com', 1977,
 '''파리의 심판'' 우승 샤르도네를 만든 마이크 그르기치의 에스테이트. 균형 잡힌 와인으로 유명하다.',
 'The estate of Mike Grgich, who made the Judgment of Paris-winning Chardonnay, famed for its balanced wines.',
 NOW(6), NOW(6)),
('샤플렛', 'Chappellet', '미국', '나파 밸리', 'https://www.chappellet.com', 1967,
 '프리처드 힐 산악 포도밭의 선구 명가. 장기 숙성형 ''프리처드 힐'' 카베르네로 유명하다.',
 'A pioneer of mountain viticulture on Pritchard Hill, famed for its age-worthy "Pritchard Hill" Cabernet.',
 NOW(6), NOW(6)),
('본드', 'Bond Estates', '미국', '나파 밸리', 'https://www.bondestates.com', 1999,
 '할란 이스테이트가 선보인 ''그랑 크뤼'' 프로젝트. 나파의 단일 밭 카베르네 시리즈로 추앙받는다.',
 'A "grand cru" project from Harlan Estate, revered for its series of single-vineyard Napa Cabernets.',
 NOW(6), NOW(6)),
('스케어크로', 'Scarecrow', '미국', '나파 밸리 (러더퍼드)', 'https://www.scarecrowwine.com', 2003,
 '러더퍼드 옛 J.J. 코헨 농장의 올드 바인으로 만드는 컬트 카베르네. 극도의 희소성으로 유명하다.',
 'A cult Cabernet from old vines on the historic J.J. Cohn ranch in Rutherford, famed for its extreme scarcity.',
 NOW(6), NOW(6)),
-- ===================== 미국 — 소노마 / 캘리포니아 추가 =====================
('마카신', 'Marcassin', '미국', '소노마 (소노마 코스트)', NULL, 1990,
 '헬렌 털리가 만든 컬트 와이너리. 부르고뉴풍의 농밀한 샤르도네·피노 누아로 추앙받는다.',
 'A cult winery created by Helen Turley, revered for rich, Burgundian-styled Chardonnay and Pinot Noir.',
 NOW(6), NOW(6)),
('피터 마이클', 'Peter Michael Winery', '미국', '캘리포니아 (나이츠 밸리)', 'https://www.petermichaelwinery.com', 1982,
 '나이츠 밸리 산악 포도밭의 명가. 단일 밭 샤르도네와 보르도 블렌드 ''레 팡세''로 유명하다.',
 'A mountain estate in Knights Valley famed for single-vineyard Chardonnay and the Bordeaux blend "Les Pavots".',
 NOW(6), NOW(6)),
('코스타 브라운', 'Kosta Browne', '미국', '소노마 (러시안 리버 밸리)', 'https://www.kostabrowne.com', 1997,
 '러시안 리버 밸리의 인기 피노 누아 명가. 농밀하고 풍만한 캘리포니아 피노 스타일로 사랑받는다.',
 'A popular Russian River Valley Pinot Noir house beloved for its rich, plush California Pinot style.',
 NOW(6), NOW(6)),
('오 봉 클리마', 'Au Bon Climat', '미국', '캘리포니아 (산타바버라)', NULL, 1982,
 '짐 클렌데넌이 설립한 산타바버라의 선구 와이너리. 우아한 부르고뉴풍 샤르도네·피노 누아로 유명하다.',
 'A pioneering Santa Barbara winery founded by Jim Clendenen, famed for elegant Burgundian-style Chardonnay and Pinot Noir.',
 NOW(6), NOW(6)),
('시 스모크', 'Sea Smoke', '미국', '캘리포니아 (스타 라인 밸리)', 'https://www.seasmoke.com', 1999,
 '서늘한 스타 라인 밸리의 컬트 피노 누아 명가. ''텐''·''사우스''로 회원제 인기를 누린다.',
 'A cult Pinot Noir house in the cool Sta. Rita Hills, with mailing-list acclaim for its "Ten" and "Southing".',
 NOW(6), NOW(6)),
('타블라스 크릭', 'Tablas Creek', '미국', '캘리포니아 (파소 로블레스)', 'https://www.tablascreek.com', 1989,
 '보카스텔(페랭) 가문과 합작한 파소 로블레스의 명가. 론 품종 와인의 미국 선구자로 꼽힌다.',
 'A Paso Robles estate partnered with the Perrin family of Beaucastel, a US pioneer of Rhône-variety wines.',
 NOW(6), NOW(6)),
('색섬', 'Saxum Vineyards', '미국', '캘리포니아 (파소 로블레스)', 'https://www.saxumvineyards.com', 2000,
 '파소 로블레스의 컬트 와이너리. 농밀한 론풍(시라·그르나슈) 블렌드로 만점 평점을 받았다.',
 'A cult Paso Robles winery awarded perfect scores for its rich Rhône-style (Syrah, Grenache) blends.',
 NOW(6), NOW(6)),
('덕혼', 'Duckhorn Vineyards', '미국', '나파 밸리 (세인트헬레나)', 'https://www.duckhorn.com', 1976,
 '나파 메를로의 선구 명가. 대중적 세컨드 라벨 ''디코이''로도 폭넓게 사랑받는다.',
 'A pioneer of Napa Merlot, also widely loved for its popular second label "Decoy".',
 NOW(6), NOW(6)),
('메이오미', 'Meiomi', '미국', '캘리포니아', 'https://www.meiomiwines.com', 2006,
 '여러 해안 산지를 블렌딩한 인기 피노 누아 브랜드. 농밀하고 부드러운 스타일로 Vivino에서 큰 사랑을 받는다.',
 'A popular Pinot Noir brand blending several coastal regions, hugely loved on Vivino for its rich, soft style.',
 NOW(6), NOW(6)),
('더 프리즈너', 'The Prisoner Wine Company', '미국', '나파 밸리', 'https://www.theprisonerwinecompany.com', 2000,
 '진판델 중심의 진한 ''레드 블렌드''로 인기를 끈 브랜드. 독특한 라벨로도 유명하다.',
 'A brand made popular by its bold Zinfandel-based "red blend," also known for its distinctive label.',
 NOW(6), NOW(6)),
('보글 빈야드', 'Bogle Vineyards', '미국', '캘리포니아', 'https://www.boglewinery.com', 1968,
 '가족 경영의 인기 가성비 와이너리. 부드러운 ''올드 바인'' 진판델과 카베르네로 사랑받는다.',
 'A family-run value-favourite winery beloved for its smooth "Old Vine" Zinfandel and Cabernet.',
 NOW(6), NOW(6)),
('조시 셀러스', 'Josh Cellars', '미국', '캘리포니아', 'https://www.joshcellars.com', 2007,
 '아버지에게 헌정한 이름의 베스트셀러 브랜드. 부드러운 카베르네 소비뇽으로 미국에서 큰 인기를 누린다.',
 'A best-selling brand named in tribute to the founder''s father, hugely popular in the US for its smooth Cabernet Sauvignon.',
 NOW(6), NOW(6)),
-- ===================== 미국 — 오리건 / 워싱턴 추가 =====================
('도멘 세렌', 'Domaine Serene', '미국', '오리건', 'https://www.domaineserene.com', 1989,
 '윌래밋 밸리의 정상급 명가. 우아하고 정교한 피노 누아·샤르도네로 오리건을 대표한다.',
 'A top Willamette Valley estate representing Oregon with elegant, refined Pinot Noir and Chardonnay.',
 NOW(6), NOW(6)),
('보 프레르', 'Beaux Frères', '미국', '오리건', 'https://www.beauxfreres.com', 1986,
 '평론가 로버트 파커가 공동 설립한 윌래밋 밸리의 명가. 농밀한 피노 누아로 유명하다.',
 'A Willamette Valley estate co-founded by critic Robert Parker, famed for its rich Pinot Noir.',
 NOW(6), NOW(6)),
('레오네티 셀러', 'Leonetti Cellar', '미국', '워싱턴 (왈라 왈라)', 'https://www.leonetticellar.com', 1977,
 '왈라 왈라 밸리 최초의 와이너리. 워싱턴 카베르네·메를로의 컬트적 선구 명가로 꼽힌다.',
 'The first winery in Walla Walla Valley, a cult pioneer of Washington Cabernet and Merlot.',
 NOW(6), NOW(6)),
('케이유스', 'Cayuse Vineyards', '미국', '워싱턴 (왈라 왈라)', NULL, 1997,
 '''더 록스'' 자갈 토양의 바이오다이내믹 컬트 와이너리. 야성적이고 독특한 시라로 추앙받는다.',
 'A biodynamic cult winery on the stony "The Rocks" soils, revered for its wild, distinctive Syrah.',
 NOW(6), NOW(6)),
('K 빈트너스 (찰스 스미스)', 'K Vintners', '미국', '워싱턴 (왈라 왈라)', 'https://www.charlessmithwines.com', 1999,
 '찰스 스미스가 설립한 워싱턴의 록스타 와이너리. 강렬한 시라와 개성적 라벨로 유명하다.',
 'A "rock star" Washington winery founded by Charles Smith, famed for bold Syrah and bold labels.',
 NOW(6), NOW(6)),
-- ===================== 호주 추가 =====================
('다렌버그', 'd''Arenberg', '호주', '맥라렌 베일', 'https://www.darenberg.com.au', 1912,
 '맥라렌 베일의 가족 명가. 시라즈 ''더 데드 암''과 거대한 ''큐브'' 건물로 유명하다.',
 'A McLaren Vale family estate famed for its "The Dead Arm" Shiraz and its giant "Cube" building.',
 NOW(6), NOW(6)),
('투 핸즈', 'Two Hands', '호주', '바로사 밸리', 'https://www.twohandswines.com', 1999,
 '바로사 시라즈의 인기 명가. 농밀하고 풍만한 스타일로 신대륙 시라즈를 대표한다.',
 'A popular Barossa Shiraz house representing New World Shiraz with a rich, plush style.',
 NOW(6), NOW(6)),
('마운트 메리', 'Mount Mary', '호주', '야라 밸리', NULL, 1971,
 '야라 밸리의 컬트 와이너리. 우아한 보르도 블렌드 ''쿼텟''과 피노 누아로 추앙받는다.',
 'A Yarra Valley cult winery revered for its elegant Bordeaux blend "Quintet" and its Pinot Noir.',
 NOW(6), NOW(6)),
('지아콘다', 'Giaconda', '호주', '빅토리아 (비치워스)', NULL, 1982,
 '비치워스의 초소량 컬트 와이너리. 부르고뉴풍 샤르도네는 호주 최고로 꼽힌다.',
 'A tiny-production Beechworth cult winery whose Burgundian Chardonnay is rated among Australia''s finest.',
 NOW(6), NOW(6)),
('웬도우리', 'Wendouree', '호주', '클레어 밸리', NULL, 1895,
 '클레어 밸리의 전설적 컬트 와이너리. 올드 바인의 강건하고 극도로 장기 숙성형인 레드로 유명하다.',
 'A legendary Clare Valley cult winery famed for powerful, extraordinarily age-worthy reds from old vines.',
 NOW(6), NOW(6)),
('바스 펠릭스', 'Vasse Felix', '호주', '마가렛 리버', 'https://www.vassefelix.com.au', 1967,
 '마가렛 리버 최초의 와이너리. 카베르네 소비뇽과 ''샤르도네''로 이 지역을 대표한다.',
 'The first winery in Margaret River, representing the region with its Cabernet Sauvignon and Chardonnay.',
 NOW(6), NOW(6)),
('모스 우드', 'Moss Wood', '호주', '마가렛 리버', 'https://www.mosswood.com.au', 1969,
 '마가렛 리버의 컬트 명가. 우아하고 장기 숙성형인 카베르네 소비뇽으로 추앙받는다.',
 'A Margaret River cult estate revered for its elegant, age-worthy Cabernet Sauvignon.',
 NOW(6), NOW(6)),
('티렐스', 'Tyrrell''s', '호주', '헌터 밸리', 'https://www.tyrrells.com.au', 1858,
 '헌터 밸리의 역사적 가족 명가. 전설적 세미용 ''뱃 1''으로 호주 화이트의 기준을 세웠다.',
 'A historic Hunter Valley family estate that set a benchmark for Australian white with its legendary "Vat 1" Semillon.',
 NOW(6), NOW(6)),
('울프 블라스', 'Wolf Blass', '호주', '바로사 밸리', 'https://www.wolfblass.com', 1966,
 '''옐로 라벨'' 등 컬러 라벨 시리즈로 유명한 인기 대형 브랜드.',
 'A popular large brand famed for its colour-coded label range, including the "Yellow Label".',
 NOW(6), NOW(6)),
('제이콥스 크릭', 'Jacob''s Creek', '호주', '바로사 밸리', 'https://www.jacobscreek.com', 1847,
 '호주를 대표하는 대중적 대형 브랜드. 합리적 가격의 다양한 와인으로 전 세계에서 사랑받는다.',
 'A leading popular Australian brand loved worldwide for its accessible, affordable range.',
 NOW(6), NOW(6)),
('19 크라임스', '19 Crimes', '호주', '사우스오스트레일리아', 'https://www.19crimes.com', 2012,
 '유형수 이야기를 담은 라벨과 AR 기술로 화제가 된 인기 레드 브랜드.',
 'A popular red-wine brand that went viral with its convict-themed labels and augmented-reality technology.',
 NOW(6), NOW(6)),
('카셀라 (옐로 테일)', 'Casella (Yellow Tail)', '호주', '뉴사우스웨일스', 'https://www.yellowtailwine.com', 1969,
 '캥거루 라벨의 ''옐로 테일''로 세계에서 가장 많이 팔린 호주 와인 브랜드를 만든 가족 와이너리.',
 'The family winery behind "Yellow Tail," with its kangaroo label, the best-selling Australian wine brand in the world.',
 NOW(6), NOW(6)),
-- ===================== 뉴질랜드 추가 =====================
('크래기 레인지', 'Craggy Range', '뉴질랜드', '호크스 베이', 'https://www.craggyrange.com', 1998,
 '단일 포도밭 와인에 집중하는 명가. 호크스 베이 보르도 블렌드 ''소피아''와 시라로 유명하다.',
 'An estate focused on single-vineyard wines, famed for its Hawke''s Bay Bordeaux blend "Sophia" and its Syrah.',
 NOW(6), NOW(6)),
('리폰', 'Rippon', '뉴질랜드', '센트럴 오타고', 'https://www.rippon.co.nz', 1982,
 '와나카 호숫가의 바이오다이내믹 명가. 우아하고 향기로운 센트럴 오타고 피노 누아로 추앙받는다.',
 'A biodynamic estate on the shore of Lake Wanaka, revered for elegant, perfumed Central Otago Pinot Noir.',
 NOW(6), NOW(6)),
('쿠뮤 리버', 'Kumeu River', '뉴질랜드', '오클랜드', 'https://www.kumeuriver.co.nz', 1944,
 '뉴질랜드 최고의 샤르도네 명가로 꼽힌다. 부르고뉴 그랑 크뤼급으로 평가받는 화이트로 유명하다.',
 'Regarded as New Zealand''s finest Chardonnay producer, famed for whites rated alongside Burgundy''s grand crus.',
 NOW(6), NOW(6)),
('그레이와키', 'Greywacke', '뉴질랜드', '말버러', 'https://www.greywacke.com', 2009,
 '클라우디 베이 창립 양조가 케빈 저드의 와이너리. 정교한 말버러 소비뇽 블랑으로 유명하다.',
 'The winery of Kevin Judd, founding winemaker of Cloudy Bay, famed for its refined Marlborough Sauvignon Blanc.',
 NOW(6), NOW(6)),
('도그 포인트', 'Dog Point', '뉴질랜드', '말버러', 'https://www.dogpoint.co.nz', 2002,
 '클라우디 베이 출신들이 설립한 말버러 명가. 야생 효모 발효의 정교한 소비뇽 블랑·샤르도네로 유명하다.',
 'A Marlborough estate founded by Cloudy Bay alumni, famed for refined, wild-yeast Sauvignon Blanc and Chardonnay.',
 NOW(6), NOW(6)),
('브랜콧 이스테이트', 'Brancott Estate', '뉴질랜드', '말버러', 'https://www.brancottestate.com', 1934,
 '말버러 소비뇽 블랑을 세계에 알린 선구 대형 브랜드(옛 몬타나).',
 'A pioneering large brand (formerly Montana) that introduced Marlborough Sauvignon Blanc to the world.',
 NOW(6), NOW(6)),
('오이스터 베이', 'Oyster Bay', '뉴질랜드', '말버러', 'https://www.oysterbaywines.com', 1990,
 '전 세계적으로 인기 있는 뉴질랜드 대형 브랜드. 산뜻한 말버러 소비뇽 블랑으로 사랑받는다.',
 'A globally popular New Zealand brand beloved for its crisp Marlborough Sauvignon Blanc.',
 NOW(6), NOW(6)),
-- ===================== 칠레 / 아르헨티나 추가 =====================
('카사 라포스톨', 'Casa Lapostolle', '칠레', '콜차과 (아팔타)', 'https://www.lapostolle.com', 1994,
 '마르니에 라포스톨 가문이 설립한 명가. 아팔타 밸리의 컬트 와인 ''클로 아팔타''로 유명하다.',
 'An estate founded by the Marnier-Lapostolle family, famed for its Apalta Valley cult wine "Clos Apalta".',
 NOW(6), NOW(6)),
('돈 멜초르', 'Don Melchor', '칠레', '푸엔테 알토 (마이포)', 'https://www.donmelchor.com', 1987,
 '콘차 이 토로의 아이콘 와인에서 독립한 명가. 푸엔테 알토의 정상급 카베르네 소비뇽으로 꼽힌다.',
 'An estate spun off from Concha y Toro''s icon wine, ranked among Chile''s top Cabernet Sauvignons from Puente Alto.',
 NOW(6), NOW(6)),
('코우시뇨 마쿨', 'Cousiño Macul', '칠레', '마이포 밸리', 'https://www.cousinomacul.com', 1856,
 '칠레의 역사적 가족 와이너리. 수도 산티아고 인근에서 전통적 카베르네 소비뇽을 만든다.',
 'A historic Chilean family winery making traditional Cabernet Sauvignon near the capital, Santiago.',
 NOW(6), NOW(6)),
('운두라가', 'Undurraga', '칠레', '마이포 밸리', 'https://www.undurraga.cl', 1885,
 '칠레의 역사적 대형 와이너리. 폭넓은 와인과 프리미엄 라인 ''T.H.''로 알려져 있다.',
 'A historic large Chilean winery known for a broad range and its premium "T.H." (Terroir Hunter) line.',
 NOW(6), NOW(6)),
('트라피체', 'Trapiche', '아르헨티나', '멘도사', 'https://www.trapiche.com.ar', 1883,
 '아르헨티나의 역사적 대형 와이너리. 단일 밭 말벡 시리즈로 폭넓게 사랑받는다.',
 'A historic large Argentine winery widely loved for its single-vineyard Malbec series.',
 NOW(6), NOW(6)),
('수사나 발보', 'Susana Balbo Wines', '아르헨티나', '멘도사', 'https://www.susanabalbowines.com.ar', 1999,
 '아르헨티나 최초의 여성 양조가가 설립한 명가. 정교한 말벡과 토론테스로 유명하다.',
 'An estate founded by Argentina''s first female winemaker, famed for refined Malbec and Torrontés.',
 NOW(6), NOW(6)),
('엘 에네미고', 'El Enemigo', '아르헨티나', '멘도사', 'https://www.elenemigowines.com', 2009,
 '카테나의 양조가 알레한드로 비글리오네의 프로젝트. 개성 있는 말벡·카베르네 프랑으로 추앙받는다.',
 'A project by Catena winemaker Alejandro Vigil, revered for its characterful Malbec and Cabernet Franc.',
 NOW(6), NOW(6)),
('보데가 콜로메', 'Bodega Colomé', '아르헨티나', '살타 (칼차키 밸리)', 'https://www.bodegacolome.com', 1831,
 '아르헨티나에서 가장 오래된 와이너리 중 하나. 세계 최고 고도의 포도밭에서 강렬한 말벡을 만든다.',
 'One of Argentina''s oldest wineries, making intense Malbec from some of the world''s highest-altitude vineyards.',
 NOW(6), NOW(6)),
-- ===================== 남아공 / 그리스 / 레바논 / 헝가리 추가 =====================
('해밀턴 러셀', 'Hamilton Russell Vineyards', '남아공', '헤멜엔아르더', 'https://www.hamiltonrussellvineyards.com', 1976,
 '서늘한 해안 지역의 명가. 부르고뉴풍 피노 누아와 샤르도네로 남아공 최고로 꼽힌다.',
 'A leading cool-climate coastal estate ranked among South Africa''s finest for Burgundian Pinot Noir and Chardonnay.',
 NOW(6), NOW(6)),
('사디 패밀리', 'Sadie Family Wines', '남아공', '스와틀란트', NULL, 1999,
 '스와틀란트의 컬트 와이너리. 올드 바인과 토착적 표현의 ''콜룸멜라''·''팔라디우스''로 추앙받는다.',
 'A Swartland cult winery revered for its old-vine, terroir-driven "Columella" and "Palladius".',
 NOW(6), NOW(6)),
('멀리뉴', 'Mullineux', '남아공', '스와틀란트', 'https://www.mullineuxwines.com', 2007,
 '스와틀란트의 신예 명가. 시라와 슈냉 블랑, 스트로 와인으로 국제적 호평을 받았다.',
 'A young Swartland star acclaimed internationally for its Syrah, Chenin Blanc and straw wine.',
 NOW(6), NOW(6)),
('러스트 엔 프레데', 'Rust en Vrede', '남아공', '스텔렌보스', 'https://www.rustenvrede.com', 1694,
 '스텔렌보스의 역사적 레드 전문 명가. 카베르네 소비뇽·시라 블렌드로 유명하다.',
 'A historic red-wine specialist in Stellenbosch famed for its Cabernet Sauvignon and Syrah blends.',
 NOW(6), NOW(6)),
('알파 이스테이트', 'Alpha Estate', '그리스', '아민데오', 'https://www.alpha-estate.com', 1997,
 '북부 그리스의 현대 명가. 토착 품종 시노마브로와 국제 품종으로 그리스 와인을 대표한다.',
 'A modern estate in northern Greece representing Greek wine with the native Xinomavro and international varieties.',
 NOW(6), NOW(6)),
('가이아 와인스', 'Gaia Wines', '그리스', '산토리니 / 네메아', 'https://www.gaiawines.gr', 1994,
 '산토리니의 아시르티코와 네메아의 아기오르기티코를 아우르는 명가. 미네랄한 화이트로 유명하다.',
 'An estate spanning Santorini Assyrtiko and Nemea Agiorgitiko, famed for its mineral whites.',
 NOW(6), NOW(6)),
('샤토 크사라', 'Château Ksara', '레바논', '베카 밸리', 'https://www.chateauksara.com', 1857,
 '레바논에서 가장 오래된 와이너리. 베카 밸리의 보르도·론 품종 블렌드로 유명하다.',
 'The oldest winery in Lebanon, famed for its Bekaa Valley Bordeaux- and Rhône-variety blends.',
 NOW(6), NOW(6)),
('오레무스', 'Oremus', '헝가리', '토카이', 'https://www.tokajoremus.com', 1993,
 '베가 시실리아 소유의 토카이 명가. 귀부 와인 ''토카이 아수''로 유명하다.',
 'A Tokaj estate owned by Vega Sicilia, famed for its nobly sweet "Tokaji Aszú".',
 NOW(6), NOW(6));


ALTER TABLE producer ALTER COLUMN type DROP DEFAULT;
