-- =============================================================================
-- DrinkIndex 기초데이터 — 와이너리 / 와인·꼬냑 생산자 (Winery seed)
-- =============================================================================
-- 작성 기준일: 2026-05-30
-- 범위: 글로벌 종합 — 국가별/지역별로 그룹화하여 정렬 (가동 중 + 폐쇄·폐업 포함)
--       스틸 와인 와이너리 + 샹파뉴/스파클링 하우스 + 주정강화(포트·셰리·마데이라) 하우스
--       + 신흥·이색 산지(일본·중국·인도·영국·한국 등)
--       ※ 꼬냑 메종은 별도 테이블(cognac_house)로 분리 → V4__seed_cognac_house.sql
--
-- [주의]
--   - Flyway 버전 마이그레이션입니다. 한 번 적용된 후에는 이 파일을 수정하지 마세요.
--     (체크섬 검증 실패로 기동이 막힙니다. 보정이 필요하면 V4__*.sql 로 추가하세요.)
--   - country 는 "생산국" 기준, region 은 와인 산지(아펠라시옹/지역) 기준으로 표기합니다.
--   - founded_year 는 와이너리(에스테이트/메종) 설립 연도 기준입니다. 보르도 등 일부 고성(古城)은
--     기원이 중세까지 거슬러 올라가나, 통상 인용되는 설립/현재 형태 성립 연도를 사용하고 보충은
--     description 에 적었습니다.
--   - website 가 확실치 않은 경우 추측 URL 대신 NULL 로 두었습니다. (폐쇄·소형 생산자 등)
--   - 운영상태 컬럼이 스키마에 없으므로, 폐쇄·폐업·부활 여부는 description 에 명시했습니다.
--     각 국가/지역 그룹 안에서 가동 중 → 폐쇄/역사적 순으로 배치했습니다.
--     (와인업계는 위스키 증류소처럼 ''폐쇄''가 드물어, 폐업보다는 부활/소유권 변경 사례가 많습니다.)
-- =============================================================================

INSERT INTO winery
    (name_ko, name_en, country, region, website, founded_year, description_ko, description_en, created_at, updated_at)
VALUES
-- ===================== 프랑스 — 보르도 (Bordeaux) =====================
('샤토 라피트 로칠드', 'Château Lafite Rothschild', '프랑스', '보르도 (포이약)', 'https://www.lafite.com', 1868,
 '포이약의 1등급(프르미에 크뤼) 샤토. 1868년 로칠드 가문이 인수했으며 우아하고 섬세한 스타일로 보르도 최정상으로 꼽힌다.',
 'A First Growth château in Pauillac, acquired by the Rothschild family in 1868, prized for its elegant, refined style at the pinnacle of Bordeaux.',
 NOW(6), NOW(6)),
('샤토 라투르', 'Château Latour', '프랑스', '보르도 (포이약)', 'https://www.chateau-latour.com', 1331,
 '포이약의 1등급 샤토. 14세기 탑(라투르)에서 이름을 따왔으며, 장기 숙성력과 묵직하고 강건한 스타일로 유명하다.',
 'A First Growth in Pauillac named after its 14th-century tower, famed for powerful, long-lived and structured wines.',
 NOW(6), NOW(6)),
('샤토 마고', 'Château Margaux', '프랑스', '보르도 (마고)', 'https://www.chateau-margaux.com', 1572,
 '마고 마을의 1등급 샤토. 향기롭고 우아한 ''벨벳 같은'' 스타일의 전형으로 평가받는다.',
 'A First Growth in the Margaux appellation, regarded as the archetype of a fragrant, elegant and velvety style.',
 NOW(6), NOW(6)),
('샤토 무통 로칠드', 'Château Mouton Rothschild', '프랑스', '보르도 (포이약)', 'https://www.chateau-mouton-rothschild.com', 1853,
 '1853년 로칠드 가문이 취득. 1973년 2등급에서 1등급으로 승격된 유일한 샤토이며, 매년 유명 화가의 라벨 아트로도 유명하다.',
 'Acquired by the Rothschilds in 1853, the only château promoted from Second to First Growth (1973), also famed for its annual artist-designed labels.',
 NOW(6), NOW(6)),
('샤토 오브리옹', 'Château Haut-Brion', '프랑스', '보르도 (페삭레오냥)', 'https://www.haut-brion.com', 1525,
 '그라브(페삭레오냥)에 위치한 유일한 1등급 샤토. 보르도에서 가장 오래된 명문 중 하나로 흙내음과 복합미가 특징이다.',
 'The only First Growth located in Graves (Pessac-Léognan), one of Bordeaux''s oldest estates, known for earthy complexity.',
 NOW(6), NOW(6)),
('샤토 슈발 블랑', 'Château Cheval Blanc', '프랑스', '보르도 (생테밀리옹)', 'https://www.chateau-chevalblanc.com', 1832,
 '생테밀리옹 최고 등급(프르미에 그랑 크뤼 클라세 A) 샤토. 카베르네 프랑 비중이 높은 화려하고 관능적인 스타일로 유명하다.',
 'A top-ranked Saint-Émilion estate (Premier Grand Cru Classé A), famed for its opulent, sensual style with a high proportion of Cabernet Franc.',
 NOW(6), NOW(6)),
('샤토 오존', 'Château Ausone', '프랑스', '보르도 (생테밀리옹)', NULL, 1781,
 '생테밀리옹의 최정상 샤토 중 하나. 석회암 비탈의 극소량 생산으로 희소성이 높다.',
 'One of the most prestigious Saint-Émilion estates, scarce due to tiny production on its limestone hillside.',
 NOW(6), NOW(6)),
('페트뤼스', 'Petrus', '프랑스', '보르도 (포므롤)', NULL, 1750,
 '포므롤의 전설적 샤토. 등급 제도가 없는 포므롤이지만 거의 100% 메를로로 만든 와인은 세계 최고가에 거래된다.',
 'The legendary Pomerol estate; though Pomerol has no classification, its near-100% Merlot wine ranks among the most expensive in the world.',
 NOW(6), NOW(6)),
('르 팽', 'Le Pin', '프랑스', '보르도 (포므롤)', NULL, 1979,
 '포므롤의 초소형 ''갸라지'' 와이너리. 단 2헥타르 남짓에서 나오는 극소량 메를로로 컬트적 인기를 누린다.',
 'A tiny Pomerol "garage" winery; its minuscule Merlot output from barely two hectares has earned a cult following.',
 NOW(6), NOW(6)),
('샤토 디켐', 'Château d''Yquem', '프랑스', '보르도 (소테른)', 'https://www.yquem.fr', 1593,
 '소테른의 유일한 특1등급(프르미에 크뤼 쉬페리외르) 샤토. 귀부병 포도로 만드는 세계 최고의 스위트 와인으로 꼽힌다.',
 'The only Premier Cru Supérieur of Sauternes, producing what is regarded as the world''s greatest sweet wine from nobly rotted grapes.',
 NOW(6), NOW(6)),
('샤토 피숑 롱그빌 콩테스 드 라랑드', 'Château Pichon Longueville Comtesse de Lalande', '프랑스', '보르도 (포이약)', 'https://www.pichon-lalande.com', 1850,
 '포이약의 2등급 샤토. ''슈퍼 세컨드''로 불리며 우아하고 향기로운 스타일로 정평이 나 있다.',
 'A Second Growth in Pauillac, a celebrated "Super Second" known for its elegant, perfumed style.',
 NOW(6), NOW(6)),
('샤토 코스 데스투르넬', 'Château Cos d''Estournel', '프랑스', '보르도 (생테스테프)', 'https://www.cosestournel.com', 1811,
 '생테스테프의 2등급 샤토. 동양풍 파고다 건축물과 이국적·강건한 스타일로 ''슈퍼 세컨드''의 대표격이다.',
 'A Saint-Estèphe Second Growth with distinctive pagoda architecture, a leading "Super Second" known for its exotic, powerful style.',
 NOW(6), NOW(6)),
('샤토 레오빌 라스 카즈', 'Château Léoville Las Cases', '프랑스', '보르도 (생쥘리앵)', NULL, 1638,
 '생쥘리앵의 2등급 샤토. 1등급에 버금가는 품질로 평가받는 ''슈퍼 세컨드''의 상징이다.',
 'A Saint-Julien Second Growth widely rated near First Growth quality, an emblematic "Super Second".',
 NOW(6), NOW(6)),
('샤토 팔메', 'Château Palmer', '프랑스', '보르도 (마고)', 'https://www.chateau-palmer.com', 1814,
 '마고의 3등급 샤토이나 1등급에 견줄 품질로 명성이 높다. 메를로 비중이 높은 화려한 스타일이 특징이다.',
 'A Margaux Third Growth long renowned for First-Growth-rivalling quality, known for an opulent style with a high Merlot share.',
 NOW(6), NOW(6)),
('샤토 랭슈 바주', 'Château Lynch-Bages', '프랑스', '보르도 (포이약)', 'https://www.lynchbages.com', 1749,
 '포이약의 5등급 샤토이나 ''가난한 자의 무통''으로 불릴 만큼 높은 가성비와 품질로 사랑받는다.',
 'A Pauillac Fifth Growth so well regarded it is nicknamed "the poor man''s Mouton," beloved for value and quality.',
 NOW(6), NOW(6)),
('샤토 퐁테 카네', 'Château Pontet-Canet', '프랑스', '보르도 (포이약)', 'https://www.pontet-canet.com', 1725,
 '포이약의 5등급 샤토. 바이오다이내믹 농법 전환 후 품질이 급상승해 컬트적 인기를 얻었다.',
 'A Pauillac Fifth Growth whose quality soared after converting to biodynamic viticulture, earning a cult following.',
 NOW(6), NOW(6)),
('샤토 앙젤뤼스', 'Château Angélus', '프랑스', '보르도 (생테밀리옹)', 'https://www.angelus.com', 1782,
 '생테밀리옹의 명문 샤토. 카베르네 프랑 비중이 높은 풍만한 스타일로 영화 007에 등장하며 유명해졌다.',
 'A prestigious Saint-Émilion estate known for a rich, Cabernet-Franc-driven style, made famous by its appearance in a James Bond film.',
 NOW(6), NOW(6)),
('샤토 피작', 'Château Figeac', '프랑스', '보르도 (생테밀리옹)', 'https://www.chateau-figeac.com', 1838,
 '생테밀리옹 최고 등급(프르미에 그랑 크뤼 클라세 A) 샤토. 카베르네 비중이 높은 보르도 좌안풍의 우아한 스타일이 특징이다.',
 'A Saint-Émilion Premier Grand Cru Classé A, distinctive for its high Cabernet content and an elegant, Left-Bank-like style.',
 NOW(6), NOW(6)),
('샤토 스미스 오 라피트', 'Château Smith Haut Lafitte', '프랑스', '보르도 (페삭레오냥)', 'https://www.smith-haut-lafitte.com', 1365,
 '페삭레오냥의 그랑 크뤼 클라세. 레드·화이트 모두 뛰어나며 인근 스파(레 소르스 드 코달리)로도 유명하다.',
 'A Pessac-Léognan Grand Cru Classé excelling in both red and white, also famed for its adjacent Caudalíe vinotherapy spa.',
 NOW(6), NOW(6)),
('샤토 소시앙도 말레', 'Château Sociando-Mallet', '프랑스', '보르도 (오메도크)', 'https://www.sociandomallet.com', 1633,
 '등급에 속하지 않은 오메도크의 ''크뤼 부르주아''이나, 등급 샤토에 버금가는 장기 숙성력으로 명성이 높다.',
 'An unclassified Haut-Médoc "Cru Bourgeois" renowned for ageing potential rivalling classified growths.',
 NOW(6), NOW(6)),
-- ===================== 프랑스 — 부르고뉴 (Bourgogne) =====================
('도멘 드 라 로마네 콩티', 'Domaine de la Romanée-Conti', '프랑스', '부르고뉴 (본로마네)', NULL, 1869,
 '''DRC''로 불리는 부르고뉴의 정점. 로마네 콩티 등 그랑 크뤼 단일 밭에서 세계 최고가의 피노 누아를 만든다.',
 'Known as "DRC," the summit of Burgundy, producing the world''s most expensive Pinot Noir from grand cru monopoles such as Romanée-Conti.',
 NOW(6), NOW(6)),
('도멘 르루아', 'Domaine Leroy', '프랑스', '부르고뉴 (본로마네)', NULL, 1988,
 '라루 비즈 르루아가 이끄는 바이오다이내믹 도멘. 극소량·고품질 그랑 크뤼로 DRC와 쌍벽을 이룬다.',
 'A biodynamic domaine led by Lalou Bize-Leroy, rivalling DRC with tiny-volume, ultra-high-quality grand crus.',
 NOW(6), NOW(6)),
('도멘 아르망 루소', 'Domaine Armand Rousseau', '프랑스', '부르고뉴 (주브레샹베르탱)', NULL, 1909,
 '주브레샹베르탱의 최정상 도멘. 샹베르탱·클로 드 베즈 등 그랑 크뤼로 부르고뉴 레드의 기준으로 꼽힌다.',
 'The leading domaine of Gevrey-Chambertin, a benchmark for red Burgundy through grand crus like Chambertin and Clos de Bèze.',
 NOW(6), NOW(6)),
('도멘 콩트 조르주 드 보귀에', 'Domaine Comte Georges de Vogüé', '프랑스', '부르고뉴 (샹볼뮈지니)', NULL, 1450,
 '샹볼뮈지니의 명문 도멘. 뮈지니 그랑 크뤼 대부분을 소유하며 우아함의 정수로 평가받는다.',
 'A historic Chambolle-Musigny domaine owning the lion''s share of Musigny grand cru, esteemed as the essence of elegance.',
 NOW(6), NOW(6)),
('도멘 메오 카뮈제', 'Domaine Méo-Camuzet', '프랑스', '부르고뉴 (본로마네)', 'https://www.meo-camuzet.com', 1920,
 '본로마네의 명문 도멘. 전설적 양조가 앙리 자이에의 영향을 받아 현대 부르고뉴의 정상급으로 도약했다.',
 'A Vosne-Romanée domaine that rose to the top tier of modern Burgundy under the influence of the legendary Henri Jayer.',
 NOW(6), NOW(6)),
('도멘 르플레브', 'Domaine Leflaive', '프랑스', '부르고뉴 (퓔리니몽라셰)', 'https://www.leflaive.fr', 1717,
 '퓔리니몽라셰의 화이트 명문. 바이오다이내믹 농법으로 세계 최고의 샤르도네를 만든다.',
 'The premier white-wine domaine of Puligny-Montrachet, crafting some of the world''s greatest Chardonnay biodynamically.',
 NOW(6), NOW(6)),
('도멘 코슈 뒤리', 'Domaine Coche-Dury', '프랑스', '부르고뉴 (뫼르소)', NULL, 1940,
 '뫼르소의 컬트 화이트 도멘. 미네랄리티와 장기 숙성력을 갖춘 샤르도네로 수집가들의 표적이 된다.',
 'A cult white-wine domaine in Meursault whose mineral, age-worthy Chardonnay is hunted by collectors.',
 NOW(6), NOW(6)),
('도멘 뒤자크', 'Domaine Dujac', '프랑스', '부르고뉴 (모레생드니)', 'https://www.dujac.com', 1967,
 '모레생드니의 현대 명문 도멘. 줄기를 함께 발효하는 홀 클러스터 기법의 향기로운 피노 누아로 유명하다.',
 'A modern Morey-Saint-Denis domaine famed for perfumed, whole-cluster-fermented Pinot Noir.',
 NOW(6), NOW(6)),
('메종 루이 자도', 'Maison Louis Jadot', '프랑스', '부르고뉴 (본)', 'https://www.louisjadot.com', 1859,
 '본에 본거지를 둔 부르고뉴 대표 네고시앙 겸 도멘. 광범위한 아펠라시옹의 안정적 품질로 명성이 높다.',
 'A leading Beaune-based Burgundy négociant and domaine, esteemed for consistent quality across a wide range of appellations.',
 NOW(6), NOW(6)),
('메종 조제프 드루앵', 'Maison Joseph Drouhin', '프랑스', '부르고뉴 (본)', 'https://www.drouhin.com', 1880,
 '본의 가족 경영 네고시앙 겸 도멘. 일찍이 바이오다이내믹을 도입했으며 오리건에도 진출했다.',
 'A family-run Beaune négociant-domaine, an early adopter of biodynamics that also expanded into Oregon.',
 NOW(6), NOW(6)),
('메종 루이 라투르', 'Maison Louis Latour', '프랑스', '부르고뉴 (본)', 'https://www.louislatour.com', 1797,
 '본의 유서 깊은 가족 네고시앙. 코르통샤를마뉴 등 그랑 크뤼 화이트로 특히 유명하다.',
 'A historic family négociant in Beaune, especially renowned for grand cru whites such as Corton-Charlemagne.',
 NOW(6), NOW(6)),
('메종 부샤르 페르 에 피스', 'Bouchard Père & Fils', '프랑스', '부르고뉴 (본)', 'https://www.bouchard-pereetfils.com', 1731,
 '본 성(샤토 드 본)에 본거지를 둔 부르고뉴 최대급 도멘 보유 네고시앙. 방대한 그랑 크뤼 밭을 소유한다.',
 'A négociant headquartered in the Château de Beaune, holding one of Burgundy''s largest grand cru vineyard estates.',
 NOW(6), NOW(6)),
('메종 페블레', 'Maison Faiveley', '프랑스', '부르고뉴 (뉘생조르주)', 'https://www.domaine-faiveley.com', 1825,
 '뉘생조르주의 가족 경영 도멘 겸 네고시앙. 코트 드 뉘와 코트 샬로네즈에 폭넓은 밭을 보유한다.',
 'A family-owned Nuits-Saint-Georges domaine and négociant with extensive holdings across the Côte de Nuits and Côte Chalonnaise.',
 NOW(6), NOW(6)),
('샤블리 도멘 윌리암 페브르', 'Domaine William Fèvre', '프랑스', '부르고뉴 (샤블리)', 'https://www.williamfevre.com', 1959,
 '샤블리 최대의 그랑 크뤼 밭을 보유한 명문 도멘. 순수하고 미네랄한 샤블리 스타일의 기준으로 꼽힌다.',
 'A leading Chablis domaine with the largest grand cru holdings, a benchmark for pure, mineral Chablis.',
 NOW(6), NOW(6)),
-- ===================== 프랑스 — 론 (Rhône) =====================
('E. 기갈', 'E. Guigal', '프랑스', '론 (코트로티)', 'https://www.guigal.com', 1946,
 '북부 론의 명가. 코트로티의 단일 밭 ''라라라''(라 물린·라 랑돈·라 튀르크)로 세계적 명성을 얻었다.',
 'A Northern Rhône powerhouse, world-famous for its single-vineyard Côte-Rôtie "La-Las" (La Mouline, La Landonne, La Turque).',
 NOW(6), NOW(6)),
('M. 샤푸티에', 'M. Chapoutier', '프랑스', '론 (에르미타주)', 'https://www.chapoutier.com', 1808,
 '론을 대표하는 가족 경영 도멘 겸 네고시앙. 바이오다이내믹 농법과 점자 라벨로도 유명하다.',
 'A leading family Rhône domaine and négociant, also known for biodynamics and its Braille-embossed labels.',
 NOW(6), NOW(6)),
('폴 자불레 애네', 'Paul Jaboulet Aîné', '프랑스', '론 (에르미타주)', 'https://www.jaboulet.com', 1834,
 '에르미타주의 명문. 전설적 ''라 샤펠''로 북부 론 시라의 기준을 세웠다.',
 'A Hermitage institution that set the standard for Northern Rhône Syrah with its legendary "La Chapelle".',
 NOW(6), NOW(6)),
('샤토 드 보카스텔', 'Château de Beaucastel', '프랑스', '론 (샤토뇌프뒤파프)', 'https://www.beaucastel.com', 1909,
 '샤토뇌프뒤파프의 정상급 도멘. 허용된 13개 품종을 모두 사용하는 전통적·장기 숙성형 스타일로 유명하다.',
 'A top Châteauneuf-du-Pape estate famed for using all 13 permitted grape varieties in a traditional, age-worthy style.',
 NOW(6), NOW(6)),
('샤토 라야스', 'Château Rayas', '프랑스', '론 (샤토뇌프뒤파프)', NULL, 1880,
 '100% 그르나슈만 사용하는 샤토뇌프뒤파프의 컬트 도멘. 향기롭고 섬세한 ''부르고뉴풍'' 스타일로 추앙받는다.',
 'A cult Châteauneuf-du-Pape estate using 100% Grenache, revered for its perfumed, delicate "Burgundian" style.',
 NOW(6), NOW(6)),
-- ===================== 프랑스 — 루아르 / 알자스 =====================
('도멘 디디에 다그노', 'Domaine Didier Dagueneau', '프랑스', '루아르 (푸이퓌메)', 'https://www.didierdagueneau.fr', 1982,
 '푸이퓌메의 소비뇽 블랑을 예술의 경지로 끌어올린 컬트 도멘. ''실렉스'' 등 단일 밭 화이트로 유명하다.',
 'A cult Pouilly-Fumé domaine that elevated Sauvignon Blanc to an art form, famed for single-vineyard whites such as "Silex".',
 NOW(6), NOW(6)),
('메종 트림바흐', 'Maison Trimbach', '프랑스', '알자스', 'https://www.maison-trimbach.com', 1626,
 '알자스의 명문 가족 하우스. 드라이하고 정교한 리슬링 ''클로 생튄''으로 세계적 명성을 얻었다.',
 'A historic Alsace family house, world-renowned for its dry, precise Riesling "Clos Sainte Hune".',
 NOW(6), NOW(6)),
('메종 위겔', 'Hugel & Fils', '프랑스', '알자스', 'https://www.hugel.com', 1639,
 '리크위르에 자리한 알자스 명가. 380여 년에 걸친 가족 경영으로 알자스 화이트의 대표주자다.',
 'An Alsace icon in Riquewihr, a flagship of Alsace white wine through nearly four centuries of family ownership.',
 NOW(6), NOW(6)),
('도멘 진트 훔브레히트', 'Domaine Zind-Humbrecht', '프랑스', '알자스', 'https://www.zindhumbrecht.fr', 1959,
 '알자스의 바이오다이내믹 선구 도멘. 진하고 응축된 그랑 크뤼 리슬링·게뷔르츠트라미너로 유명하다.',
 'A pioneering biodynamic Alsace domaine known for rich, concentrated grand cru Riesling and Gewurztraminer.',
 NOW(6), NOW(6)),
-- ===================== 프랑스 — 샹파뉴 (Champagne) =====================
('동 페리뇽 (모엣 샹동)', 'Dom Pérignon (Moët & Chandon)', '프랑스', '샹파뉴 (에페르네)', 'https://www.domperignon.com', 1936,
 '모엣 샹동의 프레스티지 퀴베. 빈티지 샴페인만 출시하며 샴페인의 대명사로 통한다.',
 'The prestige cuvée of Moët & Chandon, released only as vintage Champagne and synonymous with luxury fizz.',
 NOW(6), NOW(6)),
('크룩', 'Krug', '프랑스', '샹파뉴 (랭스)', 'https://www.krug.com', 1843,
 '오크통 발효와 다년 리저브 블렌딩을 고수하는 프레스티지 샴페인 하우스. 농밀하고 복합적인 스타일로 추앙받는다.',
 'A prestige Champagne house using oak fermentation and multi-year reserve blending, revered for its rich, complex style.',
 NOW(6), NOW(6)),
('루이 로드레', 'Louis Roederer', '프랑스', '샹파뉴 (랭스)', 'https://www.louis-roederer.com', 1776,
 '가족 경영 샴페인 하우스. 러시아 황실을 위해 만든 프레스티지 퀴베 ''크리스탈''로 유명하다.',
 'A family-owned Champagne house famed for "Cristal," the prestige cuvée originally created for the Russian Tsar.',
 NOW(6), NOW(6)),
('볼랭저', 'Bollinger', '프랑스', '샹파뉴 (아이)', 'https://www.champagne-bollinger.com', 1829,
 '피노 누아 비중이 높은 묵직한 스타일의 명문 하우스. 007 제임스 본드의 공식 샴페인으로도 유명하다.',
 'A prestigious house known for a powerful, Pinot-Noir-rich style, also famed as James Bond''s official Champagne.',
 NOW(6), NOW(6)),
('뵈브 클리코', 'Veuve Clicquot', '프랑스', '샹파뉴 (랭스)', 'https://www.veuveclicquot.com', 1772,
 '''샴페인의 여제'' 마담 클리코가 리들링(르뮈아주) 기법을 발전시킨 역사적 하우스. 노란 라벨로 유명하다.',
 'A historic house where the "Grande Dame" Madame Clicquot perfected riddling, instantly recognised by its yellow label.',
 NOW(6), NOW(6)),
('폴 로저', 'Pol Roger', '프랑스', '샹파뉴 (에페르네)', 'https://www.polroger.com', 1849,
 '에페르네의 가족 경영 하우스. 윈스턴 처칠이 사랑한 샴페인으로 유명하며 프레스티지 퀴베에 그의 이름을 붙였다.',
 'A family house in Épernay famed as Winston Churchill''s favourite Champagne, whose prestige cuvée bears his name.',
 NOW(6), NOW(6)),
('테탱저', 'Taittinger', '프랑스', '샹파뉴 (랭스)', 'https://www.taittinger.com', 1734,
 '샤르도네 비중이 높은 우아한 스타일의 가족 하우스. 프레스티지 퀴베 ''콩트 드 샹파뉴''로 유명하다.',
 'A family house known for an elegant, Chardonnay-led style and its prestige cuvée "Comtes de Champagne".',
 NOW(6), NOW(6)),
('뤼나르', 'Ruinart', '프랑스', '샹파뉴 (랭스)', 'https://www.ruinart.com', 1729,
 '세계 최초로 설립된 샴페인 하우스. 샤르도네 중심의 섬세하고 우아한 스타일이 특징이다.',
 'The oldest established Champagne house in the world, characterised by a delicate, Chardonnay-focused elegance.',
 NOW(6), NOW(6)),
('살롱', 'Salon', '프랑스', '샹파뉴 (르메닐쉬르오제)', NULL, 1911,
 '단일 마을·단일 품종(샤르도네)·단일 빈티지만 만드는 전설적 블랑 드 블랑 하우스. 작황이 좋은 해에만 출시한다.',
 'A legendary Blanc de Blancs house making only single-village, single-variety (Chardonnay), single-vintage wine, released solely in great years.',
 NOW(6), NOW(6)),
('빌카르 살몽', 'Billecart-Salmon', '프랑스', '샹파뉴 (마뢰이쉬르아이)', 'https://www.champagne-billecart.fr', 1818,
 '저온 장기 발효로 섬세함을 추구하는 가족 하우스. 특히 로제 샴페인의 기준으로 꼽힌다.',
 'A family house pursuing finesse through long, cold fermentation, regarded as a benchmark for rosé Champagne.',
 NOW(6), NOW(6)),
('페리에 주에', 'Perrier-Jouët', '프랑스', '샹파뉴 (에페르네)', 'https://www.perrier-jouet.com', 1811,
 '꽃 같은 화사한 스타일의 하우스. 아네모네 꽃이 그려진 프레스티지 퀴베 ''벨 에포크''로 유명하다.',
 'A house known for a floral style, famed for its "Belle Époque" prestige cuvée adorned with painted anemones.',
 NOW(6), NOW(6)),
('로랑 페리에', 'Laurent-Perrier', '프랑스', '샹파뉴 (투르쉬르마른)', 'https://www.laurent-perrier.com', 1812,
 '신선하고 가벼운 스타일의 대형 가족 하우스. 색이 진한 ''퀴베 로제''로 특히 유명하다.',
 'A large family house with a fresh, light style, especially celebrated for its richly coloured "Cuvée Rosé".',
 NOW(6), NOW(6)),
-- (꼬냑 메종은 별도 테이블 cognac_house 로 분리 → V4__seed_cognac_house.sql 참조)
-- ===================== 이탈리아 — 피에몬테 (Piemonte) =====================
('가야', 'Gaja', '이탈리아', '피에몬테 (바르바레스코)', 'https://www.gaja.com', 1859,
 '이탈리아 와인의 세계화를 이끈 피에몬테의 상징. 안젤로 가야가 바르바레스코·바롤로를 명품 반열에 올렸다.',
 'The symbol of Piedmont that led the globalisation of Italian wine, with Angelo Gaja elevating Barbaresco and Barolo to icon status.',
 NOW(6), NOW(6)),
('자코모 콘테르노', 'Giacomo Conterno', '이탈리아', '피에몬테 (바롤로)', NULL, 1908,
 '바롤로 전통주의의 정점. 전설적 ''몬포르티노'' 리제르바로 세계 최고의 네비올로를 만든다.',
 'The pinnacle of traditionalist Barolo, producing some of the world''s finest Nebbiolo with its legendary "Monfortino" Riserva.',
 NOW(6), NOW(6)),
('브루노 자코사', 'Bruno Giacosa', '이탈리아', '피에몬테 (바르바레스코)', 'https://www.brunogiacosa.it', 1900,
 '''피에몬테의 천재''로 불린 양조가의 와이너리. 붉은 라벨 리제르바로 바롤로·바르바레스코의 정수를 보여준다.',
 'The winery of a vintner hailed as "the genius of Piedmont," whose red-label Riservas epitomise Barolo and Barbaresco.',
 NOW(6), NOW(6)),
('비에티', 'Vietti', '이탈리아', '피에몬테 (카스틸리오네 팔레토)', 'https://www.vietti.com', 1919,
 '단일 밭(크뤼) 바롤로와 예술가 라벨로 유명한 피에몬테 명가.',
 'A renowned Piedmont estate known for single-vineyard (cru) Barolo and its artist-designed labels.',
 NOW(6), NOW(6)),
('피오 체사레', 'Pio Cesare', '이탈리아', '피에몬테 (알바)', 'https://www.piocesare.it', 1881,
 '알바 시내에 자리한 가족 경영 명가. 전통과 현대를 아우르는 바롤로·바르바레스코로 정평이 나 있다.',
 'A family estate in the town of Alba, esteemed for Barolo and Barbaresco that bridge tradition and modernity.',
 NOW(6), NOW(6)),
('바르톨로 마스카렐로', 'Bartolo Mascarello', '이탈리아', '피에몬테 (바롤로)', NULL, 1918,
 '단일 밭 분리를 거부하고 전통 블렌딩 바롤로를 고수하는 컬트 와이너리. ''No Barrique, No Berlusconi'' 라벨로도 유명하다.',
 'A cult estate that rejects single-vineyard bottlings in favour of traditional blended Barolo, famous for its "No Barrique, No Berlusconi" label.',
 NOW(6), NOW(6)),
-- ===================== 이탈리아 — 토스카나 (Toscana) =====================
('안티노리', 'Marchesi Antinori', '이탈리아', '토스카나 (키안티 클라시코)', 'https://www.antinori.it', 1385,
 '600년 넘게 이어온 토스카나의 명문. ''슈퍼 투스칸'' 티냐넬로·솔라이아로 이탈리아 와인 혁명을 이끌었다.',
 'A Tuscan dynasty spanning over six centuries, leading the Italian wine revolution with its Super Tuscans Tignanello and Solaia.',
 NOW(6), NOW(6)),
('테누타 산 귀도 (사시카이아)', 'Tenuta San Guido (Sassicaia)', '이탈리아', '토스카나 (볼게리)', 'https://www.tenutasanguido.com', 1968,
 '최초의 슈퍼 투스칸 ''사시카이아''를 탄생시킨 볼게리의 에스테이트. 보르도 품종으로 만든 와인이 단독 DOC를 받았다.',
 'The Bolgheri estate that created the first Super Tuscan, "Sassicaia," whose Bordeaux-variety wine earned its own DOC.',
 NOW(6), NOW(6)),
('오르넬라이아', 'Ornellaia', '이탈리아', '토스카나 (볼게리)', 'https://www.ornellaia.com', 1981,
 '볼게리의 슈퍼 투스칸 명가. 보르도 블렌드의 화려하고 풍만한 스타일과 단일 메를로 ''마세토''로 유명하다.',
 'A Bolgheri Super Tuscan estate famed for its opulent Bordeaux blend and the single-vineyard Merlot "Masseto".',
 NOW(6), NOW(6)),
('마세토', 'Masseto', '이탈리아', '토스카나 (볼게리)', 'https://www.masseto.com', 1986,
 '오르넬라이아에서 분리·독립한 단일 밭 메를로. ''이탈리아의 페트뤼스''로 불리며 세계 최고가 메를로로 평가받는다.',
 'A single-vineyard Merlot spun off from Ornellaia, dubbed "the Petrus of Italy" and ranked among the world''s greatest Merlots.',
 NOW(6), NOW(6)),
('비온디 산티', 'Biondi-Santi', '이탈리아', '토스카나 (몬탈치노)', 'https://www.biondisanti.com', 1888,
 '브루넬로 디 몬탈치노를 창시한 역사적 에스테이트. 극도의 장기 숙성력을 지닌 산지오베제로 유명하다.',
 'The historic estate that invented Brunello di Montalcino, famed for extraordinarily age-worthy Sangiovese.',
 NOW(6), NOW(6)),
('프레스코발디', 'Frescobaldi', '이탈리아', '토스카나', 'https://www.frescobaldi.com', 1308,
 '700년 역사의 토스카나 명문 가문. 몬탈치노·키안티 등 여러 명품 에스테이트를 거느린다.',
 'A 700-year-old Tuscan noble family controlling several prestige estates across Montalcino, Chianti and beyond.',
 NOW(6), NOW(6)),
('카스텔로 반피', 'Castello Banfi', '이탈리아', '토스카나 (몬탈치노)', 'https://www.castellobanfi.com', 1978,
 '몬탈치노 최대 규모의 현대적 에스테이트. 연구 기반 양조로 브루넬로의 국제적 명성을 높였다.',
 'The largest modern estate in Montalcino, raising Brunello''s global profile through research-driven winemaking.',
 NOW(6), NOW(6)),
-- ===================== 이탈리아 — 베네토 (Veneto) =====================
('마시', 'Masi Agricola', '이탈리아', '베네토 (발폴리첼라)', 'https://www.masi.it', 1772,
 '아마로네의 대명사로 꼽히는 발폴리첼라의 명가. 포도를 말려 농축하는 ''아파시멘토'' 기법의 대가다.',
 'A Valpolicella estate synonymous with Amarone, a master of the "appassimento" grape-drying technique.',
 NOW(6), NOW(6)),
('주세페 퀸타렐리', 'Giuseppe Quintarelli', '이탈리아', '베네토 (발폴리첼라)', NULL, 1924,
 '''아마로네의 신''으로 추앙받는 전설적 컬트 와이너리. 극도로 긴 숙성과 전통 방식으로 희소한 명작을 만든다.',
 'A legendary cult winery revered as "the god of Amarone," crafting scarce masterpieces through extremely long ageing and traditional methods.',
 NOW(6), NOW(6)),
('달 포르노 로마노', 'Dal Forno Romano', '이탈리아', '베네토 (발폴리첼라)', 'https://www.dalfornoromano.it', 1983,
 '현대적·고농축 스타일을 대표하는 발폴리첼라의 컬트 생산자. 퀸타렐리와 함께 아마로네의 양대 산맥으로 꼽힌다.',
 'A cult Valpolicella producer epitomising the modern, concentrated style, ranked alongside Quintarelli as a twin peak of Amarone.',
 NOW(6), NOW(6)),
('알레그리니', 'Allegrini', '이탈리아', '베네토 (발폴리첼라)', 'https://www.allegrini.it', 1854,
 '발폴리첼라 클라시코의 명가. 단일 밭 ''라 포자'' 등 현대적이고 우아한 아마로네로 유명하다.',
 'A leading Valpolicella Classico estate known for modern, refined Amarone and single-vineyard wines such as "La Poja".',
 NOW(6), NOW(6)),
-- ===================== 이탈리아 — 기타 (시칠리아·캄파니아) =====================
('플라네타', 'Planeta', '이탈리아', '시칠리아', 'https://www.planeta.it', 1995,
 '시칠리아 와인의 현대적 르네상스를 이끈 가족 와이너리. 토착·국제 품종을 두루 다룬다.',
 'A family winery that led the modern renaissance of Sicilian wine, working with both native and international varieties.',
 NOW(6), NOW(6)),
('마스트로베라르디노', 'Mastroberardino', '이탈리아', '캄파니아', 'https://www.mastroberardino.com', 1878,
 '캄파니아의 토착 품종(알리아니코·피아노 등)을 지켜낸 역사적 와이너리. 폼페이 고고학 양조 프로젝트로도 유명하다.',
 'A historic Campania winery that safeguarded native varieties (Aglianico, Fiano), also famed for its Pompeii archaeological vineyard project.',
 NOW(6), NOW(6)),
-- ===================== 스페인 — 리오하 / 리베라 / 프리오라트 =====================
('마르케스 데 리스칼', 'Marqués de Riscal', '스페인', '리오하', 'https://www.marquesderiscal.com', 1858,
 '리오하의 가장 오래된 와이너리 중 하나. 프랭크 게리가 설계한 미래적 호텔로도 유명하다.',
 'One of the oldest wineries in Rioja, also famous for its futuristic Frank Gehry-designed hotel.',
 NOW(6), NOW(6)),
('라 리오하 알타', 'La Rioja Alta', '스페인', '리오하', 'https://www.riojalta.com', 1890,
 '전통적 장기 숙성 리오하의 명가. 오랜 오크·병 숙성을 거친 ''그란 레세르바 904·890''으로 유명하다.',
 'A bastion of traditional, long-aged Rioja, famed for its Gran Reserva 904 and 890 after extended oak and bottle ageing.',
 NOW(6), NOW(6)),
('보데가스 무가', 'Bodegas Muga', '스페인', '리오하 (아로)', 'https://www.bodegasmuga.com', 1932,
 '아로의 가족 경영 명가. 자체 쿠퍼리지(통 제작)를 갖추고 전통 방식의 리오하를 만든다.',
 'A family estate in Haro with its own in-house cooperage, producing Rioja in the traditional manner.',
 NOW(6), NOW(6)),
('로페스 데 에레디아', 'R. López de Heredia', '스페인', '리오하 (아로)', 'https://www.lopezdeheredia.com', 1877,
 '시간이 멈춘 듯한 초전통주의 리오하의 상징. 수십 년 숙성된 ''비냐 톤도니아'' 화이트·레드로 컬트적 인기를 누린다.',
 'An icon of ultra-traditional, time-frozen Rioja, with a cult following for its decades-aged "Viña Tondonia" whites and reds.',
 NOW(6), NOW(6)),
('베가 시실리아', 'Vega Sicilia', '스페인', '리베라 델 두에로', 'https://www.vegasicilia.com', 1864,
 '스페인 최고의 와이너리로 꼽히는 리베라 델 두에로의 정점. 10년 넘게 숙성하는 ''우니코''로 유명하다.',
 'Regarded as Spain''s greatest winery and the summit of Ribera del Duero, famed for its decade-plus-aged "Único".',
 NOW(6), NOW(6)),
('도미니오 데 핑구스', 'Dominio de Pingus', '스페인', '리베라 델 두에로', NULL, 1995,
 '덴마크 출신 양조가 피터 시섹이 만든 컬트 와이너리. 극소량 생산되는 ''핑구스''는 스페인 최고가 와인 중 하나다.',
 'A cult winery created by Danish winemaker Peter Sisseck, whose tiny-volume "Pingus" is among Spain''s most expensive wines.',
 NOW(6), NOW(6)),
('보데가스 알레한드로 페르난데스 (페스케라)', 'Bodegas Alejandro Fernández (Pesquera)', '스페인', '리베라 델 두에로', 'https://www.grupopesquera.com', 1972,
 '리베라 델 두에로를 세계에 알린 선구자. 100% 템프라니요 ''페스케라''로 명성을 얻었다.',
 'A pioneer who put Ribera del Duero on the world map, earning fame with the 100% Tempranillo "Pesquera".',
 NOW(6), NOW(6)),
('알바로 팔라시오스', 'Álvaro Palacios', '스페인', '프리오라트', 'https://www.alvaropalacios.com', 1989,
 '프리오라트 부흥을 이끈 양조가의 와이너리. 단일 밭 ''레르미타''로 스페인 정상급 와인을 만든다.',
 'The winery of the vintner who spearheaded the revival of Priorat, crafting top-tier Spanish wine with its single-vineyard "L''Ermita".',
 NOW(6), NOW(6)),
('클로스 모가도르', 'Clos Mogador', '스페인', '프리오라트', 'https://www.closmogador.com', 1979,
 '르네 바르비에가 설립한 프리오라트 부흥의 또 다른 주역. 프리오라트 최초의 단일 와이너리 등급(Vi de Finca)을 받았다.',
 'Founded by René Barbier, another driving force of the Priorat revival and the first to earn the region''s single-estate "Vi de Finca" status.',
 NOW(6), NOW(6)),
-- ===================== 스페인 — 셰리 (Jerez) =====================
('곤살레스 비아스 (티오 페페)', 'González Byass (Tío Pepe)', '스페인', '헤레스 (셰리)', 'https://www.gonzalezbyass.com', 1835,
 '세계에서 가장 유명한 피노 셰리 ''티오 페페''를 만드는 헤레스의 대형 보데가.',
 'The large Jerez bodega behind "Tío Pepe," the world''s most famous Fino sherry.',
 NOW(6), NOW(6)),
('보데가스 루스타우', 'Bodegas Lustau', '스페인', '헤레스 (셰리)', 'https://www.lustau.es', 1896,
 '''알마세니스타'' 솔레라 셀렉션으로 셰리의 다양성을 알린 명가. 폭넓은 고품질 셰리로 정평이 나 있다.',
 'A house celebrated for showcasing sherry''s diversity through its "Almacenista" solera selections and a broad range of high-quality sherries.',
 NOW(6), NOW(6)),
('보데가스 바르바디요', 'Bodegas Barbadillo', '스페인', '산루카르 (만사니야)', 'https://www.barbadillo.com', 1821,
 '산루카르 데 바라메다의 명가. 해풍을 머금은 만사니야 셰리의 대표 생산자다.',
 'A leading house in Sanlúcar de Barrameda, the foremost producer of sea-influenced Manzanilla sherry.',
 NOW(6), NOW(6)),
('오스보르네', 'Osborne', '스페인', '엘 푸에르토 데 산타 마리아', 'https://www.osborne.es', 1772,
 '스페인 도로변의 검은 황소 실루엣으로 유명한 셰리·브랜디 명가.',
 'A sherry and brandy house famed for the black bull silhouette that dots Spanish roadsides.',
 NOW(6), NOW(6)),
-- ===================== 포르투갈 — 포트 (Port) / 마데이라 =====================
('테일러스', 'Taylor''s', '포르투갈', '도루 (포트)', 'https://www.taylor.pt', 1692,
 '빈티지 포트의 기준으로 꼽히는 명문 포트 하우스. 묵직하고 장기 숙성형 스타일로 유명하다.',
 'A benchmark Port house for Vintage Port, renowned for its powerful, long-ageing style.',
 NOW(6), NOW(6)),
('그라함스', 'Graham''s', '포르투갈', '도루 (포트)', 'https://www.grahams-port.com', 1820,
 '시밍턴 가문이 운영하는 명문 포트 하우스. 풍만하고 달콤한 스타일과 ''식스 그레이프스''로 유명하다.',
 'A prestigious Port house run by the Symington family, known for a rich, sweet style and its "Six Grapes" reserve.',
 NOW(6), NOW(6)),
('폰세카', 'Fonseca', '포르투갈', '도루 (포트)', 'https://www.fonseca.pt', 1815,
 '농밀하고 화려한 스타일의 명문 포트 하우스. 빈티지 포트의 최정상으로 꼽힌다.',
 'A prestigious Port house with a rich, flamboyant style, ranked among the finest producers of Vintage Port.',
 NOW(6), NOW(6)),
('다우스', 'Dow''s', '포르투갈', '도루 (포트)', 'https://www.dows-port.com', 1798,
 '시밍턴 가문의 포트 하우스. 상대적으로 드라이한 빈티지 포트 스타일로 정평이 나 있다.',
 'A Symington-family Port house esteemed for its comparatively dry style of Vintage Port.',
 NOW(6), NOW(6)),
('킨타 두 노발', 'Quinta do Noval', '포르투갈', '도루 (포트)', 'https://www.quintadonoval.com', 1715,
 '전설적인 ''나시오날'' 빈티지 포트로 유명한 싱글 킨타. 접목하지 않은 포도나무에서 극소량을 생산한다.',
 'A single quinta famed for its legendary "Nacional" Vintage Port, produced in tiny quantities from ungrafted vines.',
 NOW(6), NOW(6)),
('니포트', 'Niepoort', '포르투갈', '도루 (포트)', 'https://www.niepoort-vinhos.com', 1842,
 '5대째 가족 경영 포트 하우스. 빼어난 포트와 함께 도루 스틸 와인의 선구자로도 유명하다.',
 'A fifth-generation family Port house, celebrated for outstanding Ports and as a pioneer of Douro still wines.',
 NOW(6), NOW(6)),
('블랜디스', 'Blandy''s', '포르투갈', '마데이라', 'https://www.blandys.com', 1811,
 '마데이라 섬의 대표 가족 와인 하우스. 수백 년 숙성 가능한 주정강화 와인 마데이라로 유명하다.',
 'The leading family wine house of Madeira island, famed for fortified Madeira wines capable of ageing for centuries.',
 NOW(6), NOW(6)),
('소그라페 (마테우스)', 'Sogrape', '포르투갈', '도루 / 다웅', 'https://www.sograpevinhos.com', 1942,
 '포르투갈 최대의 와인 그룹. 세계적 인기를 끈 로제 ''마테우스''로 출발해 다수의 명품 에스테이트를 거느린다.',
 'Portugal''s largest wine group, which began with the globally popular "Mateus" rosé and now owns numerous prestige estates.',
 NOW(6), NOW(6)),
-- ===================== 독일 / 오스트리아 =====================
('에곤 뮐러', 'Egon Müller (Scharzhof)', '독일', '모젤 (자르)', 'https://www.scharzhof.de', 1797,
 '세계 최고의 리슬링으로 꼽히는 모젤의 전설적 에스테이트. 샤르츠호프베르거 아우스레제·TBA는 경매 최고가를 기록한다.',
 'A legendary Mosel estate producing what many call the world''s finest Riesling, whose Scharzhofberger Auslese and TBA fetch record auction prices.',
 NOW(6), NOW(6)),
('닥터 로젠', 'Dr. Loosen', '독일', '모젤', 'https://www.drloosen.com', 1988,
 '모젤 리슬링을 세계에 알린 에른스트 로젠의 에스테이트. 오래된 그랑 크뤼 밭의 표현력으로 유명하다.',
 'The estate of Ernst Loosen, who brought Mosel Riesling to the world, famed for the expressiveness of its old grand cru sites.',
 NOW(6), NOW(6)),
('요한 요제프 프륌', 'Joh. Jos. Prüm', '독일', '모젤', NULL, 1911,
 '모젤의 전설적 가족 에스테이트. 베른카스텔러 존넨우어 등에서 극도로 정교하고 장기 숙성형 리슬링을 만든다.',
 'A legendary Mosel family estate producing exquisitely precise, age-worthy Riesling from sites like the Wehlener Sonnenuhr.',
 NOW(6), NOW(6)),
('로베르트 바일', 'Weingut Robert Weil', '독일', '라인가우', 'https://www.weingut-robert-weil.com', 1875,
 '라인가우의 정상급 리슬링 에스테이트. 드라이부터 귀부 와인까지 폭넓은 스펙트럼으로 유명하다.',
 'A top Rheingau Riesling estate famed for a wide spectrum from dry wines to nobly sweet bottlings.',
 NOW(6), NOW(6)),
('F.X. 피흘러', 'F.X. Pichler', '오스트리아', '바하우', 'https://www.fx-pichler.at', 1898,
 '바하우의 정상급 에스테이트. 진하고 응축된 그뤼너 펠트리너·리슬링으로 오스트리아 화이트의 기준을 세웠다.',
 'A leading Wachau estate that set the standard for Austrian whites with its rich, concentrated Grüner Veltliner and Riesling.',
 NOW(6), NOW(6)),
('브륀들마이어', 'Bründlmayer', '오스트리아', '캄프탈', 'https://www.bruendlmayer.at', 1860,
 '캄프탈의 명문 에스테이트. 그뤼너 펠트리너와 함께 오스트리아 스파클링(젝트)의 선두주자로 꼽힌다.',
 'A leading Kamptal estate, a frontrunner in Austrian sparkling (Sekt) as well as Grüner Veltliner.',
 NOW(6), NOW(6)),
-- ===================== 미국 — 나파 밸리 (Napa Valley) =====================
('오퍼스 원', 'Opus One', '미국', '나파 밸리', 'https://www.opusonewinery.com', 1979,
 '로버트 몬다비와 무통 로칠드의 합작으로 탄생한 나파의 상징적 와이너리. 보르도 블렌드 단일 와인만 만든다.',
 'An iconic Napa winery born of a partnership between Robert Mondavi and Mouton Rothschild, producing a single Bordeaux-blend wine.',
 NOW(6), NOW(6)),
('스크리밍 이글', 'Screaming Eagle', '미국', '나파 밸리 (오크빌)', NULL, 1986,
 '나파 컬트 카베르네의 정점. 극소량 생산과 회원제 판매로 세계 최고가 신대륙 와인 중 하나가 되었다.',
 'The pinnacle of Napa cult Cabernet; tiny production and mailing-list-only sales make it one of the most expensive New World wines.',
 NOW(6), NOW(6)),
('할란 이스테이트', 'Harlan Estate', '미국', '나파 밸리 (오크빌)', 'https://www.harlanestate.com', 1984,
 '''캘리포니아의 1등급''을 표방하며 설립된 컬트 와이너리. 오크빌 산비탈의 보르도 블렌드로 명성을 얻었다.',
 'A cult winery founded with the ambition of a "California First Growth," celebrated for its Oakville hillside Bordeaux blend.',
 NOW(6), NOW(6)),
('로버트 몬다비 와이너리', 'Robert Mondavi Winery', '미국', '나파 밸리 (오크빌)', 'https://www.robertmondaviwinery.com', 1966,
 '캘리포니아 와인을 세계 수준으로 끌어올린 선구자. 나파 부흥의 상징적 와이너리다.',
 'A pioneer who raised California wine to world class, an emblematic winery of the Napa renaissance.',
 NOW(6), NOW(6)),
('스택스 립 와인 셀러스', 'Stag''s Leap Wine Cellars', '미국', '나파 밸리', 'https://www.stagsleapwinecellars.com', 1970,
 '1976년 ''파리의 심판''에서 보르도를 꺾고 우승한 카베르네로 캘리포니아 와인의 위상을 바꾼 와이너리.',
 'The winery whose Cabernet beat Bordeaux at the 1976 "Judgment of Paris," transforming the standing of California wine.',
 NOW(6), NOW(6)),
('리지 빈야드', 'Ridge Vineyards', '미국', '캘리포니아 (산타크루즈 산맥)', 'https://www.ridgewine.com', 1962,
 '''파리의 심판''에 출전한 ''몬테 벨로'' 카베르네와 올드 바인 진판델로 유명한 컬트 와이너리.',
 'A cult winery famed for its "Monte Bello" Cabernet — a Judgment of Paris contender — and its old-vine Zinfandels.',
 NOW(6), NOW(6)),
('케이머스', 'Caymus Vineyards', '미국', '나파 밸리 (러더퍼드)', 'https://www.caymus.com', 1972,
 '와그너 가족이 운영하는 나파의 인기 와이너리. 농밀하고 풍만한 카베르네 소비뇽으로 사랑받는다.',
 'A popular Napa winery run by the Wagner family, beloved for its rich, plush Cabernet Sauvignon.',
 NOW(6), NOW(6)),
('도미누스 이스테이트', 'Dominus Estate', '미국', '나파 밸리 (용트빌)', 'https://www.dominusestate.com', 1983,
 '페트뤼스의 크리스티앙 무엑스가 설립한 나파 와이너리. 옛 나파누크 밭에서 절제된 보르도풍 와인을 만든다.',
 'A Napa winery founded by Christian Moueix of Petrus, producing restrained, Bordeaux-styled wine from the historic Napanook vineyard.',
 NOW(6), NOW(6)),
('샤토 몬텔레나', 'Chateau Montelena', '미국', '나파 밸리 (캘리스토가)', 'https://www.montelena.com', 1882,
 '''파리의 심판''에서 부르고뉴를 꺾고 우승한 샤르도네로 유명한 역사적 와이너리.',
 'A historic winery famed for the Chardonnay that beat white Burgundy at the "Judgment of Paris".',
 NOW(6), NOW(6)),
('하이츠 셀러', 'Heitz Cellar', '미국', '나파 밸리 (세인트헬레나)', 'https://www.heitzcellar.com', 1961,
 '단일 밭 카베르네의 선구자. 전설적인 ''마사스 빈야드'' 카베르네로 나파의 역사를 쓴 와이너리다.',
 'A pioneer of single-vineyard Cabernet, a Napa landmark thanks to its legendary "Martha''s Vineyard" bottling.',
 NOW(6), NOW(6)),
('인글눅', 'Inglenook', '미국', '나파 밸리 (러더퍼드)', 'https://www.inglenook.com', 1879,
 '19세기 나파의 명문이었으나 20세기 중반 쇠락한 역사적 와이너리. 영화감독 프랜시스 포드 코폴라가 부지·브랜드를 사들여 부활시켰다.',
 'A 19th-century Napa landmark that declined mid-20th century, then revived after filmmaker Francis Ford Coppola reunited the estate and brand.',
 NOW(6), NOW(6)),
('베린저', 'Beringer Vineyards', '미국', '나파 밸리 (세인트헬레나)', 'https://www.beringer.com', 1876,
 '금주법 시대에도 미사용 포도주 명목으로 가동을 이어간, 나파에서 가장 오래 연속 운영된 와이너리.',
 'The longest continuously operating winery in Napa, which kept running through Prohibition by making sacramental wine.',
 NOW(6), NOW(6)),
('슈램스버그', 'Schramsberg', '미국', '나파 밸리 (캘리스토가)', 'https://www.schramsberg.com', 1862,
 '미국 프리미엄 스파클링 와인의 선구자. 1972년 닉슨의 중국 방문 ''평화를 위한 건배''에 사용되며 유명해졌다.',
 'A pioneer of American premium sparkling wine, made famous when it was served at Nixon''s 1972 "Toast to Peace" in China.',
 NOW(6), NOW(6)),
-- ===================== 미국 — 소노마 / 오리건 / 워싱턴 =====================
('키슬러 빈야드', 'Kistler Vineyards', '미국', '소노마', 'https://www.kistlervineyards.com', 1978,
 '부르고뉴풍 단일 밭 샤르도네·피노 누아로 컬트적 인기를 누리는 소노마의 명가.',
 'A Sonoma estate with a cult following for its Burgundian single-vineyard Chardonnay and Pinot Noir.',
 NOW(6), NOW(6)),
('윌리엄스 셀리엠', 'Williams Selyem', '미국', '소노마 (러시안 리버 밸리)', 'https://www.williamsselyem.com', 1981,
 '러시안 리버 밸리 피노 누아 붐을 일으킨 선구자. 회원제 판매와 단일 밭 피노로 유명하다.',
 'A pioneer who sparked the Russian River Valley Pinot Noir boom, known for mailing-list sales and single-vineyard Pinot.',
 NOW(6), NOW(6)),
('도멘 드루앵 오리건', 'Domaine Drouhin Oregon', '미국', '오리건 (윌래밋 밸리)', 'https://www.domainedrouhin.com', 1987,
 '부르고뉴 명가 조제프 드루앵이 오리건에 세운 와이너리. 윌래밋 밸리 피노 누아의 위상을 끌어올렸다.',
 'An Oregon winery established by the Burgundian house Joseph Drouhin, which elevated the standing of Willamette Valley Pinot Noir.',
 NOW(6), NOW(6)),
('아이리 빈야드', 'The Eyrie Vineyards', '미국', '오리건 (윌래밋 밸리)', 'https://www.eyrievineyards.com', 1965,
 '윌래밋 밸리에 처음 피노 누아를 심은 오리건 와인의 개척자.',
 'The pioneer of Oregon wine, the first to plant Pinot Noir in the Willamette Valley.',
 NOW(6), NOW(6)),
('퀼세다 크릭', 'Quilceda Creek', '미국', '워싱턴 (컬럼비아 밸리)', 'https://www.quilcedacreek.com', 1979,
 '워싱턴주 최정상 카베르네 소비뇽 생산자. 만점 평점을 여러 번 받은 컬트 와이너리다.',
 'Washington State''s premier Cabernet Sauvignon producer, a cult winery with multiple perfect scores.',
 NOW(6), NOW(6)),
('샤토 생 미셸', 'Chateau Ste. Michelle', '미국', '워싱턴 (컬럼비아 밸리)', 'https://www.ste-michelle.com', 1934,
 '워싱턴주 와인 산업을 일군 대표 와이너리. 독일 닥터 로젠과 협업한 ''에로이카'' 리슬링으로도 유명하다.',
 'The flagship winery that built Washington''s wine industry, also known for "Eroica" Riesling made with Germany''s Dr. Loosen.',
 NOW(6), NOW(6)),
-- ===================== 아르헨티나 (멘도사) =====================
('카테나 사파타', 'Catena Zapata', '아르헨티나', '멘도사', 'https://www.catenawines.com', 1902,
 '아르헨티나 말벡을 세계적 수준으로 끌어올린 상징적 와이너리. 고지대 포도밭 연구로 유명하다.',
 'The iconic winery that raised Argentine Malbec to world class, renowned for its research into high-altitude vineyards.',
 NOW(6), NOW(6)),
('아차발 페레르', 'Achaval-Ferrer', '아르헨티나', '멘도사', 'https://www.achaval-ferrer.com', 1998,
 '단일 밭 말벡에 집중하는 멘도사의 부티크 와이너리. 농축미와 우아함의 균형으로 호평받는다.',
 'A boutique Mendoza winery focused on single-vineyard Malbec, praised for balancing concentration with elegance.',
 NOW(6), NOW(6)),
('수카르디', 'Familia Zuccardi', '아르헨티나', '멘도사 (우코 밸리)', 'https://www.zuccardiwines.com', 1963,
 '우코 밸리 떼루아 표현의 선두주자. 콘크리트 양조와 석회질 토양 와인으로 세계적 주목을 받는다.',
 'A leader in expressing Uco Valley terroir, drawing global attention with its concrete-fermented, limestone-soil wines.',
 NOW(6), NOW(6)),
('보데가 노턴', 'Bodega Norton', '아르헨티나', '멘도사', 'https://www.norton.com.ar', 1895,
 '멘도사의 역사적 대형 와이너리. 안정적 품질의 말벡으로 아르헨티나 와인 대중화에 기여했다.',
 'A historic large-scale Mendoza winery that helped popularise Argentine wine with consistently reliable Malbec.',
 NOW(6), NOW(6)),
('슈발 데 안데스', 'Cheval des Andes', '아르헨티나', '멘도사', 'https://www.chevaldesandes.com', 1999,
 '보르도 샤토 슈발 블랑과 협업해 탄생한 ''안데스의 그랑 크뤼''. 말벡·카베르네 블렌드를 만든다.',
 'An "Andean Grand Cru" born of a partnership with Bordeaux''s Château Cheval Blanc, producing a Malbec-Cabernet blend.',
 NOW(6), NOW(6)),
-- ===================== 칠레 =====================
('콘차 이 토로', 'Concha y Toro', '칠레', '마이포 밸리', 'https://www.conchaytoro.com', 1883,
 '라틴아메리카 최대의 와이너리. ''까시예로 델 디아블로''와 플래그십 ''돈 멜초르''로 세계적 명성을 얻었다.',
 'The largest winery in Latin America, world-famous for "Casillero del Diablo" and its flagship "Don Melchor".',
 NOW(6), NOW(6)),
('알마비바', 'Almaviva', '칠레', '마이포 밸리', 'https://www.almavivawinery.com', 1997,
 '콘차 이 토로와 무통 로칠드의 합작 와이너리. 칠레를 대표하는 프리미엄 보르도 블렌드를 만든다.',
 'A joint venture between Concha y Toro and Mouton Rothschild, producing Chile''s flagship premium Bordeaux blend.',
 NOW(6), NOW(6)),
('비냐 에라수리스', 'Viña Errázuriz', '칠레', '아콩카과 밸리', 'https://www.errazuriz.com', 1870,
 '2004년 ''베를린 시음회''에서 보르도·토스카나 명품을 꺾은 ''비녜도 차드윅''으로 유명한 역사적 와이너리.',
 'A historic winery famed for "Viñedo Chadwick," which beat top Bordeaux and Tuscany at the 2004 "Berlin Tasting".',
 NOW(6), NOW(6)),
('몬테스', 'Montes', '칠레', '콜차구아 밸리', 'https://www.monteswines.com', 1988,
 '칠레 프리미엄 와인의 선구자. 플래그십 ''몬테스 알파 M''과 ''푸르푸리오''로 명성을 얻었다.',
 'A pioneer of premium Chilean wine, renowned for its flagship "Montes Alpha M" and "Purple Angel".',
 NOW(6), NOW(6)),
('비냐 산타 리타', 'Viña Santa Rita', '칠레', '마이포 밸리', 'https://www.santarita.com', 1880,
 '칠레의 역사적 대형 와이너리. ''120'' 시리즈와 프리미엄 ''카사 레알''로 잘 알려져 있다.',
 'A historic large Chilean winery well known for its "120" range and the premium "Casa Real".',
 NOW(6), NOW(6)),
('비냐 세냐', 'Seña', '칠레', '아콩카과 밸리', 'https://www.sena.cl', 1995,
 '에두아르도 차드윅과 로버트 몬다비가 함께 만든 칠레 아이콘 와인. 바이오다이내믹 보르도 블렌드를 만든다.',
 'A Chilean icon wine created by Eduardo Chadwick and Robert Mondavi, producing a biodynamic Bordeaux blend.',
 NOW(6), NOW(6)),
-- ===================== 호주 =====================
('펜폴즈', 'Penfolds', '호주', '남호주 (바로사 밸리)', 'https://www.penfolds.com', 1844,
 '호주를 대표하는 와이너리. 다지역 블렌드 시라즈 ''그랜지''는 호주 최고의 아이콘 와인으로 꼽힌다.',
 'Australia''s flagship winery, whose multi-region Shiraz "Grange" is regarded as the country''s greatest icon wine.',
 NOW(6), NOW(6)),
('헨쉬케', 'Henschke', '호주', '남호주 (에덴 밸리)', 'https://www.henschke.com.au', 1868,
 '6대째 가족 경영 와이너리. 100년 넘은 올드 바인에서 나오는 싱글 빈야드 시라즈 ''힐 오브 그레이스''로 유명하다.',
 'A sixth-generation family winery famed for "Hill of Grace," a single-vineyard Shiraz from vines over a century old.',
 NOW(6), NOW(6)),
('윈스', 'Wynns Coonawarra Estate', '호주', '남호주 (쿠나와라)', 'https://www.wynns.com.au', 1891,
 '쿠나와라의 ''테라 로사'' 토양을 대표하는 와이너리. 가성비 좋은 카베르네 소비뇽으로 유명하다.',
 'The standard-bearer for Coonawarra''s "terra rossa" soils, famed for great-value Cabernet Sauvignon.',
 NOW(6), NOW(6)),
('토브렉', 'Torbreck', '호주', '남호주 (바로사 밸리)', 'https://www.torbreck.com', 1994,
 '바로사 올드 바인 시라즈의 현대적 강자. 진하고 풍만한 론풍 블렌드로 명성을 얻었다.',
 'A modern force in Barossa old-vine Shiraz, renowned for rich, plush Rhône-style blends.',
 NOW(6), NOW(6)),
('얄룸바', 'Yalumba', '호주', '남호주 (바로사 밸리)', 'https://www.yalumba.com', 1849,
 '호주에서 가장 오래된 가족 경영 와이너리. 자체 묘목원과 통 제작소를 갖추고 비오니에로도 유명하다.',
 'Australia''s oldest family-owned winery, with its own nursery and cooperage, also celebrated for Viognier.',
 NOW(6), NOW(6)),
('다렌버그', 'd''Arenberg', '호주', '남호주 (맥라렌 베일)', 'https://www.darenberg.com.au', 1912,
 '맥라렌 베일의 가족 와이너리. 기발한 와인 이름과 ''큐브'' 큐브형 건물로도 유명하다.',
 'A McLaren Vale family winery known for its quirky wine names and its landmark "Cube" building.',
 NOW(6), NOW(6)),
('리우윈 이스테이트', 'Leeuwin Estate', '호주', '서호주 (마가렛 리버)', 'https://www.leeuwinestate.com.au', 1973,
 '마가렛 리버를 세계에 알린 와이너리. 최고급 ''아트 시리즈'' 샤르도네로 명성이 높다.',
 'The winery that put Margaret River on the map, renowned for its top-tier "Art Series" Chardonnay.',
 NOW(6), NOW(6)),
('컬른', 'Cullen Wines', '호주', '서호주 (마가렛 리버)', 'https://www.cullenwines.com.au', 1971,
 '마가렛 리버의 바이오다이내믹 선구 와이너리. 카베르네·메를로 블렌드 ''다이애나 매들린''으로 유명하다.',
 'A biodynamic pioneer in Margaret River, famed for its Cabernet-Merlot blend "Diana Madeline".',
 NOW(6), NOW(6)),
('타빌크', 'Tahbilk', '호주', '빅토리아 (낵비 밸리)', 'https://www.tahbilk.com.au', 1860,
 '빅토리아의 역사적 가족 와이너리. 1860년대에 심은 세계에서 가장 오래된 마르산 포도나무로 유명하다.',
 'A historic Victorian family winery famed for some of the world''s oldest Marsanne vines, planted in the 1860s.',
 NOW(6), NOW(6)),
-- ===================== 뉴질랜드 =====================
('클라우디 베이', 'Cloudy Bay', '뉴질랜드', '말버러', 'https://www.cloudybay.co.nz', 1985,
 '말버러 소비뇽 블랑을 세계에 알린 상징적 와이너리. 뉴질랜드 화이트 와인의 대명사로 통한다.',
 'The iconic winery that brought Marlborough Sauvignon Blanc to the world, synonymous with New Zealand white wine.',
 NOW(6), NOW(6)),
('펠튼 로드', 'Felton Road', '뉴질랜드', '센트럴 오타고', 'https://www.feltonroad.com', 1991,
 '센트럴 오타고 피노 누아의 정점으로 꼽히는 바이오다이내믹 와이너리. 단일 밭 피노로 컬트적 인기를 누린다.',
 'A biodynamic winery regarded as the pinnacle of Central Otago Pinot Noir, with a cult following for its single-vineyard bottlings.',
 NOW(6), NOW(6)),
('빌라 마리아', 'Villa Maria', '뉴질랜드', '말버러 / 호크스 베이', 'https://www.villamaria.co.nz', 1961,
 '뉴질랜드를 대표하는 대형 와이너리. 전 와이너리 스크루캡 도입을 선도한 것으로도 유명하다.',
 'A leading large New Zealand winery, also famed for pioneering an all-estate switch to screwcaps.',
 NOW(6), NOW(6)),
('테 마타 이스테이트', 'Te Mata Estate', '뉴질랜드', '호크스 베이', 'https://www.temata.co.nz', 1896,
 '뉴질랜드에서 가장 오래된 와이너리 중 하나. 보르도 블렌드 ''콜레인''으로 명성이 높다.',
 'One of New Zealand''s oldest wineries, renowned for its Bordeaux-blend "Coleraine".',
 NOW(6), NOW(6)),
-- ===================== 남아프리카공화국 =====================
('클라인 콘스탄시아', 'Klein Constantia', '남아프리카공화국', '콘스탄시아', 'https://www.kleinconstantia.com', 1685,
 '18~19세기 유럽 왕실이 사랑한 전설적 스위트 와인 ''뱅 드 콘스탄스''를 부활시킨 역사적 에스테이트.',
 'A historic estate that revived "Vin de Constance," the legendary sweet wine beloved by European royalty in the 18th–19th centuries.',
 NOW(6), NOW(6)),
('카논콥', 'Kanonkop', '남아프리카공화국', '스텔렌보스', 'https://www.kanonkop.co.za', 1910,
 '''남아공의 1등급''으로 불리는 명가. 토착 품종 피노타지와 보르도 블렌드 ''폴 사우어''로 유명하다.',
 'An estate dubbed "the First Growth of South Africa," famed for the native Pinotage and its Bordeaux blend "Paul Sauer".',
 NOW(6), NOW(6)),
('베르헬레헌', 'Vergelegen', '남아프리카공화국', '스텔렌보스 (소머셋 웨스트)', 'https://www.vergelegen.co.za', 1700,
 '300년 역사의 역사적 에스테이트. 우아한 보르도 블렌드와 화이트로 남아공 정상급 평가를 받는다.',
 'A 300-year-old historic estate rated among South Africa''s best for its elegant Bordeaux blends and whites.',
 NOW(6), NOW(6)),
('미어러스트', 'Meerlust', '남아프리카공화국', '스텔렌보스', 'https://www.meerlust.co.za', 1693,
 '8대째 가족 경영 역사적 에스테이트. 보르도 블렌드 ''루빅''으로 명성이 높다.',
 'A historic eighth-generation family estate, renowned for its Bordeaux blend "Rubicon".',
 NOW(6), NOW(6)),
('부켄하우츠클루프', 'Boekenhoutskloof', '남아프리카공화국', '프란슈후크', 'https://www.boekenhoutskloof.co.za', 1776,
 '''세븐 시스터스''와 시라즈로 유명한 현대 남아공의 정상급 와이너리. 대중적 ''울프트랩''으로도 잘 알려져 있다.',
 'A top modern South African winery famed for its Syrah and "The Chocolate Block," also widely known for the value "Wolftrap".',
 NOW(6), NOW(6)),
-- ===================== 신흥·이색 산지 — 일본 =====================
('샤토 메르시앙', 'Château Mercian', '일본', '야마나시', 'https://www.chateaumercian.com', 1877,
 '일본 와인의 역사적 선구자. 토착 품종 고슈(甲州)와 머스캣 베일리 A로 재패니즈 와인을 세계에 알렸다.',
 'A historic pioneer of Japanese wine, championing native Koshu and Muscat Bailey A on the world stage.',
 NOW(6), NOW(6)),
('그레이스 와인 (주오 부도슈)', 'Grace Wine (Chuo Budoshu)', '일본', '야마나시 (가쓰누마)', 'https://www.grace-wine.com', 1923,
 '고슈 품종 화이트로 국제 무대에서 호평받는 가족 경영 와이너리. 일본 와인의 품질 혁신을 이끌었다.',
 'A family winery acclaimed internationally for its Koshu whites, a driver of quality innovation in Japanese wine.',
 NOW(6), NOW(6)),
('산토리 토미노오카', 'Suntory Tomi no Oka', '일본', '야마나시', 'https://www.suntory.co.jp/wine/tomi', 1909,
 '산토리가 운영하는 야마나시의 역사적 와이너리. 보르도 블렌드와 고슈, 귀부 와인을 만든다.',
 'A historic Yamanashi winery run by Suntory, producing Bordeaux blends, Koshu and noble-rot sweet wines.',
 NOW(6), NOW(6)),
('코코 팜 와이너리', 'Coco Farm & Winery', '일본', '도치기 (아시카가)', 'https://cocowine.com', 1958,
 '장애인 복지시설에서 출발한 독특한 와이너리. 야생 효모 자연 발효 와인으로 컬트적 인기를 누린다.',
 'A unique winery that grew out of a care facility for people with disabilities, with a cult following for its wild-yeast natural wines.',
 NOW(6), NOW(6)),
-- ===================== 신흥·이색 산지 — 중국 =====================
('아오윈', 'Ao Yun', '중국', '윈난', 'https://www.aoyun.wine', 2013,
 'LVMH가 히말라야 고지대 윈난에 세운 초프리미엄 와이너리. 해발 2,600m 포도밭의 보르도 블렌드로 세계를 놀라게 했다.',
 'An ultra-premium winery established by LVMH in high-altitude Yunnan, astonishing the world with Bordeaux blends from vineyards at 2,600m.',
 NOW(6), NOW(6)),
('장위', 'Changyu', '중국', '산둥 (옌타이)', 'https://www.changyu.com.cn', 1892,
 '중국에서 가장 오래된 대형 와이너리. 100년 넘는 역사로 중국 와인 산업의 토대를 닦았다.',
 'The oldest large-scale winery in China, which laid the foundations of the Chinese wine industry over more than a century.',
 NOW(6), NOW(6)),
('그레이스 비냐드 (이위안)', 'Grace Vineyard', '중국', '산시 (山西)', 'https://www.grace-vineyard.com', 1997,
 '중국 부티크 와인의 선구자. 품질 중심의 보르도 블렌드 ''디퍼런스''와 ''에인절''로 호평받는다.',
 'A pioneer of Chinese boutique wine, praised for its quality-focused Bordeaux blends "Deep Blue" and "Angelina".',
 NOW(6), NOW(6)),
('실버 하이츠 (인써가오디)', 'Silver Heights', '중국', '닝샤', NULL, 2007,
 '닝샤 와인 붐을 이끈 가족 경영 부티크 와이너리. 보르도에서 양조를 배운 딸이 만든 ''더 서밋''으로 유명하다.',
 'A family boutique winery that helped spark the Ningxia wine boom, famed for "The Summit" made by a Bordeaux-trained daughter.',
 NOW(6), NOW(6)),
-- ===================== 신흥·이색 산지 — 인도 =====================
('술라 빈야드', 'Sula Vineyards', '인도', '나시크 (마하라슈트라)', 'https://www.sulavineyards.com', 1999,
 '인도 와인 산업을 사실상 창시한 대표 와이너리. 인도 최대 와인 생산자이자 와인 관광의 중심지다.',
 'The flagship winery widely credited with founding India''s wine industry, the country''s largest producer and a wine-tourism hub.',
 NOW(6), NOW(6)),
('그로버 잠파', 'Grover Zampa Vineyards', '인도', '난디 힐스 (카르나타카)', 'https://www.groverzampa.in', 1988,
 '보르도 자문(미셸 롤랑)을 받아 출발한 인도의 선구적 와이너리. 인도 프리미엄 와인을 대표한다.',
 'A pioneering Indian winery launched with Bordeaux consultancy (Michel Rolland), a flagship of Indian premium wine.',
 NOW(6), NOW(6)),
-- ===================== 신흥·이색 산지 — 영국 =====================
('나이팀버', 'Nyetimber', '영국', '잉글랜드 (웨스트서식스)', 'https://www.nyetimber.com', 1988,
 '잉글리시 스파클링 와인의 선구자. 샹파뉴와 같은 백악질 토양·전통 방식으로 세계적 평가를 받는다.',
 'A pioneer of English sparkling wine, internationally acclaimed for using Champagne''s chalk soils and traditional method.',
 NOW(6), NOW(6)),
('채플 다운', 'Chapel Down', '영국', '잉글랜드 (켄트)', 'https://www.chapeldown.com', 2001,
 '잉글랜드 최대의 와이너리. 전통 방식 스파클링 와인으로 영국 와인 대중화를 이끌었다.',
 'England''s largest winery, which led the popularisation of British wine with its traditional-method sparkling wines.',
 NOW(6), NOW(6)),
('거스본', 'Gusbourne', '영국', '잉글랜드 (켄트)', 'https://www.gusbourne.com', 2004,
 '빈티지·싱글 이스테이트 스파클링만 고집하는 잉글랜드의 프리미엄 와이너리.',
 'A premium English winery committed exclusively to vintage, single-estate sparkling wine.',
 NOW(6), NOW(6)),
-- ===================== 신흥·이색 산지 — 한국 =====================
('그랑꼬또 (그린영농조합)', 'Grand Coteau', '대한민국', '경기 (안산 대부도)', 'https://www.greengray.co.kr', 2000,
 '대부도 포도로 만드는 한국의 대표 와이너리. 캠벨·청수 품종 와인으로 국산 와인의 인지도를 높였다.',
 'A leading Korean winery on Daebudo Island, raising the profile of domestic wine with Campbell and Cheongsu grape wines.',
 NOW(6), NOW(6)),
('여포와인농장', 'Yeopo Wine Farm', '대한민국', '충북 (영동)', NULL, 2005,
 '와인 특구 영동의 대표 농가형 와이너리. 직접 재배한 포도로 만드는 한국 와인으로 알려져 있다.',
 'A leading farm winery in Yeongdong, Korea''s designated wine district, known for wines from its own estate-grown grapes.',
 NOW(6), NOW(6)),
('샤토 마니', 'Chateau Mani', '대한민국', '충북 (영동)', NULL, 1965,
 '국내에서 손꼽히는 오랜 역사의 와이너리. 유기농 포도로 만드는 와인과 와인 체험으로 알려져 있다.',
 'One of Korea''s longest-standing wineries, known for organic-grape wines and wine-experience tourism.',
 NOW(6), NOW(6)),
('산머루 농원', 'Sanmeoru Farm', '대한민국', '경기 (파주)', NULL, 1996,
 '토종 머루로 와인을 만드는 파주의 와이너리. 머루 와인이라는 한국적 카테고리를 개척했다.',
 'A Paju winery making wine from native "meoru" (wild grape), pioneering a distinctly Korean wine category.',
 NOW(6), NOW(6)),
-- ===================== 신흥·이색 산지 — 기타 (레바논·헝가리·캐나다·그리스) =====================
('샤토 무사', 'Château Musar', '레바논', '베카 밸리', 'https://www.chateaumusar.com', 1930,
 '내전 속에서도 양조를 이어간 레바논의 전설적 와이너리. 독창적이고 장기 숙성형인 레드로 컬트적 추앙을 받는다.',
 'A legendary Lebanese winery that kept making wine through civil war, with a cult reputation for idiosyncratic, age-worthy reds.',
 NOW(6), NOW(6)),
('로열 토카지', 'The Royal Tokaji', '헝가리', '토카이', 'https://www.royal-tokaji.com', 1990,
 '공산정권 붕괴 후 토카이 귀부 와인의 부활을 이끈 와이너리. 와인 평론가 휴 존슨이 공동 설립했다.',
 'A winery that led the revival of Tokaji noble-rot wine after the fall of communism, co-founded by wine writer Hugh Johnson.',
 NOW(6), NOW(6)),
('디즈노쾨', 'Disznókő', '헝가리', '토카이', 'https://www.disznoko.hu', 1992,
 '프랑스 AXA 그룹이 부활시킨 토카이 명가. 역사적 그랑 크뤼 밭에서 아수(Aszú) 귀부 와인을 만든다.',
 'A Tokaji estate revived by France''s AXA group, producing Aszú noble-rot wine from a historic grand cru site.',
 NOW(6), NOW(6)),
('이니스킬린', 'Inniskillin', '캐나다', '온타리오 (나이아가라)', 'https://www.inniskillin.com', 1975,
 '캐나다 아이스와인을 세계에 알린 선구 와이너리. 1991년 비냐쿠르 그랑프리 수상으로 명성을 얻었다.',
 'A pioneering winery that brought Canadian icewine to the world, winning the 1991 Vinexpo Grand Prix d''Honneur.',
 NOW(6), NOW(6)),
('도멘 시갈라스', 'Domaine Sigalas', '그리스', '산토리니', 'https://www.sigalas-wine.com', 1991,
 '화산섬 산토리니의 토착 품종 아시르티코를 세계에 알린 대표 와이너리. 미네랄한 화이트로 유명하다.',
 'A leading Santorini winery that brought the volcanic island''s native Assyrtiko to global attention, famed for its mineral whites.',
 NOW(6), NOW(6)),
('슈흐만 와인스', 'Schuchmann Wines', '조지아', '카헤티', 'https://www.schuchmann-wines.com', 2008,
 '8000년 와인 발상지 조지아의 현대적 대표 와이너리. 전통 크베브리(토기) 양조와 토착 품종 사페라비로 유명하다.',
 'A leading modern winery in Georgia, the 8,000-year cradle of wine, known for traditional qvevri (clay vessel) winemaking and the native Saperavi.',
 NOW(6), NOW(6));
